### ISSUE TITLE
Avatar related work

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#105]
Long term (not alpha release)

- [x] expire cache
- [ ] retry failed fetch occasionally
- [ ] retry after new metadata arrives with a different url
- [x] support SVGs (see rust crate "resvg")
- [ ] animate animated GIFs
- [x] setting to disable avatar fetching
- [x] rounding of corners

**Comment by mikedilger** [comment]
Some of this might be a good first issue.

**Comment by bu5hm4nn** [comment]
You can tick 'rounding of corners' ;-)

**Comment by mikedilger** [comment]
Animated gif support is #543.  The rest I think is done.
