### ISSUE TITLE
Following people doesn't automatically update the UI

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#113]
I don't know about the feed, but it doesn't add the person to the "People" UI even though the follow was successful.

**Comment by mikedilger** [comment]
Restart the client and it will.  It's not rewriting the main subscription on these events yet.  Pretty easy fix I suppose but I just haven't done it yet.

**Comment by fiatjaf** [comment]
I meant the list of people under the "People" tab, not the feed.

But wait, it is working now for me.
