### ISSUE TITLE
Support importing list of followers from kind-3 events

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#115]
Should probably be an optional thing that you have to click a button to do.

**Comment by fiatjaf** [comment]
This is done, I suppose?

**Comment by mikedilger** [comment]
If you meant people that you follow, then yes it is done.  If you meant people that follow you, then no it is not done.

**Comment by mikedilger** [comment]
If I knew how many people followed me I'd probably become afraid to post 😅
