### ISSUE TITLE
Support NIP-19 `nprofile`

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#116]
The `nprofile` identifier contains a list of relays, so it would probably fit easily into Gossip's people-adding flow. It's essentially what NIP-35 was for NIP-05 but for standalone key identifiers.

https://github.com/nostr-protocol/nips/blob/master/19.md

An example: `nprofile1qqsrhuxx8l9ex335q7he0f09aej04zpazpl0ne2cgukyawd24mayt8gpyfmhxue69uhkummnw3ez6an9wf5kv6t9vsh8wetvd3hhyer9wghxuet5fmsq8j`

**Comment by fiatjaf** [comment]
That is just for copypasting, as in: "follow me, I am nprofile1qqsrhuxx8l9ex335q7he0f09aej04zpazpl0ne2cgukyawd24mayt8gpyfmhxue69uhkummnw3ez6an9wf5kv6t9vsh8wetvd3hhyer9wghxuet5fmsq8j on nostr!".

They would also work well as QR codes and links (`nostr:nprofile1qqsrhuxx8l9ex335q7he0f09aej04zpazpl0ne2cgukyawd24mayt8gpyfmhxue69uhkummnw3ez6an9wf5kv6t9vsh8wetvd3hhyer9wghxuet5fmsq8j` or `nostr:name@domain.com` would work nice, what do you think?). But I think no one has implemented these things yet.

**Comment by fiatjaf** [comment]
Yes, to me it sounds right.

**Comment by mikedilger** [comment]
nostr-types now supports a Profile type like this:

````rust
/// A person's profile on nostr which consists of the data needed in order to follow someone.                                                                                     
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Profile {
    /// Their public key                                                                                                                                                          
    pub pubkey: PublicKey,

    /// Some of the relays they post to (when the profile was created)                                                                                                            
    pub relays: Vec<Url>,
}
````

As well as

````rust
    /// Export as a bech32 encoded string ("nprofile")                                                                                                                            
    pub fn try_as_bech32_string(&self) -> Result<String, Error> {
        ...
    }

    /// Import from a bech32 encoded string ("nprofile")                                                                                                                          
    pub fn try_from_bech32_string(s: &str) -> Result<Profile, Error> {
       ....
    }
````

...with working test cases, including the example in NIP-19 tried in both directions.

Gossip doesn't have any changes in this regard yet.

**Comment by mikedilger** [comment]
Done.  Can follow an nprofile.  Shows your own nprofile string.
