### ISSUE TITLE
NIP-05 not getting validated

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#117]
I believe it is only validated for people added directly by NIP-05 identifier.

It would be better if it was validated whenever a "fetch metadata" was triggered for any given user.

**Comment by fiatjaf** [comment]
I was trying to implement this, but I wanted to only trigger a NIP-05 validation when the event had the correct handle, i.e. when it came as a response to a metadata query (to prevent unwanted NIP-05 validations happening due to random factors).

But then from what I see here the `handle` is not used anywhere. Shouldn't it be passed to `process_new_event`?

![2023-01-05-110452_772x407_scrot](https://user-images.githubusercontent.com/1653275/210798421-2d47b455-7ac6-42be-bc96-721ee0f8d115.png)

**Comment by fiatjaf** [comment]
Maybe I am overthinking this and a validation can be safely triggered whenever a `kind 0` is received, and a NIP-05 `dns_id` exists but `dns_id_valid` is false?

**Comment by mikedilger** [comment]
Every event that comes in gets processed in that crate::process module.  That level of processing, however, probably shouldn't be so heavy as to trigger the fetch of nostr.json.  The kind-0 event remains in the globals.events however, and so there could be a global 'update metadata' or just the current per-person 'update metadata' which just looks through the kind-0 events already sitting in memory and updates when you press the button.  If nip05 changed or was new or was not yet valid or was a bit too stale, then the fetch of nostr.json would be in a task::spawn background job which would update the person (and the database) when the result came in.

**Comment by fiatjaf** [comment]
I got about 35% of what you just said, so I think I will try to tackle a different issue next time I sit down in my Rust chair.

**Comment by mikedilger** [comment]
Now that I'm in the code about to do it, it occurs to me to not be so easy.  The 'button' initiates the subscription for their kind-0 data.  How is it then supposed to also initiate the nostr.json fetch?  The results of a subscription are not like the results of a future I could await on. Lemme think on this.

**Comment by fiatjaf** [comment]
> The results of a subscription are not like the results of a future I could await on. Lemme think on this.

Maybe it would be a good abstraction to have a `query()` function for these one-time queries that returned a future and then registered a handler for `EVENT` message results that would then resolve the future. I'm not sure how this would be done in Rust.

**Comment by mikedilger** [comment]
I just pushed the passing of sub handle to process new events.

I think I could write that future. The waker (futures have a waker when you write them yourself) would be woken by the minion whenever events came in satisfying it. Sounds like the right strategy to ease the logic.

**Comment by mikedilger** [comment]
So you can see how the magic happens, I just pushed a branch 'f' with one commit that is HALF of the work needed to implement a future Stream.  The goal is something like this:

````rust
while let Some(event) = overlord.launch_query(url, filters).await.next().await {
        println!("Got event {}", serde_json::to_string(&event).unwrap());
}
````

overlord gets a new 'launch query' function which sets it all up. It starts a minion if needed. It creates a place in GLOBALS.relay_query_data for the incoming events to land temporarily and where the future can pick them up from.  It sends a message to the minion to go do that subscription, and of kind 'query' so the minion knows it has to drop the events into the GLOBALS.relay_query_data under the subscription handle.  It returns a RelayQuery object which implements Stream.

In query.rs we can see how RelayQuery implements Stream.  It uses it's Context to put a 'waker' into the GLOBALS.relay_query_data, so the minion can wake up the future-stream.  It checks for events and returns them, poping them off the list of events that the minion filled (usually just one, but could be more). If the minion set the EOSE flag it completes. One shortcoming still is some relays don't return EOSE and so we need to thread in a timeout as well.

The next commit will do the minion half.  Then I'll do some testing and merge it into master.

But I might sleep a bit first.

**Comment by mikedilger** [comment]
Ok that EventStream distraction isn't fruitful yet and I don't want to make the perfect the enemy of the good. So I'm moving past it.

I went ahead and implemented NIP-05 validation whenever a kind-0 metadata event comes in and whenever it hasn't been checked for 2 weeks if it previously passed, or 1 day if it failed (to be added as settings).  This will check everybody on startup loaded from the database the first time, but for me it wasn't overly intense.  Might have to think about how the dates could get staggered somehow.

**Comment by fiatjaf** [comment]
This is probably a better implementation.
