### ISSUE TITLE
Composing a post:  @mentions!

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#121]
We need it to give a pulldown of users that they can pick from, enter the 'p' tag, and insert a reference to it like `#[N]`

**Comment by fiatjaf** [comment]
This will be the greatest feature of the century.

**Comment by mikedilger** [comment]
There is a somewhat hacky solution on the 'tag' branch which I will try to clean up a bit and merge into master soon.

**Comment by mikedilger** [comment]
I'm leaving this open as I think we should improve the UX, but pushing out the milestone.

**Comment by mikedilger** [comment]
duped by #512 which is now fixed
