### ISSUE TITLE
last_success_at double meaning, can cause events not showing up

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#129]
If you close gossip after a relay has connected but before it has delivered events to you, next time you start we are not asking for those events because we bump `last_success_at` right after we connect, not on `EOSE` like we used to.

I'd like to bump it at `EOSE` but `EOSE` is optional.  I should use NIP-11 (as specified in NIP-15) to find out, and if EOSE is not available, bump `last_success_at` to the created_at timestamp of each event as it comes in.

**Comment by fiatjaf** [comment]
Good. This might be the cause of some issues I experienced with feeds not showing up that didn't look deterministic.

**Comment by mikedilger** [comment]
I have partial code for this on a private branch that I didn't get finished before work this morning. I'm aiming to finish and merge it tonight.

**Comment by mikedilger** [comment]
merged.
