### ISSUE TITLE
Bad deserialization or read?

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#133]
See all these incomplete JSON events I'm getting:

![2023-01-10-220747_1920x1080_scrot](https://user-images.githubusercontent.com/1653275/211694504-eaaf044c-dd5c-4d8b-84ae-231c4b517868.png)

**Comment by mikedilger** [comment]
Me too. I recently added code to help me clarify the error and track this down. They are all kind-3. The ones I checked have 'p' tags in npub format. I intend to be robust enough to handle that, but I'm also trying to contact the authors of the events.

**Comment by mikedilger** [comment]
Oh, and they are not incomplete. It's just that if I logged the entire message it would be 15 screens long.

**Comment by fiatjaf** [comment]
Oh, ok, that makes more sense now.

But if you grab one of these and try to deserialize it through other means, what happens?

**Comment by mikedilger** [comment]
The JSON is fine. Relays probably don't dig deep enough to notice (probably too expensive for a relay).

My nostr-types library does fairly heavy type and validity checking on top of JSON serialization/deserialization. Keys must be hex, must be the right length, URLs must be valid as relay urls, tag fields must be strings and if interpreted as a Url must be a valid relay url, etc, etc.  Those validation errors come through to gossip as serde errors and unfortunately don't explain themselves very well at present, something I should improve upon.

**Comment by mikedilger** [comment]
I don't even check key validity anymore in this case. Closing.
