### ISSUE TITLE
Giant note screwing UI

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#136]
![2023-01-12-110221_959x1058_scrot](https://user-images.githubusercontent.com/1653275/212086814-c878a200-f7ab-4a84-a5f0-a0b89ec740a5.png)

This is it: 9a0765be9f669cd7fe54ee738d4d59f9c82c6084bcb6099f319b79c02463c7c4

**Comment by mikedilger** [comment]
I'll push it upstream.

In the mean time, you can choose from the hamburger menu to dismiss that post.  Dismissing a post is temporary, until you restart the client.

**Comment by mikedilger** [comment]
Filed upstream as https://github.com/emilk/egui/issues/2578

**Comment by mikedilger** [comment]
I don't have this event anymore and haven't seen this kind of UI shift for ages. Closing.
