### ISSUE TITLE
Another giant note screwing UI

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#144]
fiatjaf's poem(?) 8e2c2a78b5748654217318d5dc98d92a3d94688b56e24479503cb9a5e21a0046 is so long that when scrolled down far enough, it is considered outside of the reasonable viewable range and isn't actually rendered anymore (a placeholder rendering takes place instead).  That means you can't get to the bottom, can't get to the reply buttons, etc.

**Comment by fiatjaf** [comment]
Oops.

**Comment by fiatjaf** [comment]
That's Fernando Pessoa.

**Comment by mikedilger** [comment]
I haven't seen any problems with long note handling in ages. Closing.
