### ISSUE TITLE
private key management

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#15]
Never display it (but possibly PKCS export it later on)

Add Drop traits to always zero out the memory.

Store it in the database encrypted with a PIN number that they enter to use it.

Add Drop traits on the PIN number too.

**Comment by mikedilger** [comment]
3 levels of private key:

Weak:  Import your private key: _________

Medium:  Generate a keypair 
- We will never display it
- We will never write it to disk in unencrypted form, but we will write it to disk encrypted under your PIN
- We will zero memory that contained key/secret material before freeing it

Strong: Use a hardware token
- The private key material will be generated on the token and never leave the token.

**Comment by ok300** [comment]
Medium-Strong: Private key is maintained in a browser extension like nos2x or Alby

* The app asks for permission to sign events
* The private key is never revealed to the app

**Comment by mikedilger** [comment]
I know about nos2x for the browser.  Is Alby for a desktop @ok300?  I'll add support it eventually if so.

**Comment by ok300** [comment]
AFAIK its also a browser extension.

Sorry I hadn't realized this isn't a webapp. I saw the html and js files in your repo and assumed it runs in a browser.

**Comment by mikedilger** [comment]
Yeah it's confusing. This runs partially as a webapp on top of (for linux at least) webkit gtk3, and partially as a native app.

**Comment by mikedilger** [comment]
Actual work on private keys is tracked under issue #53.  The main gist of this has been implemented, so closing.
