### ISSUE TITLE
missing Origin header

### ISSUE THREAD

**Issue by davestgermain** [mikedilger/gossip#165]
My relay `wss://relay-pub.deschooling.us` blocks gossip because you aren't sending an Origin header in the request. I'm using an origin blacklist because it's an easy way of filtering out problematic clients.

**Comment by mikedilger** [comment]
Thanks for letting me know.

Gossip has no origin. It is not a website-hosted application, it is a local executable. It would be inappropriate for me to list some domain name as an origin, or even to set Origin to null.

You are probably blocking more-speech and nostr-console too, which also don't have origins.

**Comment by mikedilger** [comment]
I could add an option for users to turn on a user-agent.

**Comment by fiatjaf** [comment]
Aren't you also blocking Damus, Amethyst, Nostros and Nozzle?

Normal programs can set their headers to anything, only webpages are restricted by the browser on some of their headers.

**Comment by mikedilger** [comment]
I'd suggest checking user-agent first, and if it is a known browser then do your logic.  If it is not a known browser you can perhaps see if you recognize the user-agent.  It will probably be missing.  I just added an option for gossip to send a user-agent to the relay, but it is off by default.

**Comment by davestgermain** [comment]
> Aren't you also blocking Damus, Amethyst, Nostros and Nozzle?
> 
> Normal programs can set any of their headers to anything they want, only webpages are restricted by the browser on some of their headers.

Damus sets the origin to the url of the relay. Other automated programs seem to set it to other arbitrary strings.

You're right that programs can set the header to anything. Filtering on the origin is mainly a way of blocking malicious or buggy web apps.

I'll just turn off the blacklist, since it's probably not doing anything meaningful.

**Comment by mikedilger** [comment]
Since I've added an optional user-agent, and IMHO that is all I should do, closing.
