### ISSUE TITLE
egui error

### ISSUE THREAD

**Issue by holdenbach** [mikedilger/gossip#170]
I'm getting this error when starting gossip. I'm unfamiliar with egui if anyone knows of an easy fix.  

ERROR egui_winit::clipboard: Cannot initialize smithay clipboard without a display handle!

**Comment by mikedilger** [comment]
This is a known error, we are all getting it.  It's harmless.  But it would still be good to sort it out, either here or within egui.

**Comment by mikedilger** [comment]
Doesn't happen in more recent builds. Closing.
