### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#172]
Right now we don't track if you have viewed a post.  We have a "Replies" feed which includes replies, mentions, eventually DMs, but there is no indication of messages waiting nor a way to flag a message as "read".

Most clients have this and we are way behind on this basic feature.

**Comment by pjv** [comment]
I think replies has now become inbox, right?

It would be excellent if there could be some kind of visual indication of new posts hitting the inbox. Maybe just something like a little red dot like this:

<img width="208" alt="SCR-20230606-npps" src="https://github.com/mikedilger/gossip/assets/327716/77267093-b261-480b-a737-ff6f6263ecf4">

I’m usually sitting with gossip on the main feed view and mostly forget to check if there is anything waiting in the Inbox.

**Comment by mikedilger** [comment]
I have finally gotten around to doing this.  We now have an inbox indicator with a count.  On unstable branch.
