### ISSUE TITLE
Prompt User before clearing text input

### ISSUE THREAD

**Issue by garyray-k** [mikedilger/gossip#178]
<img width="1123" alt="Screenshot 2023-01-29 at 1 16 28 PM" src="https://user-images.githubusercontent.com/39040273/215347406-8b89d9aa-7c6e-4a67-a139-dc62b1654cdc.png">

Just want to avoid a misclick

**Comment by mikedilger** [comment]
If we are going to confirm cancelling, we should definitely also confirm sending.  I'm thinking:

`Cancel` `Send` when you hit cancel becomes `Changed my mind` `Yes, Really` and the button widths remain fixed so you must move your mouse and click the other one to confirm.

`Cancel` `Send` when you instead hit send becomes `Yes Really`, `Changed my mind`
