### ISSUE TITLE
Talk to us about gossip

### ISSUE THREAD

**Issue by bitkarrot** [mikedilger/gossip#185]
Hey Mike, 

Fiatjaf wants you to join us on a future podcast at https://nostrovia.org and talk about Gossip. Since DMs were not working for you on Nostr, I thought I'd message you here. We'd love to have you do a deep dive and get into the details. Our podcast is developer focused.

Please do Let me know the best way to get in touch, for scheduling. 

All the best.

**Comment by mmochan** [comment]
@bitkarrot - Not sure what's going on with my Nostr DMs!!

That said whilst I'm a Rust and Nostr fan, I'm not sure I could offer much in the way of a deep dive, however, I would be keen to listen to the podcast

until I sort out my Nostr account you can get me at mike.mochan@gmail.com

**Comment by mikedilger** [comment]
Let's talk on telegram.
