### ISSUE TITLE
can't paste my key

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#186]
I get the error:

```
ERROR Cannot initialize smithay clipboard without a display handle!
ERROR Paste error: The clipboard contents were not available in the requested format or the clipboard is empty.
```

My clipboard is not empty...
On wayland Ubuntu 22.10

**Comment by mikedilger** [comment]
We all get the "smithay clipboard" error message and it doesn't affect our ability to paste.

Try CTRL-V instead of right-click or middle-click.

**Comment by jeremyd** [comment]
> We all get the "smithay clipboard" error message and it doesn't affect our ability to paste.
> 
> Try CTRL-V instead of right-click or middle-click.

I did try this, all the different ways to paste..  And I tried one more time just now to be sure.  None of them actually paste, and I click import too just in case the ui wasn't showing it.. no luck (middle mouse, CTRL-V, CTRL-SHIFT-V)

**Comment by jeremyd** [comment]
> We all get the "smithay clipboard" error message and it doesn't affect our ability to paste.
> 
> Try CTRL-V instead of right-click or middle-click.

OHHH, hm, yes I did have some copy/paste shenanigans.. I was using sway.  I logged out and logged in with gnome and then things worked.  Thanks!  Closing issue.

**Comment by mikedilger** [comment]
Perhaps Sway captures and inteprets CTRL-V.

**Comment by jeremyd** [comment]
> Perhaps Sway captures and interprets CTRL-V.

yes, it could also be user error.. i wasn't able to bisect before i logged out anyway due to other issues haha.  i will try again next setup.

**Comment by lilydjwg** [comment]
I get this too and type the whole string instead (using ydotool). Wlroots-based Wayland compositor doesn't allow X clipboard access when no X window is focused. GNOME does allow this. The right way is to use Wayland native clipboard.

**Comment by mikedilger** [comment]
This is an upstream issue. Gossip relies on eframe (from egui) to handle all this stuff.  If eframe is wrongly using an X clipboard on a pure Wayland desktop, that's probably an open issue over there somewhere.  But so is this "ERROR Cannot initialize smithay clipboard without a display handle!" probably an open issue over there.

**Comment by jeremyd** [comment]
I went hunting for additional info, it appears that smithay clipboard is supposed to work with wayland although i don't think it's had much testing.. The error we're getting is indicating it's not able to create the clipboard.

https://github.com/1Password/arboard/issues/52

https://github.com/emilk/egui/pull/1613

https://github.com/emilk/egui/commit/b8a5924295cce4d555c302fa000bd1bfd4d89575

**Comment by jeremyd** [comment]
@mikedilger I fixed the clipboard for wayland just by adding explicit dep for egui-winit.  I tried this because it seemed like the library just wasn't getting the default set of 'features'.  This is cool!  Maybe it will fix other clipboard related stuff for all the platforms (tested in linux/wayland/sway).
