### ISSUE TITLE
Use `p` relay hints for `e` tags

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#187]
I don't know if Gossip currently uses relay hints when trying to load a thread or the previously-referenced event in a reply sequence. Does it?

Anyway, assuming it does, my suggestion is that when an `e` tag is present but doesn't have a relay hint on it but a `p` tag is and does, to try to use that to fetch the previous event.

And vice-versa?

I don't know if that makes sense.

**Comment by mikedilger** [comment]
Makes sense. Good little hack. I'll try to look at this tonight.

**Comment by mikedilger** [comment]
on master.
