### ISSUE TITLE
Unable to run after installation on WSL2

### ISSUE THREAD

**Issue by icheyne** [mikedilger/gossip#192]
I have a clean PC and a new install of WSL, but was unable to run Gossip after install.

_./run.sh
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/gossip`
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoWaylandLib X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: winit::platform_impl::platform::EventLoop<T>::new
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9
   3: winit::event_loop::EventLoopBuilder<T>::build
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/event_loop.rs:111:25
   4: eframe::native::run::with_event_loop::{{closure}}::{{closure}}
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:95:36
   5: core::option::Option<T>::get_or_insert_with
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:1546:49
   6: eframe::native::run::with_event_loop::{{closure}}
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:94:26
   7: std::thread::local::LocalKey<T>::try_with
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/thread/local.rs:446:16
   8: std::thread::local::LocalKey<T>::with
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/thread/local.rs:422:9
   9: eframe::native::run::with_event_loop
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:89:5
  10: eframe::native::run::glow_integration::run_glow
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:845:13
  11: eframe::run_native
             at /home/iain/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/lib.rs:192:13
  12: gossip::ui::run
             at ./src/ui/mod.rs:50:5
  13: gossip::main
             at ./src/main.rs:69:21
  14: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace._

**Comment by mikedilger** [comment]
Maybe winit doesn't support WSL2.

This runs on windows outside of WSL2 though.  The trick being how to get it to compile on windows outside of WSL.  As I'm not a windows developer, I don't know myself.  I did it once, but I tried again later and discovered that I had forgotten how.

**Comment by icheyne** [comment]
Fair enough. Thanks anyway. :-)

**Comment by mikedilger** [comment]
Just checked winit repo, and based on issues posted it seems it does work on WSL2 as 'wayland'.

Did you run the github artifact binary, or did you compile?  If you ran the artifact, try compiling instead.  If you compiled, then it looks like a hard problem.

**Comment by icheyne** [comment]
I compiled it following the instructions in your readme. I'm not a developer, so I don't know how to get the github artifact binary.
