### ISSUE TITLE
View Thread not working so well as of f39d169

### ISSUE THREAD

**Issue by pjv** [mikedilger/gossip#196]
So yesterday, before f39d169, when I clicked the view thread button (or any linkified note pubkey) gossip would pretty reliably show me a lot of historical thread context and almost always let me keep clicking note pubkeys to follow the chain back in sequence to read a whole thread of replies to replies to … to original posts.

Today on f39d169 that’s not working anymore. Most of the replies that I click on take me to a blank “Thread” pane.

**Comment by mikedilger** [comment]
Ok I'll revert it for now and be more careful next time.  Thanks.

**Comment by pjv** [comment]
I don’t know if this is borked up relays (relay.damus.io seems to be throwing a 521 error at the moment) or something that changed in gossip (or a combination)), but I’m seeing a repeat of the same issue again in 9eb7221. Clicking on the parent link for many notes takes me to a blank thread pane. Log says `Done picking relays: Unable to make further progress.`

**Comment by mikedilger** [comment]
That particular commit couldn't have anything to do with this.  I've always had this issue.  Sometimes it is because the parent event isn't loaded and simply isn't returned from the relays we think it might be at.  But other times there is some indication that this event does exist locally (at least on disk) but not in memory. I thought I fixed this twice now, but I also have seen evidence of this perhaps continuing to be a problem.  I'll reopen this and continue to try to chase it down.

**Comment by pjv** [comment]
> That particular commit

Sorry for my unclarity. I didn’t mean that commit specifically, I was using that like a version number I am running. I don’t remember the exact commit I updated from to 9eb7221, but it was likely 327d923, so if there is something in gossip that changed affecting this and it’s not just some kind of relay transient thing, it would probably have been in the commits between those.

I definitely have been noticing this symptom here and there, but it seems worse to me as of the latest re-compile at 9eb7221 - but that could very easily be non-related to the commits between here and there.

**Comment by mikedilger** [comment]
I can't see anything between those commits that could have that effect. And my experience is that gossip is loading these threads about as well as it used to.

**Comment by mikedilger** [comment]
In the intervening 21 months or so a lot of code has changed so closing.
