### ISSUE TITLE
Can't run under wayland

### ISSUE THREAD

**Issue by honza** [mikedilger/gossip#204]
It compiles fine but I get this runtime error:

```
thread 'main' panicked at 'Failed to initialize any backend!
Wayland status: NoWaylandLib X11 status:
LibraryOpenError(OpenError {
  kind: Library,
  detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" }
)',
/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9
```

**Comment by mikedilger** [comment]
That is unfortunate.  The part that says "Wayland status: NoWaylandLib" leads me to believe it can't find your wayland.  Which OS distribution is this happening on?

**Comment by mikedilger** [comment]
Are you on NixOS?

Related:
https://github.com/emilk/egui/discussions/1587
https://github.com/danyspin97/wpaperd/issues/7

**Comment by honza** [comment]
> Are you on NixOS?

Yes.  The first link solves my issue, thanks.
