### ISSUE TITLE
dark-light mode issue on MacOS

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#215]
I got this report on telegram:

> @mikedilger just an FYI the "dark-light" feature of eframe prevents gossip from running in OSX 10.13.6. It's safe to assume that's also the case with older versions. the "dark-light" feature doesn't seem to do much.

> Some undefined symbols for x86_64 relating to the NSAppearance framework.

**Comment by pjv** [comment]
On macOS 12.6.2 dark and light works fine.

**Comment by mikedilger** [comment]
Thanks @pjv Did you not get errors about "NSAppearance framework?" like the other reporter? If not I'll just close this, especially if Jack Chakany manages to package it for macos.

**Comment by pjv** [comment]
I did not see any such errors, but I am running an older version of macOS than the original reporter.

BTW, I did experiment this morning with using [cargo-bundle](https://github.com/burtonageo/cargo-bundle) to build a stand-alone macOS app bundle of gossip and it worked well.

**Comment by mikedilger** [comment]
Yes I think the original poster is on Apple silicon.

**Comment by bu5hm4nn** [comment]
> Dark mode was first introduced in 2018 as part of macOS Mojave (10.14) and quickly became a popular feature with Mac users.

He needs to update macOS to 10.14

**Comment by InnocuousFinch** [comment]
> Yes I think the original poster is on Apple silicon.

I'm running Gossip in dark mode on macOS 13.2.1 with M1 Pro and it's working fine.

**Comment by mikedilger** [comment]
Ok let's close this then.  If people are on an OS from <2018 I'm not going out of my way to support those.
