### ISSUE TITLE
read/write relays not updated

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#216]
I notice that when I move to another machine, it picks up my kind-10002 and it marks my person record relay_list_created_at as having processed that one as the latest one... but my relays are not checked according to what that kind-10002 event says.

I also tried forcing my person record relay_list_created_at timestamp back to 0, and it then reprocesses it and works.  But why didn't it work when I first fired it up this morning after 3 days.

Mysterious.

**Comment by cryptoquick** [comment]
I'm not sure if this is related, but I just installed the very latest from master, 74aefab0180ca81626f714085a9a61267018e32c, and Gossip didn't pick up my relays. I have nearly a hundred, so maybe it's just taking a while? Not sure. My npub is: `npub1qqqqqqqrxtrcx8vut2vlrqa0c2qn5mmf59hdmflkls8dsyg9vmnqsclxwk`

**Comment by mikedilger** [comment]
The problem might be related to kind-3 contact list relay lists.  Both forms of relay list are treated similarly.  So if your ContactList is newer than your kind-10002 relay list, gossip will consider it as the newest relay list even though gossip never updates that nonstandard one.

Clearly a problem. The solution isn't clear though.

**Comment by mikedilger** [comment]
I think I should just drop the whole kind-3-contents processing thing.  I'll keep it preserved for those other clients, but gossip shouldn't use it -- the meaning of 'read' and 'write' isn't the same in kind-10002 anyways.

BTW: I think having "nearly a hundred" relays is verging on a DDoS attack.

**Comment by mikedilger** [comment]
Eh, I just looked at the code and we don't process our own contact list contents. So I was off base.  I remembered things wrong.

**Comment by cryptoquick** [comment]
> Eh, I just looked at the code and we don't process our own contact list contents. So I was off base. I remembered things wrong.

If that's the case, what's the solution?

> BTW: I think having "nearly a hundred" relays is verging on a DoS attack.

It's not so bad if the load is spread over different hosts, though? Also, Gossip does its own form of relay optimizations, right? If any client could handle a hundred relays, it'd be this one?

**Comment by mikedilger** [comment]
Well if you are writing to 100 relays, it has to connect to 100 relays to write to them all, and that still puts 100x the load on the entire network than would be there if you only wrote to 1 relay (which I'm not suggesting, 1 is too small).  And the nostr network is rather heavily loaded because lots of clients are thinking this same way (no single client is smashing any single relay, so the relays don't see any client as overusing them, but overall,. collectively, that is what is happening), and it all adds up to crushing the relays.  If you are reading from 100 relays, it has to connect to all 100 to pick up any events addressed to you and there's nothing smart it can do in that regard.

**Comment by mikedilger** [comment]
> If that's the case, what's the solution?

I don't know because I don't know what the bug is. And I'm not even sure we've characterized the misbehavior correctly yet.

**Comment by cryptoquick** [comment]
You make good points... I'd remove some relays, but I'm not sure of a good way to tell how many users I'd lose contact with. In addition, I like things like [filter.nostr.wine](https://filter.nostr.wine), and it probably overlaps with some of my relays. What would you recommend I do?

**Comment by mikedilger** [comment]
Well, gossip will find who you follow and get their events without you needing lots of relays.  But to be heard, you still might need to still write to a lot of relays, because those other clients won't.  At least for now.

I don't know if I'm missing a lot, but it doesn't feel like I am.  I'm usually connected to about 10 relays, several are not ones that I configured (like damus or snort.social) but ones that people I follow profess to post to.

There's no right answer, especially right now.

**Comment by mikedilger** [comment]
I'm going to close this, I think it works now.
