### ISSUE TITLE
Major Feature Set:  SEARCH

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#219]
Top level menu 'Search' with a single page

- ~~Search for Note by id --> gives as a thread~~
- ~~Search for Person by pubkey --> gives the person page~~
- ~~Search for Person by name or metadata content --> gives the person page~~
- ~~Search Local notes for Substring --> gives a LIST of links to posts~~
- ~~Search Local for Hashtag --> gives a LIST of links to posts~~
- Search Relay notes for Substring --> gives a feed [This will be a separate issue]

- [x] Move lens icon to the right, make into a button
- [x] Focus the input when the page is entered

**Comment by cryptoquick** [comment]
It might help to have a scoped Person search to the People page, I think, but if that's too complex, maybe a button on that page could take you to the Search page.

**Comment by mikedilger** [comment]
This is done on unstable.

Searching at a relay will be a separate issue.
