### ISSUE TITLE
simple tags would be better?

### ISSUE THREAD

**Issue by soloturn** [mikedilger/gossip#231]
for the tags i guess it would be simpler to just have standard tags, and not an additional one called "..unstable", while the 0.4.0 is not even reachable via history from master?
```
from the arch PKGBUILD file in gossip-git the version is calculated so:

❯ git -C gossip-git/  describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/^v//'
0.3.91.r13.g1cda929

❯ git -C gossip-git lg1 -30
* 1cda929 - (15 hours ago) v0.4.90-unstable, to indicate that this branch is the precursor to 0.5.0 - Mike Dilger (HEAD -> master)
| * a52888b - (15 hours ago) v0.4.0 - Mike Dilger (tag: v0.4.0, v0.4)
|/  
* 653d3ba - (14 hours ago) update make-tar.sh to use the current VERSION from Cargo.toml - Mike Dilger
* 3ce38ed - (19 hours ago) Track how many bytes are read and display on stats page - Mike Dilger

```

**Comment by soloturn** [comment]
this will auto-fix with the next release :)

**Comment by soloturn** [comment]
it did not fix itself with next release. 0.4.2 tag not reachable from master. can we merge it? 

```
❯ git -C gossip-git/ lg1 -40
* 02d8135 - (10 hours ago) Add a silly 'Origin' header for a few relays that won't talk without it - Mike Dilger (HEAD -> master)
* 74aefab - (13 hours ago) Updated notes on windows packaging - Mike Dilger
...
*   9bed167 - (20 hours ago) Merge pull request #244 from 0xbabo/patch-build-releases - Michael Dilger
|\  
| * e5b6960 - (21 hours ago) Build release branches - 1babo
|/  
* 3c4fde2 - (2 days ago) When viewing a thread, pull relevant events from local database - Mike Dilger
...
* 58249e6 - (5 days ago) Improve scrolling in the presence of lots of reposts (not perfect, but better) - Mike Dilger
* 1922a0c - (5 days ago) New event tracking is now ID based, and turned off if your mouse-pointer hovers over it - Mike Dilger
* 1cda929 - (6 days ago) v0.4.90-unstable, to indicate that this branch is the precursor to 0.5.0 - Mike Dilger
| * bf0d50c - (13 hours ago) Updated notes on windows packaging - Mike Dilger (v0.4)
| * f52c767 - (14 hours ago) 0.4.3-unstable - Mike Dilger
| * 1a37e03 - (14 hours ago) 0.4.2 - Mike Dilger (tag: v0.4.2)
| * 6109ebb - (15 hours ago) bugfix in nip-05 (reqwest.get() already adds one Host header) - Mike Dilger

```

**Comment by soloturn** [comment]
if we would be able to merge 0.4 into master, all would be good:
```
/repos/gossip-git/src/gossip-git on  makepkg is 📦 v0.4.90-unstable via 🦀 v1.67.1 
❯ git merge origin/v0.4
...
❯ git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/^v//'
0.4.2.r36.g90bb4a8

```

**Comment by mikedilger** [comment]
Version 0.4 is a proper fork from master.  When a bug is fixed on master, it gets cherry-picked over to v0.4.  Sometimes it is necessary to do some ugly custom rearrangement on v0.4 in order to bring over a bugfix without also bringing over a risky new feature.  And such ugly custom rearrangement cannot be merged into master.

The user impression of a numerically-increasing set of versions along a single line is just a fiction. Real code often cannot work like that.

**Comment by soloturn** [comment]
that is fair enough, in that case we could do a
```
src/gossip on  master [⇡] is 📦 v0.4.90-unstable via 🦀 v1.67.1
❯ git merge -s ours origin/v0.4
```
and you continue to do whatever you describe.

**Comment by mikedilger** [comment]
I never understood what this issue was about. And I don't understand the emojis.  I don't know what "is 📦" signifies.

**Comment by soloturn** [comment]
https://aur.archlinux.org/packages/gossip-git shows as version 0.3.91.r215.gab25e37. would love it is 0.4.2.r36.g90bb4a8, x commits newer than  release 0.4.2. and i would love to keep gossip-git aur package pointing to master and not something else. (forget about the icons this is just starship prompts default: https://starship.rs/).

https://git-scm.com/docs/git-describe

**Comment by mikedilger** [comment]
`git describe` isn't a good way to get the current version off of master because the git tags are unreliable and they only show you the last tag, but master doesn't tag commits that aren't actual releases (as you have noticed).

You might try something like this:
````
VERSION=$(cat Cargo.toml | grep ^version | awk -F= '{print $2}' | awk -F\" '{print $2}')
````

**Comment by soloturn** [comment]
this gives a name:
```
❯ cat Cargo.toml | grep ^version | awk -F= '{print $2}' | awk -F\" '{print $2}'
0.6.0-unstable
```
which does not let the version number grow automatically with new commits coming in?

**Comment by mikedilger** [comment]
Concatenate the beginning of the commit hash

````
VERSION=$(cat Cargo.toml | grep ^version | awk -F= '{print $2}' | awk -F\" '{print $2}')-$(git rev-parse --short HEAD)
````

**Comment by soloturn** [comment]
@mikedilger ithanks for the hint, used it like:
```
echo $(cat Cargo.toml | grep ^version | awk -F= '{print $2}' | awk -F\" '{print $2}' | awk -F- '{print $1}').$(git describe --long --tags | awk -F- '{print "r"$2"." $3}')

0.6.0.r389.g6321c6f
```
in arch linux, gossip would be a stable packe, gossip-git is the one from head of git. so no "unsecure" necessary.
