### ISSUE TITLE
scroll jump problems

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#233]
Especially with big notes going in/out of view, scrolling sometimes jumps so far that there are notes that you can't even get to.

**Comment by mikedilger** [comment]
largely fixed (not perfectly)

**Comment by pjv** [comment]
fwiw, i am still seeing pretty much the same scrolley jumpiness in e97f62a as i did on whatever commit i was running yesterday.

**Comment by mikedilger** [comment]
A little scrolley jumpiness is hard to avoid (we have to estimate the height of posts we don't render, and it's hard to estimate that perfectly), but what I fixed was jumpiness of several screens at a time due to the oversight of not estimating the height of repost contents.  If you are getting jumpiness that is so bad you can't get to some posts, then I'll reopen this and try to figure out what else I forgot about.

**Comment by pjv** [comment]
it’s nothing like full screens - more like jumping up or down an inch or so. It’s usually just enough that my eye loses what i was looking at and i have to consciously search for where i was.

i know almost zero about egui so this is a pretty naive question: does the “immediate” aspect of egui force it to know something about the content (i.e. height of posts) of what it’s scrolling rather than just scrolling at the pixel level?

**Comment by mikedilger** [comment]
We don't actually render the entire feed.  If we did, we would have to do it again every frame, and that would make gossip very slow and unresponsive.  We only render the posts that are visible on the screen.  But the egui ScrollArea widget presumes you have a large amount of rendered content that it is scrolling through.  So we have to lie to that widget by creating empty content above and below the visible window so that it can draw a scrollbar that is close to accurate.  When that empty content gets partly replaced with an actual post, the height of that actual post might not match what we estimated, in which case the Y position of the content at the top of the window is suddenly off by some number of pixels.  The more accurate we are at estimating the height a post would be had we actually rendered it, the smoother scrolling will become.

Maybe there is a smarter way to do it. But this was the hack that worked "good enough" for early versions of gossip without me having to code a different smarter ScrollArea widget.

**Comment by mikedilger** [comment]
Ok I've pushed a couple changes that have fixed this.  Scrolling is now accurate because I'm now actually rendering every post if never rendered before, and remembering the height.  Then in subsequent frames if the post is off-screen it just adds empty space to fill in the exact height that was remembered.

There is a small sacrifice in that there is a pause before any feed loads.

**Comment by pjv** [comment]
Wow - much, much better to me. Thanks!
