### ISSUE TITLE
retry failed posts?

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#235]
If you post a message and it fails on a relay, that might show up in the logs but there is no record nor any attempt to retry.  Not sure how to handle this.

**Comment by cryptoquick** [comment]
One thing I worry about is that when I join new relays, my old messages are unbroadcasted there. I was thinking, maybe there could be a way to periodically "sync" all your messages to your relays, maybe rate-limited over time, keeping track locally of which messages have been known to have been broadcasted to relays already.

**Comment by cryptoquick** [comment]
The solution for this might tie into #207

**Comment by mikedilger** [comment]
Well, I suppose step 1 would be to, once the message is written to the relay successfully (as far as we can tell) add a record in event_seen as if the event was seen delivered by that relay.  Then event_seen is really just tracking what relays we believe hold the event.

Then we can go from there.
