### ISSUE TITLE
Feature Request: Mute threads and filter inbox view

### ISSUE THREAD

**Issue by pgerstbach** [mikedilger/gossip#239]
## Problem Description / Rationale

Threads with many mentions that go viral can congest the "Inbox" view very quickly.

For example I was mentioned in a thread with 40 other npubs. The thread went viral and was reposted dozens of times. That resulted in "Inbox" spam: For days my Inbox only contains those reposts and other conversation gets unnoticed.

## Possible solution
It would be nice to allow muting specific threads, maybe together with a time-span how long:
Mute for 1h, 2h, 4h, 8h, 24h, 1week, forever

## Alternative solution
Don't mute threads but allow to filter what is shown in Inbox or add more views:
* Don't show reposts
* Show only direct answers to own posts

Thanks!

**Comment by mikedilger** [comment]
For the moment, there is a setting "Enable Reposts" that you can turn off.  I get the same kind of spam reposts.

I'll leave this open for a thread-mute option.

**Comment by pgerstbach** [comment]
Oh great, I was not aware of this setting. This solves 90% of the issue, thanks!

**Comment by dtonon** [comment]
@pgerstbach some days ago the inbox has been divided: one part shows only the direct replies and mentions, the other all the posts where the user is tagged (the hell threads you are referring to). Checking the first one should be a relief :)

**Comment by pgerstbach** [comment]
Yes, the new filters are great! Thanks!
And it seem gossip filtered out the latest hell-thread with >1000 mentions. Glad to see a clean notification view!
