### ISSUE TITLE
Automated builds not run for release tag/branch

### ISSUE THREAD

**Issue by 0xbabo** [mikedilger/gossip#240]
Automated builds (https://github.com/mikedilger/gossip/pull/162) are only running for commits on master branch, but releases are pushed on forks for some reason. 

Proposed solutions:
- Don't fork releases.
- Dedicated branch for releases, to be added to the github action.

**Comment by mikedilger** [comment]
Every release gets a fork.  If we need to patch a bug in a release, it goes onto that release branch.  v0.4 has a few patches, but not all of master.  Master gets lots of other stuff that should not go onto that release branch.  So given this, I don't understand how anybody could **not** fork releases, nor to put them all on the same dedicated branch.

I think automated builds for master is sufficient.  People should probably be running off of master, unless they can't be bothered to compile and require a package.  That's what releases are for.

0.4.1 will be released soon, I was going to do it today but I corrupted my server and had to rebuild it instead.

**Comment by 0xbabo** [comment]
I haven't used them much but I was looking at the PR earlier and it seems like it requires specifying the branches to build on, hence the second proposal :)

Anyway, I think it might make more sense for now as a homebrew formula (rather than cask) which won't require published binaries.

**Comment by 0xbabo** [comment]
I've made a homebrew formula for gossip here: https://github.com/0xbabo/homebrew-nostr/blob/main/Formula/gossip.rb

I will submit a PR for building release branches shortly.
