### ISSUE TITLE
When closing on Linux via Sig-Term, app does not start anymore

### ISSUE THREAD

**Issue by MartinKei** [mikedilger/gossip#245]
I'm running on Fedora 36 and build the app on my machine.

I setup my account, added some relays and started to follow user `mike@mikedilger.com`

In the command line I hit `CTRL + C` and stopped the app to restart it via `./gossip`

This leads me to not being able to start the app anymore:

```
[zombie@localhost gossip]$ ./gossip 
Error: Sql(QueryReturnedNoRows)
```

Most recent commit of my build:
3c4fde2aee6283d170577433cded528a315c21ae

**Comment by mikedilger** [comment]
I don't think the CTRL-C caused any damage.

Maybe I broke something in 3fe4c8b620500cba2277b179d2150872a82ea8e9
It was a tricky change and there might be a case that I didn't account for properly.

Can you run sqlite3 on your database (~/.local/share/gossip/gossip.sqlite) and see if it has a `local_settings` table with one row in it (`SELECT * FROM local_settings`)

**Comment by vbacode** [comment]
> 

Same problem here after installing on arch in virtualbox.  The table 'local_settings' is there, but there is no record, just empty table.  I built from source downloaded and build about an hour ago, and put some relays in.  The app was not responding so I closed it thinking if I re-opened it would clean it up.

**Comment by mikedilger** [comment]
Ah I see the problem. Working on a fix.

**Comment by mikedilger** [comment]
Pull and try again from scratch after deleting the ~/.local/share/gossip/gossip.sqlite file.

For clients that didn't get stuck, they don't need to reapply this schema.  But for fresh installs that are stuck, they have to be reinstalled (or you could manually create the row in the local_settings table).

**Comment by vbacode** [comment]
This fixed the issue, new build working now.  Thanks!
