### ISSUE TITLE
Can't see exported private key on windows because console is explicitly hidden

### ISSUE THREAD

**Issue by CalebFenton** [mikedilger/gossip#248]
Great project. Thanks for all your effort.

Looks like the console is explicitly hidden on windows and that's where the private key is exported. https://github.com/mikedilger/gossip/blob/a94a601c40c219f44e05976ec6b14062d411f5aa/src/main.rs#L1

Any work around? Maybe I'm doing something dumb.

**Comment by mikedilger** [comment]
I'm the one doing something dumb.  I should have set that to "console".

Damn, I was trying to get the console to show by default about a week ago and couldn't figure it out.  It is right there in line 1 !!!

The workaround:  you can start gossip from a powershell or a cmd shell and you'll see the output.

**Comment by CalebFenton** [comment]
I had the same idea about running it from the console. I tried cmd, using `start` from cmd, using `&.\gossip.exe` from powershell, etc. and they all just open the window with no console output.

Insanely fast resolution. Thanks again for the free shit!

**Comment by babonyx** [comment]
If I want to run on Windows without the console, how would I go about doing that? Thanks

**Comment by mikedilger** [comment]
Sorry, there is no option to do that.
