### ISSUE TITLE
ws:// support?

### ISSUE THREAD

**Issue by JimSB** [mikedilger/gossip#250]
Hi support from the Umbrel team here, does gossip have ws:// support? 
If not, can it?  :slightly_smiling_face::flamingo:(I understand this is a flamingo, but there is no ostrich emote so we make do)

**Comment by mikedilger** [comment]
I'm not sure I can respond to a flamingo.  I think I'm gonna need an ostrich. 𓅦

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⠿⠶⠖⠂⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣇⠀⠀⠀⠀⠀
⠀⠀⠀⢠⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣦⠀⠀⠀⠀
⠀⠀⠀⠈⣵⣾⣿⣿⣿⣿⠆⠀⣀⣠⣤⣤⣤⣤⣤⣤⣀⡀⠀⣠⣾⣿⠀⠀⠀⠀
⠀⠀⠀⠸⠟⠁⠈⠻⠟⢁⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡈⢻⣿⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⣻⣧⠈⠃⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠻⠿⠿⠿⠿⠟⠛⠋⣁⣤⣾⣿⡟⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣦⣀⠐⠶⣶⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⡿⠿⠟⠃⢢⣤⣈⡉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢠⣶⡿⠋⠉⠀⠀⠀⠀⠀⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⢀⠀⠀⠀⣰⣿⠏⠀⠀⠀⠀⠀⠀⠀⠰⣿⣿⣶⣤⣤⣀⣀⡀⠀⠀⠀⠀⠀⠀
⠀⠘⠻⠷⠾⠿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣄⡀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠀⠀⠀⠀

**Comment by mikedilger** [comment]
My intent is that ws:// is supposed to be supported. I explicitly used a library call that does not require TLS, but does TLS if it is there.  It's called `MaybeTlsStream`.  I haven't actually tested this though.

**Comment by rgleavenworth** [comment]
Doesn't work for me. I tried using gossip with my local nostr relay over umbrel and it can't connect to it. My amethyst client on android works just fine with the relay, so looks to be a Gossip specific issue.

**Comment by mikedilger** [comment]
Well then use Amethyst. Or fix it and issue a PR. I don't have time to figure this out.

**Comment by mikedilger** [comment]
This will be easiest to debug using one of the tools from nostr-types such as pull_event which is inly 105 lines long, since you can force it to a particular relay, unlike gossip.  Then when the fix is discovered, gossip can be patched.

**Comment by mikedilger** [comment]
````
[mike@brindylln nostr-types]$ ./target/debug/pull_event ws://64.44.60.124:7777 df585cf412854a1077be45369b9f2ae88d83db541718196e001cead65a02d3de
{"id":"df585cf412854a1077be45369b9f2ae88d83db541718196e001cead65a02d3de","pubkey":"82341f882b6eabcd2ba7f1ef90aad961cf074af15b9ef44a09f9d2a8fbfbe6a2","created_at":1677597725,"kind":1,"tags":[["e","47745b135fba2b1d4f1ce8857c53b8280d852ce2fc7dee410b09408d455826b7"],["p","e8ed3798c6ffebffa08501ac39e271662bfd160f688f94c45d692d8767dd345a"]],"content":"Many reasons for that…\n\n🧵1/73","sig":"130ecc2224c10a0c57d45952c057d0ce11956f567f6c9ba6d710b57b6b1ec6af8ad41210671c705fbf71ff8073824f3244591ea78b4290f09c9bb788bc3cca58"}
Closing
````

This seems to work in nostr-types.  If you can explain the nature of the error condition better it would help.  Do you see any errors in the logs that are output on the console?
