### ISSUE TITLE
Show your followers

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#252]
This is expensive data to collect, but other clients have at least a count of how many people follow you.

We should have a button (NOT do it automatically) where a user can request this process to occur, maybe just once per session (if they click over and over they will just cause mayhem, they should just wait for the results which might take minutes).

We can cache this data too. But that cache doesn't help us ask the relays for only the ContactLists we are missing.. we have to get them all again.

**Comment by jadijadi** [comment]
related to #111

**Comment by mikedilger** [comment]
We load this data now to compute friends-of-friends.  So this (and #111) should be easier to do now.

**Comment by mikedilger** [comment]
Since we only load your followED's contact lists, we cant count your followERS.  This will have to wait for HyperLogLog on the relays.  (yes we could do it now with an expensive operation but I don't think it's good. You can get it from other clients).

**Comment by mikedilger** [comment]
I did this anyways.
