### ISSUE TITLE
MacOS M1 version would make der0pa very very Happy! :)

### ISSUE THREAD

**Issue by der0pa** [mikedilger/gossip#258]
nostr community could really use another native client for MacOS other than damus.    your methodology on reading from where folks write makes more sense to me.    Nice work ... 
I tried installing gossip on  Arch Linux VM on my mac but was unsuccessful.  A docker image would help also work for MacOS.     

How long have you lived in NZ ?     ... sounds pretty sweet! 

Cheers

**Comment by mikedilger** [comment]
Did you try compiling it from the git repo? That's the most reliable and up to date way to get it running anywhere.

18 years.

**Comment by der0pa** [comment]
tried from source first but many many errors.
i wont burden you with.

**Comment by mikedilger** [comment]
It might be that linux on M1 hardware is not yet supported by the libraries I'm using.  I think MacOS on M1 hardware does work (I think, I cannot verify).

**Comment by mikedilger** [comment]
Version 0.6 has  just been released for Darwin arm64
