### ISSUE TITLE
Relay list - delete

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#264]
This came up before (I can't find the issue) but we should allow people to mark a relay as deleted.  This would set the rank=0 and hide it from the list.  We shouldn't actually delete because we want it to stay gone even if it comes back via an event.

**Comment by bokybanton** [comment]
Try to add a relay and mistype it...Now I can not delete it.. Any typs?  I think feature will be useful. Thank you @mikedilger

**Comment by mikedilger** [comment]
this was done long ago now.
