### ISSUE TITLE
Websocket space limit exceeded

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#269]
From time to time I start to get errors like this in the logs, I'm unsure yet what is causing this.. Is it gossip is trying to send a websocket message that is too large?

ERROR wss://relay.snort.social: Websocket: Space limit exceeded: Message too long: 181475 > 131072

**Comment by mikedilger** [comment]
This is when gossip receives a message that is too large.  The length is declared before the message is sent, and gossip rejects messages greater than 131072 bytes.  We could have picked any size limit, and I chose this based on the largest existing events I had seen, and then went something like 4x that.  Maybe it has become too small.  But I would be interested to know what the event is about -- a long diatribe, a long bit of spam, multimedia content, a huge contact list -- I'm curious what it was.

Of course we can allow very long messages, but at some point someone could DoS your system by flooding it with massive messages.

Maybe we can make this a setting.

**Comment by mikedilger** [comment]
See src/overlord/minion/mod.rs line 180.  It's probably too small.

**Comment by jeremyd** [comment]
Interesting, thanks!  I was seeing it a lot about a week ago, then it went away for a while and I thought it was fixed somehow.  Good to know, I'll play around with the setting a bit and also see if I can determine what type of message is hitting the limit..

**Comment by jeremyd** [comment]
fixed in https://github.com/mikedilger/gossip/commit/7851460b64dc9485696b44dc4092794642b3d973
