### ISSUE TITLE
Major CPU load issue

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#270]
At some point today all my cores were maxed out and they wouldn't come down until the client was killed.

**Comment by mikedilger** [comment]
This isn't so bad. I usually run in debug mode, and in debug mode things have been running rather hot. But in a release build the CPU barely moves.

**Comment by dtonon** [comment]
Happened also to me in debug mode, I related the matter to the post of a message using POW (25), but I wasn't able to reproduce. However the CPU peak usage under POW was similar.

**Comment by mikedilger** [comment]
Well, posts with POW are expected to use all of your CPU for a while.  I filed this because I was getting high CPU usage while not doing much at all (slow scrolling and mouse movement).

I ran perf and flamegraph to try to find the problems but they didn't show up.  Then I realized flamegraph compiles in release mode, which made me realize I was using a debug mode binary, which made me decide this issue was no big deal anyways.
