### ISSUE TITLE
Problems with Soapbox Bridge

### ISSUE THREAD

**Issue by vsatmydynipnet** [mikedilger/gossip#272]
Compiled Gossip on Debian Sid, running in Firejail using "torsocks gossip" to route all through Tor.

Works basically fine.

I am using Soapbox to Bridge to Mastodon:

https://gitlab.com/soapbox-pub/mostr

But when trying to follow my mastodon user using:

me_at_mymastodon.server.com@mostr.pub

Gossip logs:

ERROR SerdeJson Error: expected value at line 1 column 1

But the Relay of the Mastodon Bridge is connected. There is a 33% success rate to connect to the relay, but its works.

**Comment by mikedilger** [comment]
Interesting.

That's not going to be easy to find. Probably something is being converted from JSON into a rust type, but it is empty/missing even though it is required.

**Comment by vsatmydynipnet** [comment]
I know. I created the account with another client. The ones already followed over the bridge looks like are working. But following new new ones runs into this error. Bridge as Relay works as it looks like.

**Comment by mikedilger** [comment]
I wouldn't worry about the serde error. Gossip recovers from things like that. Might just be a nostr.json file with no contents or a 404 response for that matter.
