### ISSUE TITLE
nostr.mikedilger.com

### ISSUE THREAD

**Issue by pjv** [mikedilger/gossip#274]
@mikedilger gossip repeatedly logging this:

<img width="672" alt="SCR-20230302-kotb" src="https://user-images.githubusercontent.com/327716/222509106-d80d3b75-fa41-4511-9a94-95abf2cbf6ee.png">

…just checking if you are aware.

**Comment by mikedilger** [comment]
I wasn't aware.  If it's not one thing it's another.
