### ISSUE TITLE
Does this client surpport  unicode/chinese/utf-8?

### ISSUE THREAD

**Issue by cxdpg** [mikedilger/gossip#293]
It looks wrong when display chinese.please see the attached screenshot.
![20230308224516](https://user-images.githubusercontent.com/10525178/223744456-dc24a329-d560-4569-87ff-106406643e55.png)

**Comment by mikedilger** [comment]
If you compile with --features="lang-cjk" then you will see the glyphs you desire.

When I do the next release I will have a CJK version.
