### ISSUE TITLE
Don't process a note if it is part of a url

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#304]
If a url contains a note this is processed and the url became corrupted.
Example: note19qw8hvsll5vwj5asvkx55t2ry0wurspe4cshqns6dnh8ul37yvmqjgssx7

<img width="583" alt="image" src="https://user-images.githubusercontent.com/89577423/224519162-5989ab65-4bb2-4b62-b30a-fbabdad90186.png">

Url should remain untouched.
Perhaps is good to detect the event and add it as e-tag.

**Comment by mikedilger** [comment]
This specific error isn't a problem anymore. But there are similar ones, any of these may still be open: #348 #400 #414
