### ISSUE TITLE
adding language fonts / fixing display of languages

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#311]
I made an attempt to figure out why gossip isn't displaying Japanese text.  It displays blank squares (see image).  I tried adding some ttf fonts, and I was also looking at the emojis and wondering if those emoji overrides blank out the other languages.  I wasn't able to get it to display..  Gossip can still copy and paste the text though with the correct content (ie. if you are pasting it to a translator) so I think it's just a display issue.

![image](https://user-images.githubusercontent.com/4072/224851405-b727df4f-793b-4450-8e52-a0bca4113387.png)

**Comment by jeremyd** [comment]
https://github.com/jeremyd/gossip/tree/japanese_fonts  Here is a branch, where I attempted to add fonts.. it's out of date though from style changes (but has the fonts I was attempting)

**Comment by mikedilger** [comment]
Compile with "cargo build --release --feature=lang-cjk"

**Comment by mikedilger** [comment]
The reason they are not included by default is that they more than double the size of the binary, which includes it's memory allocation when running.

**Comment by jeremyd** [comment]
Oh cool!!!  Thanks that works great!  Is there a list of all languages?

**Comment by mikedilger** [comment]
So far nobody has asked for any other languages. I'm using the "Noto" fonts, and they are split into separate files for each language, and since they use different metrics and such they don't combine properly.  So that means I have to dump a hundred files or so and add features to turn on subsets of that.  That's the plan, but I didn't want to bother until someone asked for a specific language.  If I just go ahead and add "MeeteiMayek" or "SyriacEastern" I bet it makes no difference.

**Comment by jeremyd** [comment]
> So far nobody has asked for any other languages. I'm using the "Noto" fonts, and they are split into separate files for each language, and since they use different metrics and such they don't combine properly. So that means I have to dump a hundred files or so and add features to turn on subsets of that. That's the plan, but I didn't want to bother until someone asked for a specific language. If I just go ahead and add "MeeteiMayek" or "SyriacEastern" I bet it makes no difference.

ya, haha, sorry I'm a font noob, I'm stoked to have japanese and that's all i cared about.  i fully realize the pain of internationalization but just wanted to make sure we got the content covered.  :)  plenty of other stuff to do and i am enjoying the new emojis too.
