### ISSUE TITLE
How to clean reset client ? 

### ISSUE THREAD

**Issue by ttpro1995** [mikedilger/gossip#313]
I mess up.
Can't decrypt private key with password. 
How to clean reset the app ?

**Comment by ttpro1995** [comment]
I stuck here. 
Can't set new key or delete old key 

![](https://i.imgur.com/KL9XNP9.png)

**Comment by mikedilger** [comment]
The "Delete this Identity" didn't work?

If you want a clean reset, go to 'Help > About' and look for where it shows you where the database is located.  Delete that file and you will have a clean start.

**Comment by ttpro1995** [comment]
> The "Delete this Identity" didn't work?
> 
> If you want a clean reset, go to 'Help > About' and look for where it shows you where the database is located. Delete that file and you will have a clean start.

this work. 
However, sometime it lock my key again, I am keep using this method once a while.
