### ISSUE TITLE
Feature Request: Ability to select text from posts

### ISSUE THREAD

**Issue by InnocuousFinch** [mikedilger/gossip#314]
As a user of Gossip, I want to be able to select text from posts so that I can copy the selected text and paste it into whatever other application I want it to go in. 

Example: user posts a bitcoin address for donations that I want to send some sats to. I'd like to be able to copy the address and paste it into the wallet of my choice.

**Comment by mikedilger** [comment]
There is a copy icon (two overlapping squares) below the post.  The best we have right now.  I cut-n-paste into a text editor, and then cut further as necessary.  I know it's a pain, but it is better than nothing.

I will leave the issue open so we can do better.

**Comment by badonyx** [comment]
This would be extremely helpful for platforms that allow additional actions based on text selection, like dictionary lookup or translation on macOS.

<img width="1211" alt="Screenshot 2023-10-05" src="https://github.com/mikedilger/gossip/assets/110633279/282669cf-b6da-4f20-879a-147a663d2728">

**Comment by acarlton** [comment]
This post suggests text_edit_multiline works in some cases:

https://github.com/emilk/egui/discussions/353

**Comment by mikedilger** [comment]
Turning every label into a text edit is a very ugly expensive solution that I'm trying to avoid.  egui needs to do better.  The fix for this should be at the egui layer.

**Comment by mikedilger** [comment]
I'm going to close this under the presumption that unstable will be merged. The egui update is becoming quite stable.
