### ISSUE TITLE
Mention not linked

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#319]
The following note include in the last part a mention that was not linked:
note1veahk446slqmafmrk0x6fgmrwmu4kk5mwrr3y2fy3x8tr3czkdaqrm5vns

<img width="746" alt="image" src="https://user-images.githubusercontent.com/89577423/226679550-f1e62981-df2a-4e26-8ff5-8c69539bb762.png">

**Comment by bu5hm4nn** [comment]
@dtonon I cannot find the note in my relays. Is this resolved? NIP-27 specifies that the link has to start with nostr: so maybe it will not work still.

**Comment by dtonon** [comment]
On unstable is ok:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/89577423/232435593-6c491bfb-8096-436b-bd38-ebf85489f533.png">

> NIP-27 specifies that the link has to start with nostr: so maybe it will not work still.

I suppose we need to keep the retro compatibility to manage all the old notes, right?

PS: Note the glitch of the "seen on" popup showing in the wrong place.

**Comment by dtonon** [comment]
The problem is back but I suppose we don't care because NIP-27 is now everywhere.
I close the issue.
