### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#321]
embed lua scripting language, tie it back to an ability to filter content with user-generated scripts

**Comment by namoscagnm** [comment]
Very nice comment!

As a user I will have many ideas that require a code change, and it would take a lots of energy from everybody if I alway have to ask someone to implement it.

If there are user scripts (with lua, javascript or whatever makes sense), with reasonable API, I could do the changes myself, like im vim.

Then I could show the conversations as trees and other types of visualization as I need, filter messages ad I need and etc.

In an extreme case, I could also share my scripts with other people and vice versa, like we have with vim plugins!

**Comment by mikedilger** [comment]
This was done, but with rhai language (because it integrated smoothly).
