### ISSUE TITLE
Improper NIP-05 domain verification for just the domain name

### ISSUE THREAD

**Issue by pwm-codes** [mikedilger/gossip#322]
For users whose NIP-05 identity is just a domain name `example.com` instead of `foo@example.com`, Gossip does not properly verify these users.
According to [NIP-05 - showing just the domain as an identifier](https://github.com/nostr-protocol/nips/blob/master/05.md#showing-just-the-domain-as-an-identifier)

> Clients may treat the identifier `_@domain` as the "root" identifier, and choose to display it as just the `<domain>`.

Even for valid NIP-05 documents featuring the root identity, gossip instead displays a strike-through, as it does for invalid NIP-05 identities.
An example of a user for whom this occurs is `fiatjaf.com`, and I have noticed others such as `tonygiorgio.com`. A small note is that the first identity does not have a redirect, but the second does, but both do ultimately point to a valid nostr.json using the `_` identifier and the correct public key.

**Comment by pwm-codes** [comment]
I am not a rust programmer but it would appear that somewhere [hereish](https://github.com/mikedilger/gossip/blob/master/src/nip05.rs#L52)
there should be a special case to deal with if the domain name split return no username.

**Comment by mikedilger** [comment]
This works fine for me.  Mine is "_@mikedilger.com" and it shows as valid (not struck through).  fiatjaf's shows for me as "fiatjaf.com" without strike-through.  I think there may be a few possibilities:

1) For the one with the redirect, that is invalid. NIP-05 says "The /.well-known/nostr.json endpoint MUST NOT return any HTTP redirects."
2) If you list "@domain" that is also invalid. You need an underscore like "_@domain"
3) If fiatjaf is not showing as valid, click his name and select "Update Metadata" and it probably will fix itself. Sometimes the fetch fails and it only fetches every so often.
4) Make sure you are using a recent version of gossip.

If you still think the NIP-05 code is wrong, reply with more specifics and I'll get around to fixing it.

**Comment by pwm-codes** [comment]
fiatjaf's fixed itself upon forcing the update, and apparently redirects are out of spec. Seems like a poor choice to me but that isn't gossip's fault for following the rules as written /shrug. Closing.
