### ISSUE TITLE
Repost of a long form content (kind 30023)

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#324]
Repost of a kind 30023 note is treat like the content was not valid:

note177wnjdnqu5aga7f9szg784jzqssnvyhythky2mx9hlhz6ceh8s5q42jd7t

<img width="716" alt="image" src="https://user-images.githubusercontent.com/89577423/227729887-cfef974e-8593-415e-bda2-4600cb35ca1a.png">

Options:

1) Show the full content, preferably the first N chars and a "Show more" button;
2) Show the title with a link to a long content service, like https://habla.news

**Comment by mikedilger** [comment]
I just read this issue.  Serendipitously I just pushed support for LongFormContent.  Does it work now?  Can you please check?  My push was not intended to fix this, but it may have.

**Comment by dtonon** [comment]
Thank you, now it works.
But the repost with the full content is shown even if the option is not enabled.

**Comment by mikedilger** [comment]
Fixed.
