### ISSUE TITLE
Can not display Chinese Character

### ISSUE THREAD

**Issue by oneforalone** [mikedilger/gossip#334]
I've just new to nostr and gossip, however, i find that gossip can not display Chinese, see the images blow. What's fonts am i missing? And how can i configure it?  Thanks.

<img width="1333" alt="Screenshot 2023-04-01 at 3 51 15 PM" src="https://user-images.githubusercontent.com/41844215/229274277-91c12f26-0bd8-4ab4-bc5f-7853357bc6f3.png">

P.S. I'm using macOS 13.3, Mac Mini M1.

**Comment by mikedilger** [comment]
If you are using a package, use the "-cjk" variant.

If you are compiling, use "--features=lang-cjk"

We don't do this by default because many people don't understand CJK glyphs anyways and don't want the giant sized binary necessary to render them.

Cheers.
