### ISSUE TITLE
Misplaced url rendering

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#336]
note1xg0kgmche45at9djajaf7exgkxsgptdgw6zw2nwtpw8336xm62gqh36k0f

<img width="743" alt="image" src="https://user-images.githubusercontent.com/89577423/229340345-e55d6f0c-0ff0-43ad-ba01-e1a3c31aa9e8.png">

**Comment by bu5hm4nn** [comment]
Is it still an issue after the current merge?

**Comment by dtonon** [comment]
Yes, I'm experimenting the same problem, both Master and Unstable.

**Comment by bu5hm4nn** [comment]
Ok this is the same error as #347. It has something to do with the wrapping newline fix I committed to egui a while ago. I'm not sure if I missed an edge case or if an update in egui broke it again. Will investigate.

**Comment by bu5hm4nn** [comment]
@mikedilger It seems one of my commits didn't make it into your egui/gossip branch. Now I don't know if it is going to solve this, but I did test the fix extensibly for submission to the original egui repo. I don't have the time to resolve the merge conflict with gossip branch so I can't test it locally right now, but I should have time on Thursday.

This is the commit: https://github.com/bu5hm4nn/egui/commit/74e9dd6e1435bba0e3bea217cc9c1c25d3a8eeb1

**Comment by mikedilger** [comment]
Ok. I cherry-picked it. There was no merge conflict to resolve. I've updated gossip unstable to use the updated egui.

**Comment by bu5hm4nn** [comment]
Thank you Mike. Didn't seem to be the fix for this issue unfortunately. Oh well, more egui debugging to do...

**Comment by bu5hm4nn** [comment]
I found a fix that did not seem to have any negative side effects. PR open

**Comment by mikedilger** [comment]
OK. I didn't look I just merged.

**Comment by bu5hm4nn** [comment]
@dtonon can you confirm this is fixed in unstable?

**Comment by dtonon** [comment]
@bu5hm4nn fixed! 👍
