### ISSUE TITLE
Sometimes the main feed seems to ignore the root posts / any post toggle

### ISSUE THREAD

**Issue by pjv** [mikedilger/gossip#337]
I can’t say exactly how to reliably produce this issue, but some sequence of actions on my part involving navigating into threads (and maybe other screens like settings or whatnot) and then back to the main feed will sometimes produce a situation where the toggle says “Any Post” but the timeline is actually showing me “root posts only”. 

IOW when this happens if I toggle to root posts only the feed does not change and then if i toggle back to any post i see a lot of posts that i wasn’t seeing when the toggle was there originally.

I'm not sure if I've also seen the vice versa, but i am sure of seeing the above scenario happen periodically.

**Comment by pjv** [comment]
OK, I think i have the reproduction recipe:

1. start on main feed with toggle set to “any post”
2. pick a note and click its “view thread” icon
3. click the “Feed” button at the very top
<img width="517" alt="SCR-20230403-jbph" src="https://user-images.githubusercontent.com/327716/229546346-7beca1cb-e396-4c69-bdb5-513fba0c04bf.png">

…then I believe you are in the main feed with it showing “root posts only” but the toggle is set to “any post”

**Comment by mikedilger** [comment]
I've noticed this too but have been too busy to get into it. Thanks for documenting.

**Comment by mikedilger** [comment]
Ok this is fixed on master.
