### ISSUE TITLE
Force literal content

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#348]
I want to create a TextNote that contains this url:

````
  https://nostr.band/npub1acg6thl5psv62405rljzkj8spesceyfz2c32udakc2ak0dmvfeyse9p35c
````

But gossip highlights it, indicating that it will rewrite it as "nostr:npub1acg6thl5psv62405rljzkj8spesceyfz2c32udakc2ak0dmvfeyse9p35c" and add a tag before sending.

But that breaks the url.

Maybe we should support prefixing with a backslash, and change our regex to ignore if prefixed with a backslash.

**Comment by bu5hm4nn** [comment]
Actually NIP-27 suggests rewriting to nostr: links after the user has entered a special character like '@'. I think that could be a solution.
<img width="826" alt="Screenshot 2023-04-11 at 21 02 33" src="https://user-images.githubusercontent.com/3328670/231337378-1071f891-ddd2-46f4-b1a2-d65e12b0fda1.png">

**Comment by bu5hm4nn** [comment]
It should either be a special sequence like `@npub1...` or we should only detect bech32 strings that are their own words (preceded by whitespace). Or both.

**Comment by bu5hm4nn** [comment]
<img width="962" alt="Screenshot 2023-04-27 at 09 52 27" src="https://user-images.githubusercontent.com/3328670/234918023-7e200811-d635-4fa7-ad3e-cbf0b1bbc01b.png">

And on incoming notes we shouldn't be replacing text within URL's. We should only interpret `nostr:<n...>` and only if it's a separate word (surrounded by whitespace). In the screenshot above it actually broke the link as it should have contained my npub.

**Comment by dtonon** [comment]
This issue is probably linkable to https://github.com/mikedilger/gossip/issues/414

**Comment by WhiteCat6142** [comment]
The problem is not solved yet on 0.8.0-unstable.

**Comment by WhiteCat6142** [comment]
Maybe same as https://github.com/mikedilger/gossip/issues/400 & https://github.com/mikedilger/gossip/issues/304

**Comment by mikedilger** [comment]
I've pushed some commits to unstable that add the "nostr:" prefix as the content is being created, rather than doing a search-replace just before sending the post:

1) No longer edits your content (if a bech32 string is not prefixed with "nostr:" it stays that way). No need to try to parse URLs differently
2) When you grab an nevent1 or npub1 from a note, it pastes with "nostr:" prefix.
3) When you tag someone, it pastes with "nostr:" prefix.

This should fix this composition issue.

Related but DIFFERENT issues:
1) #424 is a related issue with tags being auto-created right before posting.
2) There is also a similar issue in shatter where we don't parse URLs in rendered notes in a greedy enough way (because we use different code to find http links).
3) Draft composition highlighting may be confusing, doesn't necessarily match what happens to the content or what tags get added, and may need a rethink as to why we even do it.
