### ISSUE TITLE
People -> Followed -> Pull (Overwrite) not working

### ISSUE THREAD

**Issue by 501st-alpha1** [mikedilger/gossip#355]
I have added my keypair to Gossip (v0.5.2), and added some relays that I've previously used on other clients (and checked the read/write/advertise checkboxes), but when I go to People -> Followed and click Pull (Overwrite), nothing happens.  I don't see any logs in the terminal either.

Any idea why this is happening?  Is there anything else I can do to troubleshoot this?

**Comment by mikedilger** [comment]
Some of these early steps work better if you do a restart.  Other than that, I don't know why it wouldn't find your ContactList on one of your 'write' relays.

0.5.2 is getting pretty far behind master. I should probably do another release.

**Comment by 501st-alpha1** [comment]
I did try restarting the app, but that didn't help.

I'll watch for a new release (or maybe build from source myself) and see if that helps.

**Comment by bu5hm4nn** [comment]
This should be resolved with the updated list controls introduced in 0.9 release
