### ISSUE TITLE
NOT NULL constraint failed: local_settings.last_contact_list_edit

### ISSUE THREAD

**Issue by kirkawolff** [mikedilger/gossip#356]
sql version 33 upgrade fails on empty database. Similar to issue #265 

This is a new issue as of commit 6d169cf2f8239e08b770ad86b480f8938b4d82ce

```
2023-04-19T22:32:14.220019Z  INFO src/db/mod.rs:129: Upgrading database to version 33
Error: Error { kind: Sql(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1299 }, Some("NOT NULL constraint failed: local_settings.last_contact_list_edit"))), file: None, line: None }
```

Commenting out the following line allows a fresh install to succeed. 

https://github.com/mikedilger/gossip/blob/94cca223fe4b7c1de77fd23d24e583dae45ac380/src/db/sql/schema33.sql#L4

**Comment by mikedilger** [comment]
Thanks. Fixed.

**Comment by kirkawolff** [comment]
Confirmed fixed
