### ISSUE TITLE
posting (pow) text suggestion

### ISSUE THREAD

**Issue by StellarStoic** [mikedilger/gossip#357]
I triggered a discussion on [nostr](https://snort.social/e/nevent1qqsyz4yxpq8ku9ytt486w4lg2nr3z8740dxm9tynru87hqe8kx8rcrgvn30zc) about the misleading _"leading zero"_ text in POW posting. I think it should be renamed into something different because if we set pow to 7, we don't get 7 leading zeros but we get only 1 zero. 

I had something like this in mind...

![Screenshot (405)](https://user-images.githubusercontent.com/34000272/233729137-3ccb646c-1da3-4c19-9029-eb5248b213f3.png)

but powrespecter@powrelay.xyz on nostr point something interesting out in his [note](https://snort.social/e/nevent1qqsqqqqqudrzgzcw2vpw2eeudexs8mmhz3p8uec8yyu5745u7x6yj3gaq2zh9)

What do you think how can we make this more understandable for an average Joe?

**Comment by mikedilger** [comment]
A pow of 7 gives you 7 leading zeros.  In binary.  I will rename it to "leading zero bits".
