### ISSUE TITLE
Support for portable block lists

### ISSUE THREAD

**Issue by ok300** [mikedilger/gossip#359]
A local list of muted / blocked pubkeys and keywords, that can be exported for use in other clients.

Suggested[^1] by Beautyon.

Gossip already supports muting pubkeys, but AFAIK there's no way to import / export that.

[^1]: https://nostr.band/?q=note1cnqmjdcs7xw35sjjj2474ytu5c26uqa7mzynjgr89wa3uf6xs74su8zftv

**Comment by bu5hm4nn** [comment]
We now have list management controls on the muted list, as well as the option to create private entries (encrypted) to the muted list.
<img width="805" alt="Screenshot 2024-03-07 at 21 35 35" src="https://github.com/mikedilger/gossip/assets/3328670/3e2abdaf-0479-469d-bfce-46066a59f727">
