### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#367]
This image renders upright in a browser, but sideways in gossip.  Some images are only marked as rotated in the exif data. We ought to support that.

nevent1qqsqqqqzhnlrmfr85ap0enqgt7c4evj9g388f4cyau2a84fnt4wvp4qpzemhxue69uhk2er9dchxummnw3ezumrpdejz7qg7waehxw309ahx7um5wgkhqatz9emk2mrvdaexgetj9ehx2ap0qydhwumn8ghj7mn0wd68ytndd94k2erfd3nk2u3wvdhk6tcpz4mhxue69uhkummnw3ezummcw3ezuer9wchsz9mhwden5te0wfjkccte9ehx7um5wghxyctwvshsnhedxx

**Comment by mikedilger** [comment]
This is a shortcoming of the image crate:
https://github.com/image-rs/image/issues/1045
https://github.com/image-rs/image/issues/1901

Then it may need to be carried up to egui-extras, depending on how it is fixed
https://docs.rs/egui_extras/latest/egui_extras/image/fn.load_image_bytes.html

**Comment by brajabi** [comment]
this function may help you

pub fn get_jpeg_orientation(file_path: PathBuf) -> Result<u32, ()> {
  let file = std::fs::File::open(file_path).expect("problem opening the file");
  let mut bufreader = std::io::BufReader::new(&file);
  let exifreader = exif::Reader::new();
  let exif = exifreader
    .read_from_container(&mut bufreader)
    .expect("failed to read the exifreader");

  let orientation: u32 = match exif.get_field(Tag::Orientation, In::PRIMARY) {
    Some(orientation) => match orientation.value.get_uint(0) {
      Some(v @ 1..=8) => v,
      _ => 1,
    },
    None => 1,
  };

  Ok(orientation)
}

**Comment by brajabi** [comment]
![CleanShot 2023-07-12 at 11 32 47](https://github.com/mikedilger/gossip/assets/26709290/d632c4f5-3c7c-4684-a55f-59079aace0c9)
 and this one

**Comment by mikedilger** [comment]
Thanks @brajabi I used some of that as a guide.  I've just pushed image rotation fix to unstable.
