### ISSUE TITLE
Where did Gossip save the pkeys?

### ISSUE THREAD

**Issue by ltraveler** [mikedilger/gossip#396]
I have removed Gossip from my computer, but I can't find where it saves the pkey to be sure that nothing private is saved on my computer after removing the Gossip client. Could you tell me the default path where Gossip saves account pkeys?

**Comment by mikedilger** [comment]
https://docs.rs/dirs/5.0.1/dirs/fn.data_dir.html

Gossip doesn't save private keys.  It only saves an encrypted blob that should be safe if you chose a reasonably safe password.  It saves that inside the sqlite database.  But it's still good to delete.
