### ISSUE TITLE
Possible bug in unstable branch: PoW starvation?

### ISSUE THREAD

**Issue by cryptoquick** [mikedilger/gossip#397]
I think I found a possible bug in the unstable branch, as of 6c3071f3dc890acf679c7d2e113451e803d43678 ... If your client is doing PoW, if you click on a thread from the Main Feed, the screen goes blank. Or maybe it's just loading, not sure. But it seemed to go away after a note submitted. Maybe they're not related, but it might be something to test.

**Comment by mikedilger** [comment]
I've heard of this before. I think it just hogs all the CPUs for the PoW, starving itself until that is completed.  For low PoWs that is not noticeable, but it is not good.  I will leave this open and reword, and maybe someone can fix (or eventually I will get to it, I'm just quite busy still and can't spend much time on gossip ATM).

**Comment by cryptoquick** [comment]
Thank you! Do you think the fix could just be to set num CPU to -= 1 ?

**Comment by mikedilger** [comment]
Nah it wouldn't be giving people everything they should have.  I will set the thread priority so it runs with lower priority but doesn't leave CPUs idle if nobody else is using them.  I asked ChatGPT for help on this one, I hope it compiles.

**Comment by mikedilger** [comment]
Ok this is fixed on unstable.  But be aware you cannot cancel the job without terminating gossip.
