### ISSUE TITLE
arm64 app does not run

### ISSUE THREAD

**Issue by wickles** [mikedilger/gossip#398]
<img width="372" alt="Screenshot 2023-06-09 at hh mm ss copy" src="https://github.com/mikedilger/gossip/assets/4229542/0ffb7a13-30e1-4165-8b5b-24691a7b5833">

Trying to run the app on an M1 mac. The arm64 release build does not work but the x86_64 one does (with rosetta). 

It works fine when built from source for arm64. ~~I suppose I could replace the bin with my own if I want a working .app?~~ (didn't work)

**Comment by mikedilger** [comment]
Yeah it is not signed. Apple requires me to sign a contract that has terms I refuse to accept, so I can't sign it.
