### ISSUE TITLE
Bad parsing of nostr entities in urls

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#400]
When posting a url that contains a nostr entity Gossip wrongly parses the entity adding the "nostr:" prefix.
Example: https://nostr.com/nevent1qqsqqqqqvfzggywqdppqr2n2kfkmdarrqzft2adjnhq7syx7juw3r4gpqqvlhde5

It should not parse it when displaying a (correct) url too, ex:

<img width="664" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/9360bdee-0477-4656-877b-94e59245f717">

nevent1qqs8yry35tega864qn7tj3ha20hj3x3n5qqn5avuplqjkdukd32a3hgpremhxue69uhkummnw3ez6ur4vgh8wetvd3hhyer9wghxuet59uq35amnwvaz7tmjv4kxz7fwwajkcmr0wfjx2u3wdejhgtcpzpmhxue69uhkummnw3ezumt0d5hszrnhwden5te0dehhxtnvdakz7qg4waehxw309ahx7um5wghx77r5wghxgetk9uq3zamnwvaz7tmwdaehgu3wwa5kuef0qy2hwumn8ghj7un9d3shjtnyv9kh2uewd9hj7qg4waehxw309aex2mrp0yhxummnw3ezuun09uq3wamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmny9uq3jamnwvaz7tmjv4kxz7fwdehhxarjv96xjtnrdakj7ll88af

**Comment by mikedilger** [comment]
Closing as dup of #348 which is now fixed
