### ISSUE TITLE
Reposted event not found

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#406]
When someone reposts something by a not followed user, opening the note (bullet button) doesn't show anything, and the status message informs that the event is not findable. But if I view the user's posts, they show up just fine, including the reposted note.
Perhaps a glitch with the relay picker?

**Comment by mikedilger** [comment]
I have noticed this too. It says "Could not find any relays for that event".  But it COULD have found them if it only knew (at that point in the code) that the event was by a user that it already knows some relays for.

This is fixable. I'm going to give it a shot.

**Comment by mikedilger** [comment]
I'm not finding any notes like that anymore. And I can't recall how I knew which user's notes to search under, what the situation was precisely.

**Comment by mikedilger** [comment]
Ah, I remember again.  When someone does a kind-6 repost, including the event, but doesn't add an 'e' tag or doesn't include a recommended relay url in the 'e' tag, then we don't have any idea which relays carry that event.

But we know the author of that event, and via that path we often can get the event loaded by clicking "View Their Posts".

Here is an example for me (the embedded event is not separately available in my database currently)

````json
{
  "id": "57e770284dd81b990cd4a95cee1d616e23e9ff990a8811c61d82cdd1d3703bcc",
  "pubkey": "d307643547703537dfdef811c3dea96f1f9e84c8249e200353425924a9908cf8",
  "created_at": 1687806970,
  "kind": 6,
  "tags": [
    [
      "e",
      "fa2a3dff5b0f0f9006c0d51c03e33f5f5f34dd4da4593c73c659f11970dc68f2",
      "",
      "root"
    ],
    [
      "p",
      "a9385f5cac7f4865692b2493a884082b7386668237cafc33be0825b58cedea6e"
    ]
  ],
  "content": "{\"pubkey\":\"a9385f5cac7f4865692b2493a884082b7386668237cafc33be0825b58cedea6e\",\"content\":\"PSA: attn Apple users. As you prepare to lose access to zaps, consider the following formula:\\n\\nApple + Zaps + FOSS - censorship = GrapheneOS\\n\\n GrapheneOS on a flagship Google Pixel offers a flagship user experience (and yes I've daily driven a flagship iPhone to compare against), but without the censorship and authoritarianism of Tim Apple.\\n\\ngrapheneos.org\\n\\n#zaps #nostr #grownostr #zapathon #bitcoin #plebchain\",\"id\":\"fa2a3dff5b0f0f9006c0d51c03e33f5f5f34dd4da4593c73c659f11970dc68f2\",\"created_at\":1687229506,\"sig\":\"4613235e7f1a53fb0782d700bdb3bba9b17f68d15c2f4a6aa769c5e1ec3caca8045a8995c6ea24fa6148dfd2d0cf0e268e5c4c0df833f7b7633163288026aeb9\",\"kind\":1,\"tags\":[[\"t\",\"zaps\"],[\"t\",\"zaps\"],[\"t\",\"nostr\"],[\"t\",\"nostr\"],[\"t\",\"grownostr\"],[\"t\",\"grownostr\"],[\"t\",\"zapathon\"],[\"t\",\"zapathon\"],[\"t\",\"bitcoin\"],[\"t\",\"bitcoin\"],[\"t\",\"plebchain\"],[\"t\",\"plebchain\"],[\"r\",\"grapheneos.org\"]]}",
  "sig": "46a0e9a76c742095de39852a46e44d6b76ac76ff91ae813362a2ae6c3c44367cb15fb08c57ea608f2c23d6b9bf95c803357a50c39675a1095de8d7ae2f69789a"
}
````

In this situation we could compute write relays for the author and ask them for the note id.

**Comment by mikedilger** [comment]
Ok I pushed changes to unstable that fix this.
