### ISSUE TITLE
Rendering glitch reposting mentioned notes

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#407]
Reposts that contains an mentioned note have a rendering glitch on the right, the last button is partially cropped.
Tested on unstable.

/cc @bu5hm4nn 

<img width="1103" alt="Screenshot 2023-06-25 alle 09 37 06" src="https://github.com/mikedilger/gossip/assets/89577423/e61d4930-a4f0-43bd-94bd-37ff5737191e">

**Comment by mikedilger** [comment]
I can only get it to happen if the note above it forces the width out slightly too much, and only at very specific window widths.

**Comment by dtonon** [comment]
Force how? The note above doesn't have any "long" element (ex. string without spaces) that really push.
Checking randomly around maybe this happens when the mentioned note has a comment longer than one line.

The problem seems somehow related to the scrolling too:

https://github.com/mikedilger/gossip/assets/89577423/2263894d-bc60-444f-9f20-557f4e1fb3aa

**Comment by bu5hm4nn** [comment]
Might be another egui cursor bug 🙄 
The cursor in that needs complete rework, it uses the same cursor for text and widgets and in my opinion they should be separate because text has so many special cases.

**Comment by mikedilger** [comment]
I believe this was fixed in 0aecc1cbe65848b753990117ff557359cd25170f
Please repoen if it recurs.

**Comment by dtonon** [comment]
The problem highlighted in the video seems resolved.
Sometimes I got this, I don't know if it is related:

![image](https://github.com/mikedilger/gossip/assets/89577423/79a0e7f1-45da-48d9-9dad-f8035a7b02c5)

The repost is nostr:nevent1qqs003v6n6rat899k8gqmcsn6knqctt8zmnptuxgyezkv8ga5y30l3cpzemhxue69uhk2er9dchxummnw3ezumrpdejz7qgwwaehxw309ahx7uewd3hkctc7lwvf4

**Comment by mikedilger** [comment]
Is that after the egui update commit?  Last 3 times I tried to update egui there were rendering issues, but I didn't see any last night.  Once I spot one, I'll git-bisect to find the egui commit that is doing this.

**Comment by dtonon** [comment]
I'm running Unstable [3d654664]
