### ISSUE TITLE
rust compiler bug

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#420]
With rust 1.70, compiling for target-cpu=native where native is znver3 (AMD Zen 3), you will get a compiler segfault while compiling fdeflate.

Workarounds:
* Use the nightly compiler (add +nightly after cargo)
* Go back to rust 1.69
* compile without optimizations (skip the --target-cpu=native)

https://github.com/image-rs/fdeflate/issues/6
https://github.com/rust-lang/rust/issues/112398

**Comment by cryptoquick** [comment]
Thanks for posting this! I was just about to file an issue, haha. The +nightly workaround works great.

I'm sure you saw these compiler warnings?

```rust
warning: variable does not need to be mutable
    --> src/people.rs:1026:17
     |
1026 |             let mut person = elem.value_mut();
     |                 ----^^^^^^
     |                 |
     |                 help: remove this `mut`
     |
     = note: `#[warn(unused_mut)]` on by default

warning: variable does not need to be mutable
   --> src/people.rs:997:17
    |
997 |             let mut person = elem.value_mut();
    |                 ----^^^^^^
    |                 |
    |                 help: remove this `mut`

warning: variable does not need to be mutable
   --> src/ui/feed/note/mod.rs:784:9
    |
784 |     let mut style = ui.style_mut();
    |         ----^^^^^
    |         |
    |         help: remove this `mut`

warning: `gossip` (bin "gossip") generated 3 warnings (run `cargo fix --bin "gossip"` to apply 3 suggestions)
```

**Comment by mikedilger** [comment]
Nightly picks that up. A variable of type `&mut T` no longer needs to be mutable to be mutably accessed, as the type itself implies that mutability, and the variable mutability really means that it can be repointed.  I always thought it was a bug that rust required those to be `mut`. Now it doesn't.

**Comment by cryptoquick** [comment]
Nice! Rust is awesome.

**Comment by mikedilger** [comment]
This is no longer relevant.
