### ISSUE TITLE
Categorize People Followed

### ISSUE THREAD

**Issue by ulrichard** [mikedilger/gossip#423]
After I don't run Gossip for a while, I would like to make sure I didn't miss anything important from people that are more important to me than most in my feed. For doing so I have to scroll through all the profiles I follow and check every one of them. 
It would be cool, if I could categorize the people into groups. Then the scrolling would be improved a lot. Even better would be if I could apply a filter to the feed, to only display notes from a certain group.

**Comment by mikedilger** [comment]
agreed. shouldn't be too hard.

**Comment by mikedilger** [comment]
This work is progressing on other open issues. Closing this one.
