### ISSUE TITLE
Download and render images (with setting to keep them as links instead)

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#43]

**Comment by mikedilger** [comment]
Links are links.  But images, not yet.

**Comment by yuvadm** [comment]
Would love to pick up this issue and implement images, anything I should take into consideration before implementing?

**Comment by mikedilger** [comment]
Great. Make sure there is a setting to turn it off.

Take a look at how avatars are handled. QR codes are done in a way where you can only have one showing (they share the same variable) so don't do that.

**Comment by mikedilger** [comment]
This was done by @bu5hm4nn . Closing.
