### ISSUE TITLE
Failed to setup database connection: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })

### ISSUE THREAD

**Issue by roberto68** [mikedilger/gossip#438]
Running the app gets me this error: 
`thread 'main' panicked at 'Failed to setup database connection: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), file: None, line: None }', src/globals.rs:154:55
stack backtrace:
`
then I ran cargo with full backtrace and I got this 
```shell
   0:     0x5599d8c3b831 - <unknown>
   1:     0x5599d8c68f2f - <unknown>
   2:     0x5599d8c36a01 - <unknown>
   3:     0x5599d8c3b645 - <unknown>
   4:     0x5599d8c3cd17 - <unknown>
   5:     0x5599d8c3cb04 - <unknown>
   6:     0x5599d8c3d1cc - <unknown>
   7:     0x5599d8c3d0c7 - <unknown>
   8:     0x5599d8c3bc66 - <unknown>
   9:     0x5599d8c3ce12 - <unknown>
  10:     0x5599d6524263 - <unknown>
  11:     0x5599d65247f3 - <unknown>
  12:     0x5599d6a19fbf - <unknown>
  13:     0x5599d6b73bb3 - <unknown>
  14:     0x5599d6a762e5 - <unknown>
  15:     0x5599d6a40710 - <unknown>
  16:     0x5599d6a4391b - <unknown>
  17:     0x5599d6a4039b - <unknown>
  18:     0x5599d6c2682c - <unknown>
  19:     0x5599d6a791f5 - <unknown>
  20:     0x5599d6a78bae - <unknown>
  21:     0x5599d6780214 - <unknown>
  22:     0x5599d6b75652 - <unknown>
  23:     0x5599d656a4c2 - <unknown>
  24:     0x5599d6bfbc0c - <unknown>
  25:     0x5599d8c2f125 - <unknown>
  26:     0x5599d6bfbbda - <unknown>
  27:     0x5599d67815be - <unknown>
  28:     0x7f0f4c357b4a - __libc_start_call_main
  29:     0x7f0f4c357c0b - __libc_start_main@@GLIBC_2.34
  30:     0x5599d6524af5 - <unknown>
  31:                0x0 - <unknown>

``` 

I'm on Fedora and I build the latest release

**Comment by jadijadi** [comment]
Thanks. Does this happen every time you run it? And since you are on fedora... can you by any chance solve it via turning off the selinux? just a guess: "sudo setenforce 0" and run again

**Comment by mikedilger** [comment]
The backtrace wouldn't help anyways even if you kept debugging symbols on. It is failing on setup.

It might be failing in profile.rs new().  Since you are building from source, if you wanted to you could add tracing messages throughout that function to see how far it is getting.  Or in db/mod.rs init_database() andd one before the "let connection" line to see if it gets there to print out the db_path.

Just by looking at my code nothing obvious stands out.

**Comment by mikedilger** [comment]
Check if `~/.local/share` exists.

**Comment by mdesmedt** [comment]
The same error is happening on MacOS running gossip for the first time from source.

`thread 'main' panicked at 'Failed to setup database connection: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), file: None, line: None }', src/globals.rs:154:55`

**Comment by roberto68** [comment]
> fs::canonicalize(&base_dir).unwrap_or(base_dir)
 
now I get "error" on `src/globals.rs:154:55` where's ... `.expect("Failed to setup database connection"))`

**Comment by mikedilger** [comment]
Ok I see the bug. I'll put in that fix @mdesmedt .  Thanks.

**Comment by roberto68** [comment]
however I added few relays (both write and read) and nothing happens - no content/feed loaded (I created "account" on plebstr).

**Comment by jadijadi** [comment]
1. Have you tried closing the app and opening it again? it is needed for
most configs
2. Generally it's good to practice the "one issue per issue" mindset
