### ISSUE TITLE
Account->Profile not editable anymore, write relays must be configured, but they are

### ISSUE THREAD

**Issue by Strunzdesign** [mikedilger/gossip#445]
Hi,

I just updated to the latest master that incorporates the new database framework. I compile the software by myself (Gentoo Linux).

Today, for the first time, I see that it is not possible anymore to edit the fields of my profile. After unlocking the private key, the screen mentions that I have to configure write relays first. However, I have about ten write relays configured. A restart of the application doesn't fix the issue.

Kind regards,
Florian

**Comment by mikedilger** [comment]
Strange. I can reproduce this. Will fix

**Comment by mikedilger** [comment]
fixed on master
