### ISSUE TITLE
on new setup, adding a relay does not connect to the relay till you restart gossip

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#449]
Just making some notes, from a fresh setup perspective.  This one might be confusing for onboarding.

It says it adds the relay but it never attempts to connect. (until you restart)

**Comment by mikedilger** [comment]
Ok thanks. I've got a whole onboarding sprint forthcoming, probably about 2 sprints in the future.

**Comment by dtonon** [comment]
This problem has been addressed in https://github.com/mikedilger/gossip/pull/402#issuecomment-1616838542 > **A6**

**Comment by mikedilger** [comment]
pushed a fix in 698cc455f5c2353a95f6d3162034de0207d64cb5
