### ISSUE TITLE
relays are really hard to edit

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#450]
When you add a relay, it disappears into the huge list of relays and is really hard to find, then when you find it and start clicking the check boxes, it jumps to the top.  It'd be easier if when you add a relay, if it stuck to the top.  (or if the list was searchable).

Just one of my main usability issues at the moment so I thought I'd file this..

**Comment by mikedilger** [comment]
@bu5hm4nn is rebuilding that page. Maybe it still does that on the rebuild, in which case he can consider this issue.

**Comment by bu5hm4nn** [comment]
Yeah, that will become way easier, you will be able to sort and search for relays, and etc. maybe 2 more weeks until it gets merged

**Comment by jeremyd** [comment]
sweet!
