### ISSUE TITLE
Reorganization of preferences

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#457]
I would switch from the current tab design to the sub-menu structure, available in the sidebar.
The setting reorganization is outlined below, with this main structure/order:

* Theme & UI
* Content
* Posting
* Network
* Database

If we move "Settings" below "Account" the Identity section is not needed; the "logN iterations" can be moved under Account > Keys.

For long areas, ex. network, I suggest exposing first the main settings, ones that are changed with more frequency or enable/disable a function, and the show the "advanced" ones in a collapsible section.
On the top right, we could have a toggle "Show advanced" that automatically expand all the sections.
This should permit a fast and productive navigation of the settings, without intimidate the newcomers, but letting the advanced users to access the power of a proper fine-tuning.

For some preferences (ex. DPI, PoW, etc) I would remove the slider because this sort of component is not particularly useful, but on the other hand make the UI more complicated and harder to manage.

This structure can be refactored using the current UI elements. If possibile I can mockup a more detailed design, but maybe now it is not a priority.

@mikedilger @bu5hm4nn let me know what do you think about this.
If it is okay, I can continue to refactor the code on my own.

---

### Theme

Theme: [ Themes list ]  
Version: [ Light / Dark ]  
[ ] Follow OS dark mode

> In a near future here there will be more preferences about the accent/secondary colors and where apply them.

### User interface

[ ] Highlight unread events  
[ ] Show posting area at the top  

<details>
<summary>Advance settings</summary>

### Advance settings
[ ] Ovveride to [72] DPI  
Maximum FPS: [15] FPS  
</details>

### Event types

[ ] Show reposts  
[ ] Show long form posts  
[ ] Show direct messages  

### Events interaction

[ ] Enable reactions  
[ ] Enable zaps  

### Events visualization

[ ] Expand mentions inline  
[ ] Show all media inline  

<details>
<summary>Advance settings</summary>

### Advance settings
> The current ones
</details>

### Proof of work

[ ] Use proof of work  
Apply [25] leading zero bits  

### Client signature

[ ] Add tag  ['client', 'gossip'] to posts  
[ ] Send User-Agent Header to relays: gossip/0.8.0-unstable-xxxxx  

### General setting

[ ] Fetch avatars  
[ ] Fetch images and videos  
[ ] Check NIP-05  
[ ] Fetch users metadata  
[ ] Offline mode (require restart)  

<details>
<summary>Advance settings</summary>

### Advance settings
> The current ones
</details>

## Database

Prune period: [30] days  
[ Prune database now ]  

### Quick infos

Stored events: 778.082  
Database size: 456MB

**Comment by dtonon** [comment]
I would like to review the Save / Revert UX, but I think we can pick-up this in a separate issue; we also need to face the case when a restart is needed.

Just to be sure, separating the preferences into different views don't create any problems with the save, right?

**Comment by mikedilger** [comment]
I like this structure.  Separating into different views is no problem.  But the current code saves ALL the views, it doesn't save them separately.  If you wanted to save them separately we would need separate UI variables holding separate copies of the unsaved parts of settings... it would be a lot more complex code-wise.

I like the save/revert because sometimes you accidentally change something and didn't mean to, and aren't even sure what you changed.

**Comment by dtonon** [comment]
> If you wanted to save them separately we would need separate UI variables holding separate copies of the unsaved parts of settings... it would be a lot more complex code-wise.

I suspected as much.
Having a single save acting on several different pages is not a good user interface.
No problem, I think we can keep the tabs for now, reorganize the structure and move to the submenu structure when we have some time to invest on that. Is that okay?

I also like the revert command, it is useful. When I said "review the save/revert UX," I meant to move the area down, above the scrolling view:

<img width="845" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/644bf0d7-9eb4-4c6e-b475-ac37b1e92658">

To do this we need to hide the compose area from the settings (it is not useful at all) and move the lock/post button up when the status bar appears.
This sort of status bar with buttons can be useful in other scenarios.

**Comment by mikedilger** [comment]
I'm making a change to how settings are stored. They will each be their own key-value in the general database. After that is done, saving settings pages individually won't be a problem anymore.  I also won't need to do heavy migrations just to add a setting.

**Comment by bu5hm4nn** [comment]
Settings have been organized in tabs now, this review is obsolete imho
