### ISSUE TITLE
Posts at the same time are randomly replaced each time you recompute.

### ISSUE THREAD

**Issue by s3-odara** [mikedilger/gossip#458]
https://github.com/mikedilger/gossip/assets/76041920/ba4f3556-3b51-4c1a-a2b7-40f385e4583c

If there is a post with the same UNIX time, it goes up and down randomly.
I think they should be fixed in the order in which they were first obtained.

**Comment by mikedilger** [comment]
Hah!  I've never seen that.  Ok, that's an easy fix, pushed to unstable.

**Comment by babonyx** [comment]
I have the same issue still on master branch. Can you reference the commit for the fix here?

**Comment by babonyx** [comment]
This I guess fb05eb970ca4fbc5075a856e5538ce58fac2cb3e ... hmm

**Comment by mikedilger** [comment]
Ok, from looking at the code it appears that read_events_referencing_person dup keys might come out of LMDB in any order.  So this might affect the inbox.  I can't see how it would affect other feeds.

**Comment by mikedilger** [comment]
pushed a fix for this to unstable 389749e6e375629cc8098641532d6138d8e458a3

**Comment by s3-odara** [comment]
I'm using 0.9.0-unstable-aaacdf28 and it looks like I'm facing the same issue...

https://github.com/mikedilger/gossip/assets/76041920/5dac7916-570e-4487-a2f0-007609c8e773

**Comment by mikedilger** [comment]
I added a fix at c70b5cfce2302c30f762e1bae11aba1d6a620304, still on unstable branch.  Will be on master soon.

**Comment by s3-odara** [comment]
Oh, I hadn't noticed that commit. Thank you very much.
