### ISSUE TITLE
My Relays - how do I advertise changes?

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#467]
Seems to be missing.

**Comment by dtonon** [comment]
Yes the new relay section misses the advertise button!
I designed a couple of different solutions, but I'm not at all convinced:

<img width="1049" alt="Screenshot 2023-09-23 alle 00 04 15" src="https://github.com/mikedilger/gossip/assets/89577423/d37905fc-9621-4054-92c7-8bad9351a5f0">

<img width="1045" alt="Screenshot 2023-09-23 alle 00 09 57" src="https://github.com/mikedilger/gossip/assets/89577423/2d377d00-7a62-4e01-819c-f36a3006e6bf">
<br/><br/>

I will discuss with @bu5hm4nn the faster approach and I will update the main issue (https://github.com/mikedilger/gossip/issues/477).

**Comment by bu5hm4nn** [comment]
So we did add a simple button back in that solves this issue. We should re-style it.
The "pick again" button only makes sense on the "Activity Monitor" or "Coverage Report" pages.

**Comment by dtonon** [comment]
> The "pick again" button only makes sense on the "Activity Monitor"

Oh yes, sorry, this is an old mockup to test the different solutions, so I added more buttons to have a more generic use case.

https://github.com/mikedilger/gossip/pull/476 fixes this.

**Comment by dtonon** [comment]
I close this because the problem is already tracked in https://github.com/mikedilger/gossip/issues/477

**Comment by dtonon** [comment]
I close because duplicate, the problem is already tracked in https://github.com/mikedilger/gossip/issues/477
