### ISSUE TITLE
app crashes during startup when built from fedora

### ISSUE THREAD

**Issue by drunker-sailor** [mikedilger/gossip#470]
Trying to build from source on Fedora 38. As far as I can tell, I have all of the equivalent build dependencies and am not seeing any compile errors but when I attempt to run the executable, I get an error and the process crashes immediately.

Curious, if you might have any thoughts or advice? I did attempt with selinux disabled (both at runtime, then recompiled with it disabled as well) but this did not make any difference.

PC is a little bit on the old side but nothing drastic and otherwise still a normal x64 system.

---

### System info and build dependencies

Distro: Fedora 38, fully updated

One of the main differences for Fedora builds as compared to Debian-based ones is that ffmpeg support rather than using `libavutil-dev`, `libavformat-dev`, `libavfilter-dev`, `libavdevice-dev`, etc is in package `ffmpeg-devel` and due to licensing restrictions, this comes from the 3rd party rpmfusion repo rather than Fedora's central repos. Besides this, it is most just a matter of finding the equivalent package names for the various libraries.

    $ uname -r
    6.4.6-200.fc38.x86_64
     
    // adding rpmfusion repo for ffmpeg support
    sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
      
    // installing c dev tools - not sure if this is strictly needed but help to be on par with Debian's build-essential
    sudo dnf group install "C Development Tools and Libraries";
     
    sudo dnf install rust cargo cmake git gcc g++ glibc-devel pkgconf;
    sudo dnf install openssl-devel fontconfig-devel ffmpeg-devel libXext-devel clang-devel;
     
    $ rustc --version
    rustc 1.71.1 (eb26296b5 2023-08-03) (Fedora 1.71.1-1.fc38)
     
    $ cargo --version
    cargo 1.71.1

---

### Build output

Followed the instructions [here](), e.g.

    $ git clone https://github.com/mikedilger/gossip
    $ cd gossip/
    $ cargo build --release
    $ strip ./target/release/gossip

After, I ran into issues, I also tried with

    $ cd ..
    $ rm -rf gossip
    $ git clone https://github.com/mikedilger/gossip
    $ cd gossip/
    $ RUSTFLAGS="-C target-cpu=native --cfg tokio_unstable" cargo build --release
    $ strip ./target/release/gossip

I did get a warning about `warning: methods `highlight_color` and `accent_complementary_color` are never used` but ignored it, since it was only a warning. There were no errors.

full build log:

[gossip-build-log.txt](https://github.com/mikedilger/gossip/files/12389998/gossip-build-log.txt)

---

### Runtime output

I checked and the executable already had the execute bit set. But running the app gives

    $ ./target/release/gossip
    2023-08-21T00:12:26.620461Z  INFO src/filter.rs:30: No spam filter: No such file or directory (os error 2)
    2023-08-21T00:12:26.623675Z  INFO src/storage/migrations/mod.rs:37: LMDB Migration 0 -> 1: Computing and storing event relationships for 0 events...
    2023-08-21T00:12:26.623699Z  INFO src/storage/migrations/mod.rs:87: syncing...
    2023-08-21T00:12:26.623704Z  INFO src/storage/migrations/mod.rs:57: done.
    2023-08-21T00:12:26.623725Z  INFO src/storage/migrations/mod.rs:43: LMDB Migration 1 -> 2: Updating Settings...
    2023-08-21T00:12:26.623744Z  INFO src/storage/migrations/mod.rs:57: done.
    2023-08-21T00:12:26.623754Z  INFO src/storage/migrations/mod.rs:47: LMDB Migration 2 -> 3: Removing invalid relays...
    2023-08-21T00:12:26.623765Z  INFO src/storage/migrations/mod.rs:116: Deleted 0 bad relays
    2023-08-21T00:12:26.623774Z  INFO src/storage/migrations/mod.rs:57: done.
    2023-08-21T00:12:26.623780Z  INFO src/storage/migrations/mod.rs:51: LMDB Migration 3 -> 4: Using kv for settings...
    Error: Error { kind: General("Settings missing."), file: None, line: None }

Subsequent attempts generate the same output, with only the timestamps being different.

Disabling SELinux with `sudo setenforce 0` also made no difference and gave the same output.

I am on a VPN (configured via network manager) but plan on accessing nostr while connected to one. If you think that is significant, I can try without it but I didn't think that would make a difference.

here's the build log with selinux disabled (main differences I was seeing is that some things were built in a different order and it was actually slower overall)

[gossip-build-log-selinux-disabled.txt](https://github.com/mikedilger/gossip/files/12390051/gossip-build-log-selinux-disabled.txt)

**Comment by drunker-sailor** [comment]
Update: also tried building from tarred release sources

    $ curl -L -o gossip-v0.7.0.tar.gz https://github.com/mikedilger/gossip/archive/refs/tags/v0.7.0.tar.gz
    $ mkdir gossip-v0.7.0
    $ tar -x -f gossip-v0.7.0.tar.gz -C gossip-v0.7.0
    $ cd gossip-v0.7.0/gossip-0.7.0
    $ cargo build --release
    $ strip ./target/release/gossip

This time, I got 3 compile warnings from cargo:

    warning: variable does not need to be mutable
        --> src/people.rs:1012:17
         |
    1012 |             let mut person = elem.value_mut();
         |                 ----^^^^^^
         |                 |
         |                 help: remove this `mut`
         |
         = note: `#[warn(unused_mut)]` on by default
     
    warning: variable does not need to be mutable
       --> src/people.rs:983:17
        |
    983 |             let mut person = elem.value_mut();
        |                 ----^^^^^^
        |                 |
        |                 help: remove this `mut`
      
    warning: variable does not need to be mutable
       --> src/ui/feed/note/mod.rs:717:9
        |
    717 |     let mut style = ui.style_mut();
        |         ----^^^^^
        |         |
        |         help: remove this `mut`
     
    warning: `gossip` (bin "gossip") generated 3 warnings (run `cargo fix --bin "gossip"` to apply 3 suggestions)
        Finished release [optimized] target(s) in 4m 59s
    
And a different runtime error but the same behavior (app crashes during startup)

    $ ./target/release/gossip
    thread 'main' panicked at 'Database version 37 is newer than this binary which expects version 36.', src/db/mod.rs:113:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Again, having SELinux on or off made no difference.

**Comment by mikedilger** [comment]
Somehow you are at migration 3 and it can't get to 4 because you have no 'settings2' object.  I thought I had all my bases covered, all possible paths someone might have taken running on various buggy commits, etc, but apparently there was some way that this state could happen.

I'm going to change the code here to create default settings if this happens. You'll have to try to remember your settings and set them up again.  Sorry about that.  The rest of your data (events, downloaded images) will be fine.

**Comment by mikedilger** [comment]
Please checkout the unstable branch, compile and run it.  It should reset your settings and apologize.

**Comment by WhiteCat6142** [comment]
Setting migration seems to be very unstable for skipping versions.

**Comment by WhiteCat6142** [comment]
The way older->9e94d26->6206b18->886d4d5(HEAD) does work.

**Comment by mikedilger** [comment]
Anybody that migrated from 1 -> 2 on commits between 70274f76c01ee46a53bedff76240200a3c4fe8d2 and 9e94d2698ee8e4e71085e870a99342b43d3f7d9b had their settings2 written as 'settings'.

I've made another change to fall back to reading it from 'settings' instead.  If anybody is still stuck please try unstable.

**Comment by mikedilger** [comment]
The people this happened to, by now, have probably resolved their issue. If not, this can be reopened.
