### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by deavmi** [mikedilger/gossip#471]
I keep getting a build error with libav as such:
![Screenshot from 2023-08-21 09-59-05](https://github.com/mikedilger/gossip/assets/5207740/f4f92a30-368e-4f50-af22-a89eafab5f88)

**Comment by deavmi** [comment]
Is libav a new dependency perhap?

**Comment by mikedilger** [comment]
Are you compiling with the 'video-ffmpeg' feature? That only works on systems that have ffmpeg dependencies installed, which is why it is an optional feature and why we can't ship it in packaged builds.

**Comment by deavmi** [comment]
Danke!
