### ISSUE TITLE
NIP09: show/hide deleted events

### ISSUE THREAD

**Issue by nbenaglia** [mikedilger/gossip#473]
NIP09 (event deletion, https://github.com/nostr-protocol/nips/blob/master/09.md) states that

` Clients SHOULD hide or otherwise indicate a deletion status for referenced events.`

As user I'd like to have a client setting option to decide whether deleted events:
- should be displayed and marked as deleted (this is the current gossip behaviour)
- should not displayed at all

**Comment by mikedilger** [comment]
Fair enough.
