### ISSUE TITLE
0.8

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#491]
- [x] Cherry-pick over petname commits once proven stable, since 0.8 has partial functionality in this regard already c960a5fde6a671000299592aba1337a99a1dbe93 and 00821f2639a87f481a3f24eafa2276efb5ae6ae7
- [ ] UI updates to relays pages
- [ ] UI updates to DMs pages, if any
- [x] Fix url.domain() bug by updating nostr-types

**Comment by bu5hm4nn** [comment]
done

**Comment by mikedilger** [comment]
Yeah, I pushed it so any further changes go into unstable/master now.
