### ISSUE TITLE
Private chats fail to decrypt after import

### ISSUE THREAD

**Issue by jamesob** [mikedilger/gossip#500]
I imported an nsec1 and PMs are failing to decrypt:
![image](https://github.com/mikedilger/gossip/assets/73197/86d10a85-25c9-42f1-be6b-693030eb1590)

**Comment by jamesob** [comment]
Ah, the issue was that I hadn't yet decrypted my keys after startup. Maybe a prompt on this page if keys are still encrypted would be good.

**Comment by mikedilger** [comment]
Good point. I've just added the same warning/link as other pages have that need your key unlocked.
