### ISSUE TITLE
Scrolling feels weird

### ISSUE THREAD

**Issue by jamesob** [mikedilger/gossip#503]
Paging through a long mainfeed feels difficult with the way scrolling works - the momentum is kind of odd. Would be nice to be able to disable this, assuming you've consciously modified the way scrolling would work otherwise.

**Comment by jamesob** [comment]
I'm on Arch Linux on a big desktop, but I wouldn't think hardware/OS would make much of a difference unless egui is really rough?

**Comment by badonyx** [comment]
I'm mainly thinking about the input hardware, like trackpad or mouse wheel, which can behave differently especially on macOS.

**Comment by mikedilger** [comment]
As you both noticed, yes I coded a custom inertial scrolling thing.  It slows down and then friction stops.  I've always loved it, thought it was my best work, but fuck I guess you can't please everybody.

You would have hated what it was like before though.... random jumps, complete chaos.  I didn't need to do the inertial thing, but I had the idea and it only took a few lines of code and I was so chuffed that it was that easy I left it in place.

I guess I need a setting to change scrolling behavior.

**Comment by dtonon** [comment]
For me (Macbook Pro M1) the inertial scrolling works really good. I didn't know was coded by Mike to level up the egui one, it feels native!

@jamesob @badonyx can you share a video?

**Comment by bu5hm4nn** [comment]
@jamesob @badonyx please also mention what OS and OS version you are on

**Comment by badonyx** [comment]
@bu5hm4nn apple trackpads all work basically the same on every version of macos.

I tried on Windows with a mouse wheel and it is more noticeable in that configuration. Might capture a video but don't see much point since it is not a visual bug. 

Any deviation from "native" scrolling is always going to feel "off".

**Comment by bu5hm4nn** [comment]
@badonyx Do you have the "Maximum FPS" set really low in "UI" settings? I am on macOS and it's really smooth, feels very similar to scrolling in Safari to me.

**Comment by mikedilger** [comment]
> Any deviation from "native" scrolling is always going to feel "off" in some way to some users.

Egui implements scrolling extremely simply by jumping by the amount the mouse requested. PageUp/PageDown/Up/Down are ignored and do not affect scrolling.  And trackpads are treated just like mice.

We either have to replicate egui's simple scrolling, or implement something else.  There is no option for "native" scrolling.

**Comment by mikedilger** [comment]
I've added the option on the unstable branch.  It replicates the egui logic, except that it honors keyboard movement keys.  I also added a mouse wheel acceleration adjustment.

It will be available on master within the next few days.

I won't close this issue yet until I get feedback on whether this works for you.

**Comment by dtonon** [comment]
@mikedilger your inertial scrolling is really better!
At least on macOS there are no reasons to turn it off.

**Comment by mikedilger** [comment]
It is better for mice, but maybe when dragging your finger across a trackpad it should just feel like dragging that perfectly tracks your finger, and probably turning it off would feel better for those people.  People may need to adjust their acceleration to get that.  I don't have a trackpad so I'll have to see what @jamesob and @badonyx think.

**Comment by dtonon** [comment]
I'm using your inertial with a trackpad.
On small movements, your inertial mode has a really little delay, but you can spot it only if you go up and down several times with quick movements, a behavior that you never use, because in the feed you usually move only in one direction.

**Comment by badonyx** [comment]
Inertial scrolling OFF feels perfect to me with the macbook trackpad. Have not tried with a mouse wheel yet.

**Comment by mikedilger** [comment]
Thanks for the confirmation. Closing.
