### ISSUE TITLE
does it really have to run on macOS 13.0+?

### ISSUE THREAD

**Issue by eleaner** [mikedilger/gossip#509]
Is there any chance to compile it for Monterey?

**Comment by mikedilger** [comment]
We should probably try to target 11 (Big Sur)

https://users.rust-lang.org/t/compile-rust-binary-for-older-versions-of-mac-osx/38695

**Comment by eleaner** [comment]
I only hope that Big Sur library will work on 12 too. That's as far as my 5.1 cMP will go (an that with some cheating)

Frankly, I am sick of apple forcing m to replace my older hardware :(

**Comment by mikedilger** [comment]
I've released 0.8.1 to support 0.12 as well.
