### ISSUE TITLE
UI/UX of tagging people

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#512]
What we have is atrocious.  We need to have an in-place drop-down menu when someone type '@' followed by something other than white-space and preceded by white-space.

We also need that to be a list taken from petname first, name second.  Don't use 'Display Name' which is often not intended to be type-able.

**Comment by bu5hm4nn** [comment]
I agree. I can take a shot at this, but I'll let @dtonon rank it in priority.

**Comment by mikedilger** [comment]
Should also look at person2::display_name() and crate::names.rs to get everything in sync.

**Comment by mikedilger** [comment]
and sync with output of this discussion https://github.com/nostr-protocol/nips/pull/794

**Comment by dtonon** [comment]
> I'll let @dtonon rank it in priority

We are now used to it but yes, objectively it is a priority for a good UX.
The classic dropdown list while the user types is ok.

**Comment by mikedilger** [comment]
So I pushed a branch "tagging" that determines if the user is in the middle of typing a tag and provides what they have typed so far.  So that is a start.

**Comment by dtonon** [comment]
Ops sorry, I forgot that this issue was open, I started a new issue connecting it to the pull request: https://github.com/mikedilger/gossip/issues/566

I'm going to close this one and link it to the new issue for reference.
