### ISSUE TITLE
Add `gossip-bin` to `Installing` section

### ISSUE THREAD

**Issue by qlrd** [mikedilger/gossip#513]
AUR packages:

- `gossip` package is outdated;
- `gossip-git` is very processor intensive for some computers;
- I created a new package, `gossip-bin` with correct version and only install `AppImage`, so its less processor intensive. See [here](https://aur.archlinux.org/packages/gossip-bin).

**Comment by mikedilger** [comment]
Cool  I've heard the AppImage doesn't work for some people.  But on ArchLinux that shouldn't be a problem.

I'll update the other packages.  I forgot about them.

**Comment by qlrd** [comment]
Nice!

Thanks for the update.

Maybe we can close this issue?
