### ISSUE TITLE
Replying to reposts

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#520]
Replying to reposts shows nothing above the draft post area.

Should we allow replies to reposts? Is the reply replying to the inner note, or the repost itself? Probably should be the inner note. The  If so we should show something. Maybe we don't because we lose the original wrapper event, and the inner event was just json-serialized content and not otherwise stored in our database?

**Comment by mikedilger** [comment]
Related to (but different from) #401

**Comment by bu5hm4nn** [comment]
When I did the original UI work around note rendering, we discussed this and agreed that replies should be to the original post only. There should not be any buttons to initiate a reply to a repost, at least back in the day, that's how it was.

**Comment by mikedilger** [comment]
I'm happy with that. So it should show and reply to the original inner post.

**Comment by mikedilger** [comment]
This issue occurs for kind-6 reposts - the reply area is only blank if the inner note being replied to is not local (and was rendered via the embedded event).  Perhaps we could fetch it when they press reply, so that it should render soon.

**Comment by bu5hm4nn** [comment]
We are only stuck when there is no relay hint contained in the embedded note. One of the popular clients not adding relay hints is Amethyst, I filed this issue to alert them to the situation: https://github.com/vitorpamplona/amethyst/issues/802

**Comment by bu5hm4nn** [comment]
So I understand Vitor's suggestion this way: try to find the 10002 or profile for the author of the embedded note, then repost to his inbox relays.

Maybe we should do a relay search anytime we receive an embedded kind 6, so there won't be a delay when a user decides to repost. Thoughts @mikedilger?

**Comment by mikedilger** [comment]
Ok let's do it that way.

**Comment by bu5hm4nn** [comment]
@mikedilger 's work on this has been merged to unstable ('seeker' branch) and it now needs testing. From what I am seeing it is already a really great improvement. @dtonon

**Comment by mikedilger** [comment]
While the inner event doesn't exist yet, can we disable the reply/repost buttons?

**Comment by bu5hm4nn** [comment]
Fixed with 625381969a22e777d9c64bb4dfa3ac265f82438b
