### ISSUE TITLE
typing up a note feels laggy 

### ISSUE THREAD

**Issue by GretaFrank** [mikedilger/gossip#521]
i only type at 80 WPM but it is very noticeable for me that the letters don't show up on the screen as i type them but about half a keystroke late. 

i don't get the same kind of delay when typing in any other application, so it has to be an issue with gossip.

i'm on Windows 10 PC with ~ 4 ghz, 8 Core/ 16Thread intel X series CPU from 2017.  about 5 GB ram available out of 16GB installed.  CPU is at about 5% utilization.

gossip is using 377 MB ram ( not an issue for me ) and just 0.2% of CPU while i am typing.

i am a technical person but not a software engineer so forgive me if my theory is obviously wrong but it seems like Gossip is only updating that text display about 10 times per second or so instead of on every frame at 60 fps that my display runs at.

it is aggravating enough that for long posts i have to switch to a different NOSTR client because it throws my typing completely off when the text isn't showing up on the screen at the same time as i'm typing.  it makes me feel as if i'm stuck in a continuous typo because at any given time what is showing up on the screen isn't what my brain is expecting to show up there at that time so my brain thinks i must have made a typo ... THE ENTIRE TIME.

maybe there is a setting to change this somewhere ?

**Comment by GretaFrank** [comment]
actually now that i think of it scrolling my timeline in Gossip has the same kind of feeling like it's running at 10-20 FPS instead of 60 ...

it is not as aggravating than the typing issue - i mainly mention it because i think they may be related ...

you will only notice this if you scroll by dragging the slider on the right.  you probably won't notice it by using the mouse scroll wheel.

**Comment by mikedilger** [comment]
Go to Settings > UI and adjust `Maximum FPS` to whatever you want.  But be aware that every frame recomputes everything because it is an immediate mode renderer, so the higher your frame rate, the more CPU you will use.

**Comment by GretaFrank** [comment]
thanks so much, it worked !

my CPU utilization went from about 0.2% to about 1% and i can see how that may be non-trivial in some battery powered applications or maybe on extremely underpowered ultrabooks ...

but i'm on a desktop with a 1,000W power supply and have an AIO liquid cooler on my CPU - i honestly wouldn't tell if there was a 20% CPU load ... at the very least it would be less noticeable than 12 FPS refresh ...

maybe someday, 10 years from now, Gossip will be able to dynamically adjust these things based on demand but for the time being i'm perfectly happy with just leaving it at 60 fps ...

thanks again.
