### ISSUE TITLE
Debian package .desktop file opens multiple instance of application under Ubuntu / Wayland

### ISSUE THREAD

**Issue by acarlton** [mikedilger/gossip#527]
When I start gossip by clicking on the Desktop icon, the app runs. When I click it a second time, it opens up a new application window and doesn't seem to recognize the window manager class. I would expect clicking on the icon a second time to make my original window active instead of spawning a separate process.

I see StartupWMClass is set correctly in the .desktop file. Let me know if you need more information or testing. I've played around with it myself a little, but don't know enough to fix it yet.

* gossip on `master` at commit `d01a92181a9b647329f051823670d42f8d0f38a1`
* Ubuntu 23.04
* Gnome 44.3
* Wayland

**Comment by mikedilger** [comment]
First, I've never expected, seen, or used such behavior... except on MacOS where I find it strange and confusing. It is especially annoying with terminals where I really do want multiple terminal windows and always forget how to get it. But this is just me venting. Gossip shouldn't have multiple windows at once.

Problem is that I doubt the desktop file can do this.  I think the executable has to detect whether a window is already running and inform the window manager or send a dbus message to it to unminify, for example. I did a quick search and didn't find any guidance.

**Comment by acarlton** [comment]
Thanks for the reply. I actually researched this for a few hours yesterday before posting, so I'm not just throwing a minor complaint out there, but I am rather new to Freedesktop standards, Gnome and all that, so I don't have all the context either.

I found [this post](https://askubuntu.com/questions/367396/what-does-the-startupwmclass-field-of-a-desktop-file-represent) which describes the problem. However, they are using `xprop` and such to diagnose, so I wonder if Wayland does things differently and invalidates those debugging assumptions.

I'm also looking at (and trying to learn) the [Freedesktop spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) and have played with overriding the .desktop file and adding `SingleMainWindow` and trying to figure out if `StartupNotify` is relevant, according to the [Startup Notification spec](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-0.1.txt), but after a quick glance at the spec, I'm wondering if those messages require some handling by the gossip application to work. This is probably the dbus message you are referencing -- guess I'm catching up.

At present, this is the tidbit from the Startup Notification spec that might be needed in the executable:
```
StartupNotify=BOOLEAN

  If true, it is KNOWN that the application will send a "remove"
  message when started with the DESKTOP_LAUNCH_ID environment variable
  set.
```

Let me know what you think. I'll keep learning myself as well :)

**Comment by acarlton** [comment]
A few more bits of documentation for reference:
* egui documentation on [NativeOptions::app_id](https://docs.rs/eframe/latest/eframe/struct.NativeOptions.html#structfield.app_id) with a note specifically WRT Wayland
* Corresponding [XDG docs](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) on Wayland app_id and best practices

I'm working to try and set `app_id` on my local copy, but it hasn't quite worked yet.

**Comment by acarlton** [comment]
@mikedilger I got it to work locally using the attached patch! I'm not sure if there is a better way to include the eframe `wayland` feature conditionally in the Cargo.toml. Still new to Rust and working my way through The Rust Programming Language :/

Happy to fork and open a PR if that would be better.

[wayland_app_id.patch.txt](https://github.com/mikedilger/gossip/files/12819938/wayland_app_id.patch.txt)

**Comment by mikedilger** [comment]
Ok I added this.  I set the commit author to "Aaron Carlton <aaron_carlton@example.com>".
