### ISSUE TITLE
Improve documentation for developers

### ISSUE THREAD

**Issue by nbenaglia** [mikedilger/gossip#528]
To facilitate new potential developers joining the project:

- [x] Create a dedicated folder for docs and logo
- [x] Add an architectural overview schema
- [x] Refactor existing documentation

**Comment by mikedilger** [comment]
I made major improvements in the last few pushes.

Run `cargo doc --lib` from the root and then browse to `target/doc/gossip_lib/index.html`

General documentation will go in the doc comment at the top of lib.rs, which will then display at the top of that page.

**Comment by nbenaglia** [comment]
`cargo doc --open` will directly open it in the browser

**Comment by mikedilger** [comment]
Oh that is sick
