### ISSUE TITLE
Cannot pull down mute list

### ISSUE THREAD

**Issue by badonyx** [mikedilger/gossip#533]
Gossip detects a larger remote mute list than I have locally, but nothing happens when pressing "Overwrite" or "Merge", and there is no logging output.

This worked for me I think before around 0.8.0.

**Comment by mikedilger** [comment]
Does the local date change to the current date?

**Comment by badonyx** [comment]
Yes it does. I didn't notice because it gets hidden by the tooltip.

**Comment by mikedilger** [comment]
If I delete entries from my mute list and pulldown, they come back.  So maybe this is a problem with how other clients create mute list entries.  Maybe they used a pubkey prefix? Maybe I'm wrongly counting tags in the newer mute list event?  I would have to see the event to know.

**Comment by badonyx** [comment]
On my laptop that I normally use with gossip it shows 8 remote and 1 local. On my desktop that I don't use gossip with as much it just says `People who are Muted (0)`. So you are probably right that the event is malformed or something.

**Comment by mikedilger** [comment]
I've pulled down the event (id  = c2e127b7b81888118f6143508bcfd46ed7f7e86d51fcb82e375fc88e86f28377) having 8 entries, and it looks (by eyeball) good to me.

So I'm stumped now. Because it works fine for my mute lists.

**Comment by mikedilger** [comment]
Ok I setup gossip with your pubkey and I'm debugging

**Comment by mikedilger** [comment]
fixed on unstable.
