### ISSUE TITLE
[Feature Request] Change Font Size and Scale

### ISSUE THREAD

**Issue by crimsonleaf363** [mikedilger/gossip#546]
### **Problem**

- The font size and scale appears to be relatively small.

### **Proposed Solution**

- Allow the font size and scale to be adjusted for improved customizability.

**Comment by mikedilger** [comment]
It is possible for us to code scaling of the font independent of the zoom level, but most people have found overriding the DPI does what they wanted.  Let us know if you tried that and it's not to your liking.  In settings > ui, click "Override DPI", slide, it, apply now (without saving), and when you like it, save the settings.  If that isn't good enough for you, we can leave this open and consider scaling fonts independently of other window attributes.

**Comment by crimsonleaf363** [comment]
> It is possible for us to code scaling of the font independent of the zoom level, but most people have found overriding the DPI does what they wanted. Let us know if you tried that and it's not to your liking. In settings > ui, click "Override DPI", slide, it, apply now (without saving), and when you like it, save the settings. If that isn't good enough for you, we can leave this open and consider scaling fonts independently of other window attributes.

Problem solved.
