### ISSUE TITLE
Relays: "Remove from personal list" also marks it as hidden

### ISSUE THREAD

**Issue by badonyx** [mikedilger/gossip#550]
Since "Hide relay" is a separate option this should not also hide the relay.

My expectation would be that it unsets the read/write/discover options that make it show up in the personal list.

**Comment by bu5hm4nn** [comment]
Yes that was a bug, I fixed it together with something else and forgot to mention the fix. 5f20999013d390915aebaebaacb08c1f0152da28
I has been merged to unstable, so please test again from unstable.
