### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by erlend-sh** [mikedilger/gossip#56]
So far only desktop is planned:

> Portable to Linux (Debian, RedHat, Arch) MacOS and Windows

But seeing as you’re using Tauri, which recently announced mobile support, will you consider mobile support?

**Comment by mikedilger** [comment]
If I stick with tauri (which has had a serious performance issue for a long time now), then yes, absolutely.  I heard that announcement too.

**Comment by mikedilger** [comment]
We didn't stick with tauri. So this won't be possible.  There are many clients to choose from now.
