### ISSUE TITLE
Tagging contacts

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#566]
Following https://github.com/mikedilger/gossip/issues/512

This issue is about contacts tagging, its interface design and the interaction.

## Basic tagging

The user initializes the contact search with the "@" character; the results are shown in a popover:
He can move on the results using the tab / shift-tab or the up / down arrows keys. The desired contact can be selected with the enter key, or simply with a space if it has been fully typed.
The user can also use the pointer to scroll the list and select a contact.

![image](https://github.com/mikedilger/gossip/assets/89577423/c0dc0ce9-265f-426b-bbfe-d22a61725ccb)

The popover pointer is linked to the "@" so it is fixed during the typing
It is shown below the current line, so all the written text is visible.
The list should always show the followed contacts first, regardless of the weight of the results.

## Followed only filter

![image](https://github.com/mikedilger/gossip/assets/89577423/cd5ec280-eddf-4da0-90e2-cc791e517875)

An optional toggle permits to filter out not followed contacts (so possibly impersonators), to be sure to tag only know people.
The default status of the filter should be active and it should be remembered, at least for the current session (until the app is restarted).
With the filter the list should can show the results with they proper weight, e.g. an not followed user that has name <typed_string> come before a followed one with the same string in the NIP-05.

## Contact inspection

![image](https://github.com/mikedilger/gossip/assets/89577423/eaa1d60f-ede3-4e01-9d56-45221cfb9317)

After the contact is mentioned the "@" is hidden (outside nostr it is usually also connected with the concept of a unique username, which is not present on nostr).
On hover the popover's pointer is placed in the middle of the center of the user's name.
The popover contains the short npub and display_name and expose two links to see the full profile and to unlink the mention.
The popover closes itself after 1000ms the mouse exit the contact + popover area.

## Popover position near the edges

![image](https://github.com/mikedilger/gossip/assets/89577423/51ec67ed-5308-42ac-9ffa-840881b0601b)
Popover position with no space on the bottom
<br/>

![image](https://github.com/mikedilger/gossip/assets/89577423/3e4a4e3c-5840-4ba6-978d-e22896b30265)
Popover near the right edge
<br/>

![image](https://github.com/mikedilger/gossip/assets/89577423/2a90d1f8-3c49-4105-a3ba-7beda4c82385)
Popover near the bottom right edge

**Comment by dtonon** [comment]
Oh sorry I missed publishing this part.
Currently, doing background inversion/variation with egui is a mess; then the highlighted row should have an increased contrast, and this means the need to manage different color variations for light and dark theme.
I would try with a simpler approach, an indicator on the right. What do you think?

![image](https://github.com/mikedilger/gossip/assets/89577423/677f4d57-40dd-4af7-ae0d-c6191b69e975)

**Comment by bu5hm4nn** [comment]
To be completely honest I prefer the light background and using accent color as selection the way it is now. The design you currently described here has too much color for me.

**Comment by dtonon** [comment]
@bu5hm4nn I tried to harmonize the popover design, but actually this specific popover has a rather high display frequency, so maybe a softer background is better. I will try the light design and post an update here.

**Comment by dtonon** [comment]
@bu5hm4nn you are right, I like more the neutral version!
I would make the popover a little darker than the textarea, with a softer and more rounded at the corners shadow. In dark mode the shadow is actually a glow effect (white).

![image](https://github.com/mikedilger/gossip/assets/89577423/a6a8af11-383d-4463-87cd-8a7816d5a71a)
![image](https://github.com/mikedilger/gossip/assets/89577423/d6a06474-f517-4977-8609-a34fc23af98b)

![image](https://github.com/mikedilger/gossip/assets/89577423/49029e52-2038-4daf-8f48-53a3883d2da6)
![image](https://github.com/mikedilger/gossip/assets/89577423/8582572d-c6cc-4fe3-919f-a1a420876ca0)

**Comment by dtonon** [comment]
@bu5hm4nn a nasty bug: when the user has some emoji at the end the name is not linked, and any successive tagging does not work:

<img width="541" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/d4b4a2ca-cea0-4891-acae-0cd31a5ba7a5">

**Comment by bu5hm4nn** [comment]
If you look at the "raw" message with the raw button below the edit field, it should be replaced correctly.

**Comment by bu5hm4nn** [comment]
@dtonon Give this fix a try: https://github.com/bu5hm4nn/gossip/tree/tagging-fix-space-in-name

**Comment by dtonon** [comment]
I see that the bug has been fixed and merged in unstable 👍

What about the final design? Can you tweak it following the mockups?
Honestly it's not a priority, if it's fast enough it's just to close this part.

**Comment by bu5hm4nn** [comment]
Leave it open, I'll get back to it. The tricky thing in egui is you don't usually know how large something is unless you pre render it, etc. But maybe we can find some sensible rules like dividing the window in 4 quadrants and just deciding (above, left), (above, right), (below, left), (below, right) based on which quadrant the start point is in.

**Comment by mikedilger** [comment]
> The tricky thing in egui is you don't usually know how large something is unless you pre render it

Yes this is the tricky thing. I cannot center a line of text that is made up of multiple widgets of dynamic unknown widths. Several options come to mind:
1) Render it aligned to the left. After rendering it we could measure it, set a variable, and next frame center it by adding calculated space first. It would render wrong for 1 frame though.
2) Render it offscreen, measure it, and then copy the pixels into place. This is IMHO a good solution, but it is uncharted territory.
3) Keep things simple and just work around this limitation by designing the UI to not have such situations come up.

**Comment by bu5hm4nn** [comment]
@dtonon can this be closed?
