### ISSUE TITLE
Magic thingymabob on OS X

### ISSUE THREAD

**Issue by freQniK** [mikedilger/gossip#573]
```shell
xattr -cr /Applications/Gossip.app
```

**Comment by mikedilger** [comment]
In the file README.macos.txt in the distribution it has something slightly different.  Can you resolve the differences?

````
% sudo xattr -rd com.apple.quarantine /Applications/Gossip.app
````

What does the `-c` do?   I presume the `-d com.apple.quarantine` limits the scope of the operation.

**Comment by mikedilger** [comment]
I looked it up.  `-d` just deletes the one attribute. I'll leave it as is. Thanks.
