### ISSUE TITLE
something broke compiling eda3ad1 on macOS intel

### ISSUE THREAD

**Issue by pjv** [mikedilger/gossip#579]
issued my “regossip” script which i do whenever there are new commits in master to recompile and launch and here’s what i see in the terminal after all the compiles are done:

````
2023-12-01T19:21:16.107699Z  INFO gossip-lib/src/filter.rs:30: No spam filter: No such file or directory (os error 2)
2023-12-01T19:21:16.168007Z ERROR gossip-lib/src/overlord/mod.rs:108: HTTP (reqwest) error: builder error: The Trust Settings Record was corrupted.
2023-12-01T19:21:16.176086Z  INFO gossip-lib/src/overlord/mod.rs:116: LMDB synced.
2023-12-01T19:21:16.176139Z  INFO gossip-lib/src/overlord/mod.rs:134: Overlord waiting for minions to all shutdown
2023-12-01T19:21:16.176150Z  INFO gossip-lib/src/overlord/mod.rs:156: Overlord confirms all minions have shutdown
2023-12-01T19:21:16.314727Z  INFO gossip-bin/src/ui/mod.rs:473: DPI (native): 144
2023-12-01T19:21:16.519196Z  INFO gossip-lib/src/lib.rs:167: LMDB synced.
````

Edit: sorry, meant to also say that after the above, no gossip.

(I checked out 361b3d7 and re-compiled and gossiping again)

**Comment by mikedilger** [comment]
Could be d130415a11b4bdcb2aad77b7587f2b1e576fbae0

"The Trust Settings Record was corrupted" may indicate that the root certificates on your machine are broken somehow.

You can use newer code if you compile with the "--no-default-features --features=rustls-tls" and any other features you want.

**Comment by pjv** [comment]
So, I finally had a chance to monkey with this and using `—features=rustls-tls` (which I can see from the commit you linked was the default before) throws the same error.

But, when I switched to `--features=native-tls` then gossip (@ [e016731](https://github.com/mikedilger/gossip/commit/e0167310220aa7904cef8bb5454ef106cb3eecea)) compiled and ran fine with no such error.

I wonder if there is something weird on my setup or if this is common to macos in general. I’m currently running Ventura 13.6.1 (22G313).

**Comment by mikedilger** [comment]
I think I messed up. Pull master and try again.

**Comment by pjv** [comment]
Still:

`2023-12-06T18:32:46.168647Z ERROR gossip-lib/src/overlord/mod.rs:108: HTTP (reqwest) error: builder error: The Trust Settings Record was corrupted.`

**Comment by pjv** [comment]
@mikedilger thanks, i’ll look through my keychain and see if i can find out what the issue is. I have my own self-generated and self-signed root certs in there alongside the native Apple ones, so maybe that’s the issue. I’ll report back what I find if I can track it down.

**Comment by mikedilger** [comment]
Well, SSL is complex and historically buggy and the guys that did the rustls code did a pretty good job making it as secure as possible, and they describe this pretty well in this manual https://docs.rs/rustls/latest/rustls/manual/index.html which is fun reading.  So if you don't need your local certificates for gossip itself, I would just use rustls-tls (the way it used to be).  But if you need to support self-signed CAs for .onion site relays or something, then go the other way with native-tls and hope there aren't any more bugs in the more native TLS stacks. It's up to you.

I'll close this now. Reopen if it is still not working.

**Comment by mikedilger** [comment]
I don't understand why. It should be doing webpki roots exclusively under that option.  I hate when I don't understand something. But at least there is 1 option for you.
