### ISSUE TITLE
PersonList related UI work

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#580]
- [ ] Person page: spruce up how you add/remove them from lists (follow dtonon's design)
- [ ] Prompt for login and Wait for migration pages could use styling.
- [ ] Feeds Menu:  This can get too long. We need to work out how to handle that

**Comment by dtonon** [comment]
@mikedilger if you prefer you can move the checklist to the main issue: https://github.com/mikedilger/gossip/issues/552

**Comment by mikedilger** [comment]
moved.
