### ISSUE TITLE
Improve the raw mode UX

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#587]
After pressing the Raw icon, nothing changes and the compose area freezes. 

Tested on 75236a73

**Comment by mikedilger** [comment]
Where did this "Raw content preview" come from? I don't remember doing that.

**Comment by mikedilger** [comment]
4b144e039fa17213564c14c614c7a9e4fccc3cff

**Comment by mikedilger** [comment]
Does it work? While you are in that preview mode you can't type. Maybe we can put a red border around the box or something.

**Comment by dtonon** [comment]
@mikedilger yes it works, I was confused by the UX.
We are reviewing it here: https://github.com/mikedilger/gossip/pull/593

@bu5hm4nn explained me that editing in raw mode is a problem, because "_I would need to reverse-calculate the replacement tags if the user edits them. It would be a lot of work._"

**Comment by dtonon** [comment]
Mockups:

![Image](https://github.com/mikedilger/gossip/assets/89577423/5d2ede9f-12ae-4751-ae0b-0257426084dc)

![Image](https://github.com/mikedilger/gossip/assets/89577423/2106aee7-7191-4950-8b2d-30fb96549f75)

![Image](https://github.com/mikedilger/gossip/assets/89577423/f6895ae2-d026-44c4-8e31-5092a86b5f73)

**Comment by mikedilger** [comment]
This appears to me to be done.
