### ISSUE TITLE
Shouldn't allow users to like their own posts

### ISSUE THREAD

**Issue by Nate-Levin** [mikedilger/gossip#59]
Seems like a weird feature in other social media clients

**Comment by mikedilger** [comment]
I agree.  We also need to make sure one public key can't create many like events (of course we cannot detect sock puppets, but we should at least do this).

**Comment by mikedilger** [comment]
I've added code to make sure only 1 reaction per person is counted (per symbol).   That is enough for 0.4.  The original issue is still open.

**Comment by mikedilger** [comment]
fixed in 62bc46e30703928706609197602c8f02853f2339
