### ISSUE TITLE
Review sidebar menu: reordering, spacing and labelling

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#594]
- [x] Reorder the items (e.g. _Search_ below _Private chats_)
- [x] Add a space before _People Lists_
- [ ] Rename Inbox in Notifications

![Image](https://github.com/mikedilger/gossip/assets/89577423/785b0675-756c-4731-bbe8-ef4fc37e564a)

**Comment by dtonon** [comment]
[ Reserved for the review checklists ]

**Comment by dtonon** [comment]
@mikedilger @bu5hm4nn do you agree to rename _Inbox_ in _Notifications_?
I think _Notifications_ it is more standard, and a longer text is more usable in the menu.

**Comment by mikedilger** [comment]
My initial reaction was that I didn't like Notifications compared to Inbox. But I dunno.

**Comment by dtonon** [comment]
I don't have really strong opinions about that, but _Inbox_ remembers me the email, while _Notifications_ is more generic and future-proof.

**Comment by dtonon** [comment]
One more think: if we implement "More (X) ..." after the preferred people lists I would keep this always opened. It is the natural point of focus, there is no need to require another click to open the sub-tree.

**Comment by mikedilger** [comment]
So should we even have a Feeds> title or just list them all and keep it open?

**Comment by dtonon** [comment]
Yes, it is a possibility. I don't dislike the gray title, but I have not strong opinion on it.

**Comment by bu5hm4nn** [comment]
I think "Inbox" is ok for the time being because it actually is only messages that are there right now.
Once we implement actual notifications (like, XY followed you, XY added you to list YZ, XY mentioned you, etc) then it makes sense to have a "Notification" item.

**Comment by mikedilger** [comment]
We will leave inbox until such time that we actually have an unread notification count indicator. Then we will rename it to notifications.

The Feeds menu is now excluded from the auto-folding.  The other menus still auto-fold.
I added the count to "More (6) ...".
