### ISSUE TITLE
Wizard: "pubkey only" mode does not find kind 3

### ISSUE THREAD

**Issue by bu5hm4nn** [mikedilger/gossip#605]
I deleted the gossip data dir to start over and followed the wizard in pubkey only mode.
Even though I have two relays that both are confirmed to have my kind:3 (relay.damus.io and purplepag.es) when I navigate to People List: Following it tells me it cannot find my list.
<img width="912" alt="Screenshot 2023-12-22 at 11 24 13" src="https://github.com/mikedilger/gossip/assets/3328670/d389f16f-8236-4372-85e3-fa5c5555cf2c">

**Comment by mikedilger** [comment]
Ok I've tried this a number of times and it finds my lists just fine.  I did fix a related problem where it didn't import a list if there was any encrypted contents.  Now it imports as much as it can.

**Comment by mikedilger** [comment]
Ok. I'll look again when I have a chance.

**Comment by bu5hm4nn** [comment]
@mikedilger I looked into it. My suggestion would be to not let people exit the wizard early, but just to choose to skip to the next step. Otherwise we have many paths we need to handle. thoughts?

**Comment by bu5hm4nn** [comment]
Fixed with merge
