### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#619]
I want to be able to bookmark posts. And then go to my 'bookmarked' feed.

**Comment by bu5hm4nn** [comment]
Aren't bookmarks just a list but with 'e' instead of 'p' tags?

**Comment by mikedilger** [comment]
Yeah. We don't store lists as events, we break them down. So we need storage for a set of bookmarks, and to use the slightly different kind 10003 for them (or 30003 if we want multiple bookmark lists, which I'm not sure about, I barely even want bookmarks).

**Comment by mikedilger** [comment]
Work progressing on bookmarks branch.  I'm not sure how much to support.

- [x] Add Feed: It was very easy to add a bookmarks feed, and populate it from a 10003 event.
- [ ] Separate Storage: If we don't have separate storage, we start to experience the same kind of clobber issues that other clients do. But it is far simpler to not have separate storage so we have started that way.
- [ ] Add/Remove: It will be easy to add a menu item that adds (or removes) a bookmark, and then triggers a publishing of a newer bookmarks event, but as of now there is no way to populate or edit the bookmarks
- [x] Kind 10003: for a single list is what we are reading right now.
- [ ] Kind 30003: If we want multiple bookmark lists, we should use 30003 with d tags
- [x] "e" for ids (kind:1 notes but IMHO any other kind too)
- [ ] "a" (kind:30023 articles)
- [ ] "t" (hashtags)
- [ ] "r" (URLs)

**Comment by mikedilger** [comment]
I'm moving the parts we didn't do to a new issue #826 and closing this one.
