### ISSUE TITLE
Discovery relays - suggest, don't force

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#627]
Right now we shove purplepag.es in as discovery. We need to do better.

**Comment by bu5hm4nn** [comment]
Why don't we just search all the relays that are in the list of popular relays that we have in the app?

**Comment by mikedilger** [comment]
I just removed the force. It adds it initially if you have none, but if you delete it, now it stays deleted.

I also bumped up the recommendation to have 4 discovery relays.

**Comment by e99243506bigplay** [comment]
Found this to discover nostr relays: https://api.nostr.watch/
Now I would like for connect like 300 relays to make sure I wont be missed anything.
