### ISSUE TITLE
Stop the video when it scrolls out of the viewport or the view is changed

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#641]
Currently if the user scroll past a video it keeps playing; same if he changes view, e.g. enter/exit a thread or more to another section using the sidebar menu. The video should pause.

**Comment by mikedilger** [comment]
I think we should remove ffmpeg videos. I have had no end to problems with them. Compile problems. Crashing problems. Etc.  It is cool no doubt, but it is our most fragile and dangerous code, our Achilles heel.

**Comment by dtonon** [comment]
Videos gave problems to me, too.

Of course they are an important media type, users usually expect them, or at least a cover to click.
Hard choice, but I cannot say nothing about this sort of technical matter.
