### ISSUE TITLE
Does the binary gossip need to stay in the project's directory?

### ISSUE THREAD

**Issue by whileunless** [mikedilger/gossip#650]
After building it I moved `gossip` from `gossip/target/release/` to  `/usr/local/bin` leaving other files in the former. At first glance it seems to work, and the things that do not seem work may be due to the fact that I am newbie to `nostr`. 

Will I miss any functionality by running `gossip` from `/usr/local/bin`?

**Comment by mikedilger** [comment]
The gossip binary is fully self-contained, including fonts.  It uses a data directory defined by https://docs.rs/dirs/latest/dirs/fn.data_dir.html at runtime.  You can even delete the rest of the stuff, all the source code, or move it to another computer of the same architecture and with the same library versions that ldd returns and it will still work.  If you move it to another computer and want your data, you have to move your data directory too.

Cheers.
