### ISSUE TITLE
[Feature request] allow entering numbers besides slider via the keyboard.

### ISSUE THREAD

**Issue by dreirund** [mikedilger/gossip#654]
In the settings dialogue, I can not enter the numbers (e.g. for "*Override DPI*") numerically. I _only_ can use the slider.

Entereing numbers is more accurate.

I fail to set DPI to 96. I can only get 95 and 97 using the slider, and it is a hassle to set a specific number (I easily slide beyond).

I hereby request the feature that in the number field besides the sliders the number can be entered via the keyboard.

Regards!

**Comment by mikedilger** [comment]
If your window was working properly you would be able to enter numbers. I can enter numbers.  Click on the number, it highlights, hit backspace and type in a new number.  If that isn't working, then this is probably the same bug as the other issue.

**Comment by mikedilger** [comment]
Closing as #655 is the likely problem.

**Comment by dreirund** [comment]
> *If your window was working properly you would be able to enter numbers. I can enter numbers. Click on the number, it highlights, hit backspace and type in a new number.*

Thanks, here it was my fault: Since a mouseover over the number field was changing the number when I clicked and moved the mouse, it did not come into my mind that there is another functionality there: UI telling me "move the mouse here" was stopping me making me think that I can interact with the same element in another way.

**Comment by mikedilger** [comment]
I agree it is a confusing UX. But it is the default widget in the egui toolkit for this kind of editor.
