### ISSUE TITLE
[Feature request] allow window to be resized.

### ISSUE THREAD

**Issue by dreirund** [mikedilger/gossip#655]
I am in the settings dialogue and the page goes beyond my screen.

I cannot resize or maximise the window.

I hereby issue the feature request to make the window resizeable, and that scrollbars automatically appear if there is more content outside of the visible area.

**Comment by mikedilger** [comment]
If your window goes outside of your screen, that's a feature of your windowing system (wayland, X, xfce, gnome, or whatever). We can't scrollbar in that circumstance.

But we can 'maximize' which would fit the window exactly to your screen, in which case scrollbars would appear within the window.  Maybe we can map that to F11 like browsers do.

**Comment by dreirund** [comment]
On Wed, 28 Feb 2024 10:09:22 -0800, Michael Dilger
***@***.***> wrote:

> But we can 'maximize' which would fit the window exactly to your
> screen, in which case scrollbars would appear within the window.
> Maybe we can map that to F11 like browsers do.

Acutally, window-manager "maximise" (clicking the "maximise" button)
does _not_ work, nor does manual resizing with the mouse.

Seems the window forces a fixed size.

I am using X.org with xfwm4 window manager.

**Comment by dreirund** [comment]
P.S.: "Fullscreen" does work, but this will also hide my taskbar and
such. "Maximise" and "resize" does not work.

**Comment by dreirund** [comment]
P.S. 2:

When "Fullscreen", there is still content outside of the visible area
and no scrollbars.

**Comment by mikedilger** [comment]
Ok something is very wrong with gossip on your system if you can't resize the window.

**Comment by mikedilger** [comment]
Let me pull in @bu5hm4nn , we upgraded our rendering library `egui` recently and maybe he knows something.

**Comment by dreirund** [comment]
> Ok something is very wrong with gossip on your system if you can't
> resize the window.

"help" -> "about": Version 0.9.0

I for now use the precompiled binary from
https://github.com/mikedilger/gossip/releases/download/v0.9.0/gossip_0.9.0_amd64.deb, installed via this AUR package: https://aur.archlinux.org/packages/gossip-bin

**Comment by mikedilger** [comment]
Also, there are some pages in the settings area that indeed need scrollbars and don't have them. I'll make a separate issue for that, and we will keep this issue focused on why your window isn't manageable.

**Comment by bu5hm4nn** [comment]
@dreirund can you open gossip from a terminal and see what the log says about the DPI setting used?

**Comment by dreirund** [comment]
I now compiled the latest git checkout from the `master` branch, still
not able to resize the window, and DPI is 168.

**Comment by dreirund** [comment]
Now it "magically" worked once.

I did quit and restart, now it does not work again; I can only make the window larger, not smaller.

(I am on a 1920x1200 resolution screen, and the window is larger than the screen, even after manually setting the DPI lower.)

The one time when making the window smaller worked I got overlapping text at the lower left when the window is so small that the menu reaches to the bottom:

---

![image](https://github.com/mikedilger/gossip/assets/1590519/eefdb3ad-2407-49f7-bc6c-9345ff689c15)

**Comment by mikedilger** [comment]
I have moved the "Reset Native" button to the next row.  See if you can't push it.

**Comment by mikedilger** [comment]
I also added F11 to maximize the screen (although that won't help you shrink the window).

**Comment by mikedilger** [comment]
If my window gets larger than the screen I can find an edge and drag it smaller, and eventually make the window smaller again.

**Comment by dreirund** [comment]
> I have moved the "Reset Native" button to the next row. See if you can't push it.

In my original window size I can see it. That screenshot was from the
one case where I actually was able to make the window smaller.

And I see no difference. (Should I use the "unstable" branch again?)

**Comment by bu5hm4nn** [comment]
@mikedilger we should add a `--dpi=` override commandline to help people rescue their session

**Comment by bu5hm4nn** [comment]
@dreirund Is it working for you now? I set up a test VM with Archlinux and xfce4. Resizing and the buttons work fine for me.

https://github.com/mikedilger/gossip/assets/3328670/38081d74-c983-4364-a97a-cbcc3469b8dc

**Comment by dreirund** [comment]
> @dreirund Is it working for you now? I set up a test VM with
> Archlinux and xfce4. Resizing and the buttons work fine for me.

Should I try "master" branch or "unstable" branch?

**Comment by bu5hm4nn** [comment]
> Should I try "master" branch or "unstable" branch?
Try unstable

**Comment by dreirund** [comment]
On Thu, 29 Feb 2024 18:05:07 -0800, bu5hm4nn ***@***.***>
wrote:

> @dreirund Is it working for you now? I set up a test VM with
> Archlinux and xfce4. Resizing and the buttons work fine for me.

I can only enlarge the window, not shrink it.

And I still get unusual high dpi.

`xdpyinfo` says the default:

`  resolution:    96x96 dots per inch`

But somehow `gossip` calculates it's own value.

**Comment by mikedilger** [comment]
Remove `~/.local/share/gossip/app.ron`

**Comment by dreirund** [comment]
> ~/.local/share/gossip/app.ron

Does not help.

Minimal window size still too large.

Note that in about 1/4 of the cases (individual sessions where I
startgossip and quit it) I can make the window smaller, in the other
cases only larger.

`xwininfo` says about the window:

```
xwininfo: Window id: 0x5c00003 "gossip"

  Absolute upper-left X:  -138
  Absolute upper-left Y:  -424
  Relative upper-left X:  1
  Relative upper-left Y:  11
  Width: 1867
  Height: 1400
  Depth: 24
  Visual: 0x3ee
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x5c00002 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +-138+-424  -191+-424  -191-224  +-138-224
  -geometry 1867x1400+-139+-435
```

(so 1867 x 1400 is it's minimum size)

**Comment by dreirund** [comment]
(Note that I use plain xfwm4, no full-fledged desktop environment.

`XDG_` environment variables (username I have censored):

```
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=xinitrc
XDG_SESSION_TYPE=x11
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/<username>
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_VTNR=12
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
```
)

**Comment by bu5hm4nn** [comment]
egui uses `xrandr` on X11 to calculate DPI from physical screen size and resolution.
We set a minimum window size of 800 x 600, but this gets scaled by the DPI setting. We do offer the option of overriding DPI which gets saved to your gossip settings, but you would have to reach the setting.
I'm not sure how to further help you if I can't replicate the behavior aside from adding a `--dpi` option.

**Comment by bu5hm4nn** [comment]
@dreirund I just added the `dpi` command on the `unstable` branch. The easiest way to pass it in is with the `./run.sh` script in the gossip source dir, just do `./run.sh dpi 72` and it will store that in the settings. Then start gossip normally without the parameter.

**Comment by bu5hm4nn** [comment]
I will assume the `dpi` command can solve for this issue

**Comment by dreirund** [comment]
Ahoj,

now I could test, and there are still design issues of different kind:

> egui uses `xrandr` on X11 to calculate DPI from physical screen size
> and resolution.

It _should not_ calculate it by it's own.

X.org has a DPI notion of it's own, which by default is calculated from
(given or assumed) screen size and resultion, and which can be
overridden by the user, and it should take directly the DPI value that
`xrandr` is aware of and not do it's own stuff:  
If the user sets a DPI setting X.org-wide/ via `xrandr`, this is
intentional, and should be used, and you should not try to calculate
something on your own:

`xrandr --dpi` sets the DPI to use, `xdpyinfo` (and maybe some library
calls) to query the actual setting:

```
[...]
screen #0:
  dimensions:    1920x1200 pixels (508x317 millimeters)
  resolution:    96x96 dots per inch
[...]
```

Please use the DPI setting that is set and don't do your own stuff here.


> I just added the `dpi` command on the `unstable` branch. [..] it will
> store that in the settings. Then start gossip normally without the parameter.

OK, that is also a way to do it.

But wouldn't an option `--dpi <DPI>` for one-time overrde, `--save-dpi <DPI>`
for starting with override _and_ permanently saving the override the more "Unix-tool-like" way?



I rebuilt and did run `gossip dpi 72` and then launched `gossip`.

It successfully is at DPI 72:  
```
2024-03-10T10:53:22.683852Z  INFO gossip-lib/src/filter.rs:30: No spam filter: No such file or directory (os error 2)
2024-03-10T10:53:22.775292Z  INFO /tmp/makepkg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/x11/window.rs:189: Guessed window scale factor: 2.3333333333333335    
2024-03-10T10:53:22.794396Z  INFO gossip-bin/src/ui/mod.rs:724: DPI (overridden): 72
```

It still prints out a `Guessed window scale factor: 2.3333333333333335`.

Regards!

**Comment by bu5hm4nn** [comment]
Hey @dreirund.
We are already running at max capacity trying to keep up with new nostr features and improving usability. We cannot chase bugs in other libraries. The dependency on xrandr is in https://github.com/rust-windowing/winit which is used by https://github.com/emilk/egui which is the GUI library that we use. The only thing we can offer is a scaling override that we feed back into the app as a workaround, that's what the `--dpi` command now does.

**Comment by dreirund** [comment]
OK. So just keep going with your main development stuff and `egui` and
let's regard egui as some -- well -- fancy shiny crippled stuff ;-)

Regards and props for your work!
