### ISSUE TITLE
Settings area scroll

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#658]
Settings aren't scrollable, and in smaller windows they run off the edge and can't be accessed.

**Comment by bu5hm4nn** [comment]
We'll put every page into a scrollarea with on-demand scroll bar visibility

**Comment by bu5hm4nn** [comment]
Completed in a81f4ad8324d9b6859a0b7dc42f6c6064668121f

**Comment by bu5hm4nn** [comment]
Done in a81f4ad8324d9b6859a0b7dc42f6c6064668121f
