### ISSUE TITLE
ffmpeg sound

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#670]
For some people, when we upgraded egui, ffmpeg videos lost sound (although it works for me).

nostr:nevent1qqsqqqqzk3mv0fexer9vh33pqcnqqd3wxthzv5l4zgfmk7kd6gajrtcpzpmhxue69uhkztnwdaejumr0dshszrnhwden5te0dehhxtnvdakz7qgnwaehxw309ahkvenrdpskjm3wwp6kytc5kxelx

Someone else also mentioned this before but I can't find it now.

**Comment by bu5hm4nn** [comment]
I replied to them, let's see if installing `libsdl2-dev` fixes it.
<img width="755" alt="Screenshot 2024-03-06 at 14 59 54" src="https://github.com/mikedilger/gossip/assets/3328670/72c382f3-30dd-4772-9d42-886c9a5affc7">

https://njump.me/nevent1qqsy3lfzhljn3mju2xjpln3h9rtlld72nk80s4rved9jaz35grscpugpzdmhxue69uhk7enxvd5xz6tw9ec82c30qyv8wumn8ghj7un9d3shjtndv968g7tzwvhxcmmv9uq3wamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet59umhfx7u

**Comment by bu5hm4nn** [comment]
Resolved with install of `libsdl2-dev`.

<img width="675" alt="Screenshot 2024-03-06 at 19 30 41" src="https://github.com/mikedilger/gossip/assets/3328670/11555616-0ef9-4683-8f82-1afb6a4d5c0b">

https://njump.me/nevent1qqsqqqqpr6jv848mxywrxdhn4wu47pq2he8ae8mp4runax0umn974wcpzpmhxue69uhkztnwdaejumr0dshszenhwden5te0ve5kcar9wghxummnw3ezuamfdejj7mnsw43rz6rvwyunx6nyw34kveej89snsuehvech57n6dquryufnwp4kxv3swfu82cmhws6xwetgxejn2dnhdvehjvn30pj85dthvulkyun0v9jxxctnws7hgun4v5qsuamnwvaz7tmwdaejumr0dshsrxqyke
