### ISSUE TITLE
Adjusting DPI too high makes form controls inaccessible

### ISSUE THREAD

**Issue by zberwaldt** [mikedilger/gossip#680]
Adjusting the DPI too high makes the form controls inaccessible on some pages in the setup wizard. In order to access the controls I had to go adjust my monitor settings for max resolution. I just use whatever windows recommends to use, so fortunately I was able to increase it.

OS: Windows 10
Gossip Version: 9.0.0

![image](https://github.com/mikedilger/gossip/assets/17715430/a608bbba-da1e-4c8f-a5c2-df3f3d021153)

**Comment by mikedilger** [comment]
This page needs a scroll area.  @bu5hm4nn

**Comment by bu5hm4nn** [comment]
<img width="912" alt="Screenshot 2024-03-14 at 17 39 50" src="https://github.com/mikedilger/gossip/assets/3328670/0f8778a8-0a57-4605-9326-e7e8da16d0ee">
Complete with 7a02bf8b008c2bbacc17159264cb7c173e8149f0
