### ISSUE TITLE
scrolling is un-necessarily slow?

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#691]
Is there a setting in egui to increase scroll speed?  I feel like when I use the mouse-wheel in gossip, the feed moves so slow compared to every other app I use..  And I don't think it's a performance thing, it's probably just a configuration for how far a wheel can make the page jump.

Just a thought.  It would make gossip feel really nice.  I notice apps that let me wheel scroll fast, give you that good feeling, and ones that are slow, it's like pushing molasses around (like something is wrong with the mouse).

PV!

**Comment by jeremyd** [comment]
I turned off inertial scrolling, and turned up mouse speed to 2.0.  Maybe just need to turn it up even farther (but the menu setting doesn't go farther than 2)

**Comment by jeremyd** [comment]
I know it can go faster in general and is likely just limited by the interaction w/the mouse driver because it is very fast when using a touch screen and feels quite normal that way.

**Comment by mikedilger** [comment]
I guess different systems are different.  Gossip scrolls for me as fast as firefox browser does, and smoother.  It is hard for me to see how it could be better.  Which says to me that you are not getting the same experience that I am.

**Comment by jeremyd** [comment]
ah, yes, haha, i was wondering if this is another linux thing :)  wayland with it's scroll wheel support is something I remember being a saga back in the early wayland days (but of course all fixed now after multiple wayland fixes).. maybe i'll splunk around into the wayland egui stuff in the mouse sections..

**Comment by bu5hm4nn** [comment]
What do you guys have set for FPS in gossip? Inertial scrolling is calculated per-frame so the calculations can be off for lower FPS.

**Comment by jeremyd** [comment]
I just have it set to the default (12 fps)

**Comment by mikedilger** [comment]
> What do you guys have set for FPS in gossip? Inertial scrolling is calculated per-frame so the calculations can be off for lower FPS.

Interesting. The scroll speed doesn't depend on FPS, and the smooth scrolling happens smoothly even with very low FPS... which means the FPS setting isn't actually being totally honored.  But don't let me derail this issue, my observation is tangential.

**Comment by bu5hm4nn** [comment]
> the FPS setting isn't actually being totally honored

In egui, if any part of the code calls `Context::request_repaint()` then there will be a repaint on the next screen refresh. Essentially it will then run at the speed of the screen refresh rate (or possibly faster). At some point we should probably audit those calls and see if we can optimize it to avoid constantly repainting.

**Comment by bu5hm4nn** [comment]
> I just have it set to the default (12 fps)

@jeremyd Have you tried maxing the FPS and does it make a difference to scrolling? Is this still an issue?

**Comment by jeremyd** [comment]
Hi @bu5hm4nn  Looks like setting FPS has no observable change.  I did set mouse acceleration to 2.0 and inertial scrolling to OFF, and it's *almost as fast as scrolling in chromium but not quite.. Would it be easy to allow up to 3.0 for acceleration?  That might do it..
