### ISSUE TITLE
I broke the UI

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#695]
I just messed up the UI by adding some things that don't line up.  It is just the visual pleasantness that I broke, but that's bad right?

@bu5hm4nn can you clean up my mess?  This commit on unstable: 724785a39ddf101000a9ecfc348771ab9d566058

I want to show when a relay list is out of date and give them a button to trigger a fetch of the relay list, as a fallback for when gossip is buggy or not working properly, at least until we are pretty sure we have fixed all the bugs related to this. Making sure people can get relay lists is important now.

**Comment by bu5hm4nn** [comment]
Should be fixed?

**Comment by mikedilger** [comment]
Yeah I saw earlier today, looked fixed.
