### ISSUE TITLE
Empty kind:6 Repost

### ISSUE THREAD

**Issue by bu5hm4nn** [mikedilger/gossip#701]
This is probably bad behavior of another client.

<img width="586" alt="Screenshot 2024-03-28 at 20 31 48" src="https://github.com/mikedilger/gossip/assets/3328670/1eb78126-fc92-4114-b265-e6b6b8c3a332">

```json
{
  "id": "72d57f8c5ef95f12b9fbcb6ab4aa0fdcd2cd1580773f14b3aa8eb1fa3be4006e",
  "pubkey": "6389be6491e7b693e9f368ece88fcd145f07c068d2c1bbae4247b9b5ef439d32",
  "created_at": 1711679280,
  "kind": 6,
  "sig": "fa5f4c8f6a7f3b1aacb0746ab9878b450ffad908d9cfe75180b97fa05f3db4bdcf78cd3bb92ea09979f2790a620711b9c30ee1f358f0d7158147a6ad429d394e",
  "content": "",
  "tags": [
    [
      "p",
      "e2260a7af33b3ba30074111c456793cef58d2ab43c5965bdbb655f90f97399ac"
    ],
    [
      "e",
      "ef2c8a8cd6224643b1ace7cb3e7298f0aeff09a47d0e666a27414c1b8c049ca7",
      "wss://relay.damus.io"
    ],
    [
      "p",
      "6389be6491e7b693e9f368ece88fcd145f07c068d2c1bbae4247b9b5ef439d32"
    ]
  ]
}
```

**Comment by mikedilger** [comment]
Reposts originally specified that the content should be empty.  Now it says (to be backwards compatible) "It MAY also be empty, but that is not recommended".  In this case, the "e" tag (or could be "a" tag) points to the event being reposted.

**Comment by mikedilger** [comment]
It looks like this word "shishi" is not in the raw event you posted, so I'm assuming gossip is displaying the contents of the event pointed to.  There is no bug here.

**Comment by bu5hm4nn** [comment]
Ok, but then there should be Reply, Quote, etc buttons. So I'll look into why there's no buttons.

**Comment by mikedilger** [comment]
oh I didn't notice.

**Comment by bu5hm4nn** [comment]
Found it. I had coded the lazy assumption back in the day (around a year ago) when implementing the repost logic, that the e-tag was always the [0] tag. So it was pulling the [0] tag and that was a mentioned pubkey (shishi in this case).
