### ISSUE TITLE
Remove wss:// protocol from the view and highlight unsafe connections

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#702]
Relays usually offer an encrypted connection; an unsecured one is a rarity, perhaps a development test or perhaps a fraud attempt.
The protocol takes up space (5/6 characters), does not help much identify the unsecured ones because it is not easy to notice the missing "s" and makes it harder to read the relay domain.
So why can't we take the secure connection for granted, omitting the protocol, and highlight the unsecured one?
Something like that:

<img width="938" alt="Screenshot 2024-03-29 alle 13 04 57" src="https://github.com/mikedilger/gossip/assets/89577423/98d45f1b-5242-45d7-af5e-daa13f94f9db">
<br/><br/>

I usually like to expose the details of the protocol, but in this particular case, at least as far as crowded views are concerned, this approach seems to be an improvement.

@mikedilger @bu5hm4nn @fiatjaf opinions?

**Comment by fiatjaf** [comment]
I think we don't need the TLS stuff at all. On Nostr every connection is secure. In fact I would rather not have any TLS anywhere. It would be better.

**Comment by dtonon** [comment]
Tampering is not a problem, of course, but don't we value privacy and non-traceability that an encrypted connection bring?

**Comment by mikedilger** [comment]
AUTH requires an encrypted channel, or else the next message might not even be the same actor.  If I had paid attention to AUTH I would have suggested an alternative.

My crypto professor insisted the the whole concept of a 'secure session' was entirely too complex to reason about mathematically, and so he always worked from MACs (message authentication codes) when doing provable security in cryptography... essentially digitally signed messages, who cares who sends them, even the devil himself can send them they are still trustworthy if signed.

BUT I would also have given relays a pubkey pair. Then users can trust which relay they are talking to, and TLS can truly go away. And relays can move to different IP addresses and DNS can go away, IP addresses being transient relay locations published in a nostr list for that relay identity.

OK enough of that.  As to your question @dtonon I'm ok with this to save space if you wanna do it.

**Comment by bu5hm4nn** [comment]
@dtonon What is your final take on this compared with the current implementation?

**Comment by mikedilger** [comment]
This was done already
