### ISSUE TITLE
User mentions overwrite urls

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#706]
The url is not clickable and the "fiatjaf" highlighted part is linked to the profile.
A quite rare bug!

<img width="743" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/3f221208-3e07-4c00-a8e9-413949efb5df">

**Comment by dtonon** [comment]
@bu5hm4nn I assigned this to you because you worked on the mentions

**Comment by bu5hm4nn** [comment]
Can you add the nevent for this?

**Comment by dtonon** [comment]
Oh sorry, [here it is](https://njump.me/nevent1qqsqqqqqpmq6rellufe7pmanedxzatyxlh0gtphsx92wmt43a08u3pgprfmhxue69uhkymmnw3ezumn0ddhhgctjduh8wmmjdvhsz9mhwden5te0vdsjuun9d3shjctzd3jjummjvuhszenhwden5te0ve5kcar9wghxummnw3ezuamfdejj7mnsw43rzwrt0fargmrtv36xxdtwxuerj6mkve6ku7r40gersdm4we6nje3kx3uhw6r20g6rxunpxsuryapj0y6hx6mnxpkhsdtn0glkyun0v9jxxctnws7hgun4v5dghpae).
And checking the njump preview I just realized that the problem is not the rendering, but the creation of the event! (by Gossip)

**Comment by bu5hm4nn** [comment]
Ah yes, we text replaced more than once

**Comment by bu5hm4nn** [comment]
Before fix:

https://github.com/mikedilger/gossip/assets/3328670/791c9dd4-2ffd-49f2-86d5-54e60fd00d1c

After fix:

https://github.com/mikedilger/gossip/assets/3328670/b5d9c094-42cf-477e-93ec-1fe1be256dc3

**Comment by mikedilger** [comment]
So this was merged. Presuming fixed.
