### ISSUE TITLE
I can't tag anybody

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#707]
Again I am having trouble tagging people.  I type "@pabl" and I get a popup list.  But when I click an entry in that list nothing happens.  It drives me insane.

There is a note I wish to write, but I will have to use another client for the time being I guess.

This is a blocker for 0.10.

**Comment by bu5hm4nn** [comment]
I believe you are experiencing this bug: 
https://github.com/emilk/egui/issues/4147

If you move the mouse over to the right of the text until it turns to a hand cursor and then click, it should work.

**Comment by mikedilger** [comment]
Yes, you are correct. I had not noticed the cursor change in those areas. Odd that I have to search for an invisible spot where the cursor icon changes.

**Comment by bu5hm4nn** [comment]
@mikedilger I added it to the existing PR that also addresses tagging issues

**Comment by mikedilger** [comment]
This has been fixed on 0.10 and unstable via a recent PR.
