### ISSUE TITLE
Relay section cuts sidebar

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#709]
When you switch to this section, the sidebar is cut off:

<img width="924" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/d14577b6-5605-4a74-94db-5b1d909ac75b">

**Comment by bu5hm4nn** [comment]
It's due to the reason string. We should truncate it.

https://github.com/mikedilger/gossip/assets/3328670/48384716-1c7c-44e0-bc10-adda51d06fdd

**Comment by dtonon** [comment]
I would move them to the "details" view, and let them eventually wrap.
If I'm not wrong I already proposed this, but maybe @mikedilger didn't like it?

<img width="853" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/a400cf26-6add-44bc-98d8-ceabfd9528df">

**Comment by mikedilger** [comment]
Yeah I don't want them in the details.  FAR too much clicking to figure out what is going on.

**Comment by dtonon** [comment]
@mikedilger details setting is remembered during the session, so it is a one time switch; maybe we can also make it persistent. Or do you want to see just the activities and not the stats?

**Comment by bu5hm4nn** [comment]
What if we only show the reason string when the debug stats are turned on?

**Comment by dtonon** [comment]
For me this solution is also fine.
In this case I would align the reasons to the left, use a different color (as in the new notification view) and implement text wrapping (that work poorly with the right alignment).

**Comment by mikedilger** [comment]
> What if we only show the reason string when the debug stats are turned on?

I'm OK with that. Solves my problem. If the wrapping sucks under debug stats, it's less impactful to normal users.

**Comment by mikedilger** [comment]
is this fixed?

**Comment by bu5hm4nn** [comment]
Well you cherry picked it onto unstable but it got overlooked for 0.10.

**Comment by mikedilger** [comment]
It's on the 0.10 branch.

**Comment by bu5hm4nn** [comment]
Oh, then I overlooked it
