### ISSUE TITLE
edit/annotate

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#710]
https://github.com/nostr-protocol/nips/pull/1091

**Comment by mikedilger** [comment]
This is done as soon as @dtonon reviews the interface.  Daniele, your posts have an "A" button on the bottom line.  That button allows you to add an annotation (e.g. an edit like "EDIT: Oops I means bob").  Supporting clients will see the annotation rendered inside your post.  Non-supporting clients will see the annotation as a reply.  Replies to the annotation will show up in gossip as replies to the original note.

**Comment by dtonon** [comment]
Annotate is a low frequency action, I would simply move it within the dropdown menu.

But this menu is growing.
@bu5hm4nn can we group all the "copy" actions under a single voice, and open laterally on the left a sub-menu?

Btw I will propose a note restyling asap, so we care rearrange the whole design, if necessary.

**Comment by bu5hm4nn** [comment]
@dtonon Yes of course we can group the copy actions
