### ISSUE TITLE
Reaction options

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#711]
'+' rendered as a heart is a meager kind of reaction set.  We show others, but don't offer our users a choice of reactions.

**Comment by mikedilger** [comment]
This is basically working on unstable, but it could use UI cleanup (I used menu_button which gives an ugly background, but at least lets the emoji picker work).

@dtonon @bu5hm4nn

**Comment by bu5hm4nn** [comment]
I restored the label and manually handled the menu so it would visually match again a4b8c83a08689f6018b6a126bf55108ed49da9a2

**Comment by mikedilger** [comment]
Thanks @bu5hm4nn looks much better.  We can keep thinking about and revising the display under a different issue. Closing.
