### ISSUE TITLE
The AppImage of the 0.9 version is missing

### ISSUE THREAD

**Issue by hardBSDk** [mikedilger/gossip#712]

**Comment by mikedilger** [comment]
I know.  My system of building AppImage was bad, and I only came up with a better system after 0.9 was released.

It has been more than 3 months, and I'm sorry it is taking so long, but version 0.10 will be released soon (I tried today, then I found show-stopper bugs).

I'd rather not try to do an AppImage on 0.9, I'd rather if you wait a few days for 0.10.
