### ISSUE TITLE
Pending: presumes local copy is correct

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#714]
When lists are out of sync, oftentimes the remote copy is newest.  So "Publish Now" and other language about publishing is not correct.  We need to let them manage it on the list page which shows dates and counts so they can think about which one is correct.

**Comment by bu5hm4nn** [comment]
<img width="867" alt="Screenshot 2024-04-15 at 11 24 09" src="https://github.com/mikedilger/gossip/assets/3328670/755a3c5a-2adc-4061-bcc0-856040fdeb87">

So you are saying these covered 3 cases are not correct? We offer "Publish Now" buttons for the first two and a "Manage" button for the last one.

**Comment by mikedilger** [comment]
That middle one should also be a Manage button.  Because sure it has been 90 days since I ran my client on windows, but during those 90 days the nostr relay events were updated many times.  So the right solution is for me to pull in the current lists, not to clobber them with my local old lists.

**Comment by mikedilger** [comment]
NotPublishedRecently is probably a bad term. Might be we should rename it.

**Comment by mikedilger** [comment]
Hang on, maybe my code is what is wrong.  Maybe I should be handing you a case-3 situation and I'm wrongly handing you a case-2 situation.
