### ISSUE TITLE
A repost fails to render

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#721]
This repost with embedded kind-1 is not being rendered:

nostr:nevent1qqsyga9v75t7fkpxhs8sddv5srmut74j5uwnvkfuj7gpvlgwn8und8gpzamhxue69uhhyetvv9ujuurjd9kkzmpwdejhgtcy9kt5e

**Comment by bu5hm4nn** [comment]
The embedded kind-1 does not pass serde parsing.

```
missing field `sig` at line 1 column 752
```
