### ISSUE TITLE
Persist NIP-46 request approval

### ISSUE THREAD

**Issue by bu5hm4nn** [mikedilger/gossip#724]
https://njump.me/nevent1qqsxj9l87eqxfp3z9gkhre7k2pdz956fada80n7ma7qenwedw8shp0qprfmhxue69uhhq7tjv9kkjepwve5kzar2v9nzucm0d5hsz9mhwden5te0wfjkccte9ec8y6tdv9kzumn9wshse8gnu9

**Comment by bu5hm4nn** [comment]
@mikedilger I am assuming somewhere at overlord 1766 we need to store the `server` object in order to persist the permission, right?
<img width="835" alt="Screenshot 2024-04-19 at 15 15 10" src="https://github.com/mikedilger/gossip/assets/3328670/9d7c0a28-3fda-491a-870d-8855ddbec850">

**Comment by bu5hm4nn** [comment]
we should probably do a 0.10.1 with this addition

**Comment by mikedilger** [comment]
Aha I didn't see this ticket until I saw your telegram comment.  Anyhow, this is closed now.
