### ISSUE TITLE
People List - Can't Sync

### ISSUE THREAD

**Issue by AngusP** [mikedilger/gossip#727]
I'm seeing this:

<img width="385" alt="Screenshot 2024-04-22 at 21 46 53" src="https://github.com/mikedilger/gossip/assets/1328814/76db81e5-3a5e-4f9c-8c08-0e1bbad7fe05">

Surely as the count and the event date don't match the lists aren't synced, but the button to sync isn't showing 🤔. I recently switched from using the homebrew cask to local compile on a6b529ab59ab9c0f323efc495f441051a5d5ba03 (v0.10.0) Mac aarch64 but AFAICT brew is [also on `v0.10.0`](https://formulae.brew.sh/formula/gossip#default).

I've tried adding some new follows in Gossip, and adding some in another client (Damus + Primal) to 'nudge' it but that doesn't seem to have worked.

Tangentially, perhaps a "publish anyway" button would be useful?

**Comment by mikedilger** [comment]
I've been working on fixing this over the last couple of days, turned out to be a deeper problem than I expected.

**Comment by mikedilger** [comment]
If you are doing a local compile, I would love if you tried out the 0.10 branch, which I think is ready to release as 0.10.1 and fixes this bug (as well as a few others).

NOTE: If you have run master or unstable recently you will have a newer database and won't be able to use the 0.10 anymore on that database

**Comment by mikedilger** [comment]
I released 0.10.1 (which fixes it one way) and also upgraded master (which fixes it a different way).

Please confirm.

**Comment by AngusP** [comment]
Thanks, I'll test the v0.10 branch soon and get back

**Comment by AngusP** [comment]
Yep, `v0.10.1` 622ff8c0ddaefe40830199571f5f76229ba7be5a fixed it 🎉
