### ISSUE TITLE
Cant republish list that is in sync

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#734]
Pending says list hasn't been published in a while.
But because it is in sync there is no publlsh button.

**Comment by bu5hm4nn** [comment]
Is it triggering `PendingItem::PersonListNotPublishedRecently` ? That one has a publish button.

**Comment by mikedilger** [comment]
Oh.  I forgot about that.  On the list page itself where the buttons are (overwrite, etc) there is no button.

**Comment by bu5hm4nn** [comment]
Ok, I thought you were talking about the Pending section. Should we nonetheless make sure the publish button is always present on the list page itself?

**Comment by mikedilger** [comment]
It was certainly a bug if there was no way to do it, but now that I know of a way to publish it isn't as important.

But yes, maybe we should always allow publish?

**Comment by bu5hm4nn** [comment]
I proceeded to always show the action buttons (more control for the user). 

We should maybe also review if we are correctly comparing the lists for changes? In my screenshot the dates are quite different.
<img width="912" alt="Screenshot 2024-06-12 at 12 54 46" src="https://github.com/mikedilger/gossip/assets/3328670/7d7e9e1c-4d9d-4c9d-9128-886cb8871e76">
