### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by nikmit** [mikedilger/gossip#739]
I've added a password to protect my private key, then forgot it...

I don't see a way to reset it, e.g. by re-entering the private key (which I do have), like I did to initially import my account.

My only option seems to be to reinstall?

**Comment by nikmit** [comment]
Thanks! A noob concern, but I wasn't sure if the delete identity option might invalidate my keys in some way, requiring the setting up of new ones :D

**Comment by mikedilger** [comment]
Nope. We should probably not have such strong danger warning.
