### ISSUE TITLE
Can't click into DMs

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#748]
Since I merged your latest PR I can't click into my DMs @bu5hm4nn .  Thinking this might be like why i couldn't tag people, I searched for a place where my cursor changed but it is always a hand and never works.

**Comment by bu5hm4nn** [comment]
I'll fix it in the next 3 hrs

**Comment by bu5hm4nn** [comment]
fixed in 09f959495981ec55001a25adf40f4772eec7f02e
