### ISSUE TITLE
Better "content is loading" view

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#749]
When the user access a section that has not been cached, he faces an empty page with a "load more" button for some seconds,  and of course the button is useless in this context:

![image](https://github.com/mikedilger/gossip/assets/89577423/a424a3c7-df99-4081-85c3-affacc4cdb1e)
<br/><br/>

We should remove the button and add a message / soft animation:

![image](https://github.com/mikedilger/gossip/assets/89577423/5b9b9f10-60f0-417a-ab24-0346c0300481)

While the loading is operative, any element on the top bar or other parts of the view should be hidden.

**Comment by bu5hm4nn** [comment]
done

**Comment by mikedilger** [comment]
This spinner hides the ability to load more.  UNTIL we load a COUNT, we might have a date range with ZERO notes and the spinner goes forever, never giving me the option to load the earlier batch of notes.  So I have reverted this.

See this thread: nostr:nevent1qqs2kln497095rxvc5ecwl5rmf23kv2z6p067x5dk2ywtheu4amdacsprfmhxue69uhhq7tjv9kkjepwve5kzar2v9nzucm0d5hse8mwaf

**Comment by dtonon** [comment]
> we might have a date range with ZERO notes and the spinner goes forever

The button should appears after we are sure we have zero results.
Of course, as you stated on the mentioned thread, the ideal solution is to simply see the last notes of a feed/profile.

**Comment by mikedilger** [comment]
> Why didn't you just show the buttons instead of removing the whole spinner?

I didn't dig into it, I just wanted it to work.  It is probably a better idea.

**Comment by mikedilger** [comment]
This is fine.  Once I solve the problem of feedback as to whether anything is ever going to load or not (starting from all the relays involved giving EOSE) then we can change the 5 second thing to when we actually know.  But for now 5 seconds is good enough.
