### ISSUE TITLE
Figure out cut-n-paste in egui

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#75]
I want to cut URLs and KEYs and paste them elsewhere.

**Comment by mikedilger** [comment]
See:
https://github.com/emilk/egui/issues/2033
https://github.com/emilk/egui/discussions/353

**Comment by mikedilger** [comment]
Paste:  Paste works with CTRL-V which is what most people use.  Unix/X11 middle-click from the alternate cut-n-paste buffer doesn't work but it is not important since CTRL-V works.

Cut:  Text selection generally is not implemented in egui, except in a text edit area (afaik).  We could dig into that code, but instead I built a clickable CopyButton icon which I can catch the clicked() on and copy whatever into the cut buffer via ui.output().  So that's working, but it requires cut buttons wherever people need them.  Maybe good enough.

Given the low likelihood of upstream movement on this in the near term I'm going to close this issue.

**Comment by tmathews** [comment]
Doesn't seem to work for me. Using Sway (Wayland) as my window manager. Any ideas?

**Comment by tmathews** [comment]
Ah found the relevant log:
```
Cannot initialize smithay clipboard without a display handle!
```

**Comment by mikedilger** [comment]
We all get that "smithay clipboard" bug and yet we can still paste with CTRL-V (and cut by pressing the cut icon).  But maybe that bug is relevant under wayland I just don't know, I'm still using X11.

**Comment by tmathews** [comment]
Thank you for the info!
