### ISSUE TITLE
Show when offline mode is active

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#751]
If the user starts in offline mode (it could be also an error or a test), there is not alert about that in the interface.
We can add a little badge on the sidebar:

<img width="665" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/45864427-adcc-4f4f-9269-9d940632894e">

**Comment by bu5hm4nn** [comment]
I think we should put a switch somewhere (like Sparrow wallet)

**Comment by dtonon** [comment]
Yes, it could be a nice as emergency switch.
We can use the same area:

<img width="518" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/afc425c5-ee34-4356-b876-5cf2334680fb">

The background is reverted to grey when the setting is off

**Comment by bu5hm4nn** [comment]
What does this look like when we are not offline? What background color?

**Comment by dtonon** [comment]
<img width="512" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/80f56394-589c-491c-9bb3-c681ac2b2f4c">

You can find it in the figma for the details
(added right now)

**Comment by bu5hm4nn** [comment]
Wow that was quick!

**Comment by bu5hm4nn** [comment]
@dtonon ready for testing on unstable

**Comment by dtonon** [comment]
Some tweaks:

1) Use the proposed texts ("Offline mode disabled/enabled"), since it is a switch and not a button
2) When the offline mode is active the top border in not necessary
3) When the offline mode is deactivate the text should be dimmed
4) In dark mode, the top line should be barely darker than the background

Result:

![image](https://github.com/mikedilger/gossip/assets/89577423/35f1f6b9-ccda-47a8-b867-04db314193d0)

![image](https://github.com/mikedilger/gossip/assets/89577423/ce5b02b5-4fa6-4bdb-aba0-bf9fcd7f2ea5)

Applied in 42130dc5

**Comment by dtonon** [comment]
@bu5hm4nn I also fixed in 6a7fe30d the vertical alignment of the label in the switch component, it was too hight.
It is a nasty hack but it should work, please take a look at it.

**Comment by mikedilger** [comment]
github autoclosed this when I pushed the branch with a commit referencing this. I'm reopening it so you two can decide if that was correct.

**Comment by dtonon** [comment]
I would like to reduce the length of the text to make the sidebar narrower, but this would involve working on the font size and the space of the counters below. Since we have more urgent things to worry about, for now let's close it.

**Comment by mikedilger** [comment]
"offline mode disabled" is a quite verbose way to say "online", so if you wanted a narrower sidebar, there is a way.

**Comment by dtonon** [comment]
I agree, it is too verbose. But the focus is on the _offline_ possible status, and usually switches have a fixed label, so It should not be changed (too much) when changing state. Maybe "Offline mode" is sufficient, adding an "ON" when active:

![image](https://github.com/mikedilger/gossip/assets/89577423/8aac7672-7dd5-4ad9-8641-04fe0d4c2ac9)

Is this ok for you?

**Comment by dtonon** [comment]
> I think it is even ok to say "__O Online" by default and "O__ Offline" if they switch it. 

This would mean having the active status of the switch on _online_, but we want to highlight the _offline_ one, because is the "expecption". Then I would prefer a slightly longer text, it is more visible and has a better graphical impact.
I pushed my proposal, let's see how it works.
