### ISSUE TITLE
Inbox - Everything shows one's own notes

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#752]
They should be filtered out.

<img width="840" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/c4bb02f5-a32b-480f-98b8-a5883ffbe71d">

**Comment by mikedilger** [comment]
feed.rs line 439-441 should be filtering this out.  I wonder why it isn't:

```rust
// exclude if it's my own note
if e.pubkey == my_pubkey {
    return false;
}
```

**Comment by mikedilger** [comment]
It was accepting giftwraps and DMs first before hitting those lines.  Can you confirm that this note was a DM or giftwrap note @dtonon?  I'll put the fix, but if this was a regular note, then this fix won't be enough.  Try unstable and let me know.

**Comment by bu5hm4nn** [comment]
Hey @mikedilger, I added those lines you quoted to fix this bug, so I think it can be closed.

**Comment by mikedilger** [comment]
Oh I see. Hah!

**Comment by dtonon** [comment]
@mikedilger sorry for the delay, it's a regular note.

> feed.rs line 439-441 should be filtering this out. I wonder why it isn't:

I actually pushed 68067672 (courtesy of @bu5hm4nn) after opening the issue, but I forgot to update the issue.
