### ISSUE TITLE
passphrase doesn't save 

### ISSUE THREAD

**Issue by GretaFrank** [mikedilger/gossip#760]
i set up gossip on new PC but my caps lock was on when i entered the passphrase

when i try to change it to same pass without caps it doesn't save - the old one stays

i mean i can login but i have to use the original all caps password and can't seem to change it

not a major issue, but something that could be improved ...

**Comment by GretaFrank** [comment]
actually i think i know what the problem is.  the "save changes" button is missing.

when i went to UI page and tried to change DPI it was missing as well.

then when i went to change FPS it suddenly appeared.

so the "save changes" button doesn't seem to always appear when you need to save changes ...

**Comment by mikedilger** [comment]
You are correct, it is broken.  Changing the passphrase is a path almost never taken, so I didn't notice when I broke it.

**Comment by mikedilger** [comment]
fixed on unstable.
