### ISSUE TITLE
scaling at high resolution ( yes, again )

### ISSUE THREAD

**Issue by GretaFrank** [mikedilger/gossip#761]
finally set up Nostr ( both Gossip and NoStrudel ) on my my biggest PC ( 75" 8K screen ) and here is what it looks like:

![image](https://github.com/mikedilger/gossip/assets/146442815/63b6e639-bd3a-4093-88c7-75731b5c3ed3)

![image](https://github.com/mikedilger/gossip/assets/146442815/41a990f7-1638-4f8e-b29b-90f25761787d)

![image](https://github.com/mikedilger/gossip/assets/146442815/cdbd4f48-a0c1-4710-9eef-55b436f8392d)

the above screen shots are full screen.  the one below is cropped so you don't see the name on my windows account 

![image](https://github.com/mikedilger/gossip/assets/146442815/c8597d00-a10d-4d00-a987-435064463321)

as you can see NoStrudel scales fine, but with Gossip 250 dpi falls just a bit short.  

yes i know i already complained about this back from my old 4K PC and it seems it was improved since then. 

my two main PCs are still QHD laptop and 4K 55" screen desktop, and i don't often use this 8K system yet ( it will become my main system eventually ) but wanted to give you guys a heads up ...

also as you can see i am already applying 400% scaling in Windows 11 which means most apps look as if i was running a regular 1080p screen ( except 4 times less pixelated ) yet even with 400% scaling and maximum 250 dpi in gossip the text looks a bit small ...

it isn't hard to read by any means, not on a 75" screen anyway, but i do feel like screen real estate is being wasted compared to how i have NoStrudel set up, which allows two separate degrees of adjustment - it offers 4 different column widths ( small, medium, large and full screen - i am using medium ) and you can use Ctrl+ and Ctrl- for an almost infinite range of scaling adjustment.

with Gossip there is no way to narrow the column to center of screen and 250 dpi isn't quite enough.

yes we been through this before i know Mike says this is boring, yes it is perfectly usable as it is now, but it looks better in NoStrudel as you can see so i am showing you the screen shots.

on the upside i like how avatars are bigger in Gossip.  i asked Hzrd to make avatars bigger and he said no.

i also noticed in Gossip when window is stretched pictures get larger, but text does not.  i guess this is how most applications act and how things are "supposed" to work, but i personally don't like when text is stretched into thin lines across the screen ... i like large easy to see text in tight narrow columns.

no suggestions or requests.  just sharing what i see / think on my end.

**Comment by mikedilger** [comment]
I just changed the max DPI slider setting to 400 on unstable.

**Comment by bu5hm4nn** [comment]
And I added that you can enter custom values in the text field after the slider if you want to go beyond 400

**Comment by GretaFrank** [comment]
thanks guys, i would certainly try this "unstable" if i knew where to find it ( all i see is 0.10.1 from 3 weeks ago )

i'm too stupid to build from source so if that's what you mean by "unstable" i will just wait for next release

thanks again

**Comment by mikedilger** [comment]
I'll presume this works and you'll get the update when we next release.  I don't plan to add any more big features before the next release, just to stabilize and fix bugs, so maybe in three weeks or so.
