### ISSUE TITLE
NIP-17 issues

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#770]
- [x] We need to be able to set DM relays (UI work)
- [x] I need to publish my relays afterwards and make sure the 10050 event is right
- [x] The only 10050 event my client has found is Vitor's. But when I DM him the client says I must use NIP-04 still.  Is that because I don't have DM relays set myself? Probably. In this case we should offer a better explanation.

**Comment by bu5hm4nn** [comment]
> The only 10050 event my client has found is Vitor's. But when I DM him the client says I must use NIP-04 still. Is that because I don't have DM relays set myself? Probably. In this case we should offer a better explanation.

I am also getting that message when trying to DM Vitor. And my client has also not found DM relays for you @mikedilger.

**Comment by mikedilger** [comment]
That is because I haven't published DM relays because there are no DM switches yet.   There also might be bugs in the code because it hasn't been fully tested yet.
