### ISSUE TITLE
Broken relay hints

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#787]
Look at this: https://njump.me/nevent1qqsfedgyqqegcpl8ehu30c6kh73xv9lclpmc2wg3gzl602ce4d860wqppemhxue69uhkummn9ekx7mp0qyghwumn8ghj7mn0wd68ytnhd9hx2tcpzdmhxue69uhk7enxvd5xz6tw9ec82c308y2xpy

I've pasted `nostr:nevent1qqs8j03ggurgk63u9elt986jvpmh8g70jkksj9qz3caw79m8t695p5qprfmhxue69uhhyetvv9ujuam9wd6x2unwvf6xxtnrdaksyg8yvswsamt36tgvpa5v6dgg658umvv4ftquek3xnhdm0fuf0s3xzsuysgm5` into the Gossip text box and published this note with it.

Gossip added a relay hint that is different from the relay hint contained in the `nevent` code, God knows where it got that hint from. And it's a bad hint, the note is _not_ at the specified relay.

**Comment by fiatjaf** [comment]
The same thing happened here: https://njump.me/nevent1qqsvjjmnjyqjyynkeuhcaw7sqjjr75ud7ktsv3n5zn06avzzest0fxcppemhxue69uhkummn9ekx7mp0qyghwumn8ghj7mn0wd68ytnhd9hx2tcpzdmhxue69uhk7enxvd5xz6tw9ec82c30n44sk5

**Comment by mikedilger** [comment]
Aw man!  And I thought I wasn't stupid because I could see the note.  Turns out I am stupid for other reasons.

Investigating...

**Comment by mikedilger** [comment]
Ok I pushed a quick fix for nevents (it will use the first relay in the nevent).

I will go on to fix how it selects hints when it doesn't obviously have one by ensuring it is a relay where the event was seen (coming soon).

**Comment by mikedilger** [comment]
ok both fixed.
