### ISSUE TITLE
Merging and Overwrite followed does now work

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#793]
Starting point:

<img width="399" alt="image" src="https://github.com/mikedilger/gossip/assets/89577423/d388c51a-4f02-4c39-a704-42d895047864">
<br/><br/>

If I press `Merge` or `Overwrite` nothing happens, the local counter is not updated, no logs in the console.

Then I tried to publish and it worked perfectly.

Finally I tried to follow a new person with another client, the remote counter increased immediately by one, but the `Merge` and `Overwrite` commands still don't work.

**Comment by mikedilger** [comment]
Verified, same happens to me.

**Comment by mikedilger** [comment]
possibly a deadlock causing it not to complete also causes gossip not to exit cleanly.

**Comment by mikedilger** [comment]
squashed.  Thanks for the report
