### ISSUE TITLE
Request: Thai language

### ISSUE THREAD

**Issue by vazw** [mikedilger/gossip#797]
![image](https://github.com/mikedilger/gossip/assets/8637706/b8f16d5c-d22b-4765-b526-2694b690a361)

and I have some problem trying to connect to my local-relay  (nostr-relay-tray) `ws://localhost:4869` any idea whit this?

**Comment by bu5hm4nn** [comment]
Hey @vazw . How did you install gossip?

I'm not sure if Thai would be included in `lang-cjk` support. If you compiled from source you can run `cargo run --features=lang-cjk --release` to enable it.

Otherwise please post an nevent link to a thai event so we can debug (I don't see any in my feed).

**Comment by vazw** [comment]
> Hey @vazw . How did you install gossip?
> 
> I'm not sure if Thai would be included in `lang-cjk` support. If you compiled from source you can run `cargo run --features=lang-cjk --release` to enable it.
> 
> Otherwise please post an nevent link to a thai event so we can debug (I don't see any in my feed).


 `cjk` does not include tlwg/libthai
it's a total diffrent language phonics.

you can try with this [event](https://njump.me/nevent1qvzqqqqqqypzpkpsaeahcv9rvjcjgjmhntamfu2kwvllhry8ydggdcntpd8xrntzqyv8wumn8ghj7un9d3shjtnwda6x7umgdyh8w6tw9uq3samnwvaz7tmjv4kxz7fwwd5kzmtnw3ezucm0d5hsqgzxq75y7nuud59ts2pxmhqrj94ph26g7jq03hmv02nagq7ajs3zru4kyk7a)

**Comment by bu5hm4nn** [comment]
For `lang-cjk` all we do is add another font. So as I understand all we need is an open source thai font that we can package with gossip.

**Comment by vazw** [comment]
> For `lang-cjk` all we do is add another font. So as I understand all we need is an open source thai font that we can package with gossip.

`Noto` also support Thai langauge 
maybe we can use [Noto Sans Thai](https://fonts.google.com/noto/specimen/Noto+Sans+Thai/about)?

**Comment by bu5hm4nn** [comment]
@vazw I added the "Noto Sans Thai" font, as we already use Noto for CJK support. Does this screenshot look right or are there characters missing/wrong?

<img width="1248" alt="Screenshot 2024-06-24 at 14 39 45" src="https://github.com/mikedilger/gossip/assets/3328670/286824e9-8ecc-42a4-b694-9bd913b5a8a8">

**Comment by vazw** [comment]
> @vazw I added the "Noto Sans Thai" font, as we already use Noto for CJK support. Does this screenshot look right or are there characters missing/wrong?

That's the correct one! Thank you! it's look great🔥

**Comment by bu5hm4nn** [comment]
@vazw If you build from unstable (`git checkout unstable`) then you can already use it.

**Comment by bu5hm4nn** [comment]
@mikedilger Is there still a reason to have `lang-cjk` as a build switch or should we just compile the languages in as standard? I don't think there's collisions with unicode.

**Comment by mikedilger** [comment]
Thanks for adding this font @bu5hm4nn 

The reason --lang-cjk is a build switch is because the fonts are big and bloat the binary.  But maybe that doesn't matter much anymore.  Without them the binary is 43 MB (release, stripped) and 63 MB with them (release, stripped).  I think the complexity of this build option is probably not worth it anymore.
