### ISSUE TITLE
Scroll positions getting reset

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#799]
If I look at a person's posts with "View Their Posts" and then scroll down, if I come back later it remembers the scroll position I was previously at.

It used to do this with all feeds.

But now all the main list feeds as well as the INBOX reset to the top every time I come back to them.

Very annoying.

**Comment by mikedilger** [comment]
I checked and the egui ui passed into render_a_feed is distinct for each feed.  So it should know that these are different instances of the scroll area, and by virtue of that I thought egui would remember and even remember it between run in `app.ron`.  This has been a problem for a while but it is only annoying me enough today to bring it up.

**Comment by mikedilger** [comment]
The reason is that we empty the feed.  Once we do that and render an empty feed it can't maintain a deep scroll position.

We empty the feed because we are no longer keeping separate data for separate feeds, but keeping it in a shared vec.  That was probably a mistake.

**Comment by mikedilger** [comment]
I fixed this in def1be0c2812161bf6bccf9219c9974d0267129a

@bu5hm4nn can you take a quick look at where I moved your code to render the spinner, and make sure that doesn't mess anything up like padding or rounding or whatever?  The point of my change was not render a scroll area with no contents while we wait because that causes the scroll offset to reset to 0.

**Comment by bu5hm4nn** [comment]
Yeah, you can either do that, or set a different scroll area ID while it is empty since the recall happens by ID.

**Comment by mikedilger** [comment]
True I could have set a different id, but this seems even cleaner.  Anyhow I'll close this but you can still adjust this if it's wrong.
