### ISSUE TITLE
Unable to download images  - using unstable version 0.11 

### ISSUE THREAD

**Issue by ashutoshmjain** [mikedilger/gossip#800]
Gossip exits with this message in clip

> Got a texture image of size 7340x3048, but the maximum supported texture side is only 2048

Is this a configuration setting ? 

I am testing on unstable version 0.11  .. built this morning .

Thanks

**Comment by mikedilger** [comment]
The MAX_TEXTURE_SIZE is determined from your graphics card (via OpenGL) by a library gossip depends on (egui_glow).

Did gossip crash when this happened?  I'd love to get a backtrace, or maybe if you know the note that has the giant image and can point me to it?

If you use the `run.sh` script it should give you a backtrace when it crashes.

**Comment by mikedilger** [comment]
Actually I think I worked it out.  Pull and try again.

**Comment by bu5hm4nn** [comment]
@ashutoshmjain Please also let us know which OS you are running on. Especially Linux currently has many different configurations.

**Comment by mikedilger** [comment]
This commit should have fixed it, but I don't have a good way to test: 29cb75dd7b740a1fa3c65a11d566494c8f3ab0e7

**Comment by ashutoshmjain** [comment]
> @ashutoshmjain Please also let us know which OS you are running on. Especially Linux currently has many different configurations.

OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 5.10.0-9-amd64 
Uptime: 1 hour, 53 mins 
Packages: 1664 (dpkg), 282 (nix-user) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: Xfce 4.16 
WM: Xfwm4 
WM Theme: Default 
Theme: Xfce [GTK2], Adwaita [GTK3] 
Icons: Tango [GTK2], Adwaita [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 16 
CPU: Intel Core 2 Duo E6850 (2) @ 2.997GHz 
GPU: Intel 82G33/G31 Express 
Memory: 1247MiB / 3921MiB

**Comment by ashutoshmjain** [comment]
> This commit should have fixed it, but I don't have a good way to test: [29cb75d](https://github.com/mikedilger/gossip/commit/29cb75dd7b740a1fa3c65a11d566494c8f3ab0e7)

No  -- I rebuilt this morning  .. and I am update as of now  .. 

Here is the backtrace 

2024-07-03T02:19:46.808370Z ERROR gossip-lib/src/overlord/mod.rs:468: Minion wss://nostr.coinfundit.com/ completed with error: Websocket: IO error: failed to lookup address information: No address associated with hostname
thread 'main' panicked at /home/amj/.cargo/git/checkouts/egui-904381843a0f3282/63dde4c/crates/egui_glow/src/painter.rs:558:9:
Got a texture image of size 1800x2400, but the maximum supported texture side is only 2048
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: egui_glow::painter::Painter::upload_texture_srgb
   3: egui_glow::painter::Painter::set_texture
   4: egui_glow::painter::Painter::paint_and_update_textures
   5: <eframe::native::glow_integration::GlowWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   7: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
   8: eframe::native::run::run_glow
   9: eframe::run_native
  10: gossip::ui::run
  11: gossip::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2024-07-03T02:19:47.649408Z  WARN /home/amj/.cargo/git/checkouts/egui-904381843a0f3282/63dde4c/crates/egui_glow/src/painter.rs:763: You forgot to call destroy() on the egui glow painter. Resources will leak!

**Comment by ashutoshmjain** [comment]
> If you use the `run.sh` script it should give you a backtrace when it crashes.

I tried running this but I am getting libsdl2-dev issues  ...  let me know if you have a pointer  .. I installed it but looks like I am not able to properly link it  .. or something ...

**Comment by mikedilger** [comment]
Ok I tried another fix, please test again.

It is quite odd that it is trying to make such a large image. Perhaps you have a very high resolution monitor?  Or you set the DPI to an unusual setting?  It is nonetheless a bug.

**Comment by bu5hm4nn** [comment]
The issue is that you have a really old 3D graphics card (2007). The UI framework we use achieves cross-platform ability by rendering to OpenGL. If we can limit the texture size and make it work, that would be great, but that is quite old.

**Comment by ashutoshmjain** [comment]
> The issue is that you have a really old 3D graphics card (2007). The UI framework we use achieves cross-platform ability by rendering to OpenGL. If we can limit the texture size and make it work, that would be great, but that is quite old.

Totally agree ..and I dont expect this machine to load the images  .. in fact I was looking for "no image setting" .. 

That said , the program should not panic crash  .. may be give a message  ..

"you are too old for nostr "   :smile:

**Comment by ashutoshmjain** [comment]
> Ok I tried another fix, please test again.
> 
> It is quite odd that it is trying to make such a large image. Perhaps you have a very high resolution monitor? Or you set the DPI to an unusual setting? It is nonetheless a bug.

Yes  .. I  have a very good ( and big ) Samsung monitor ..

As for DPI  ..  it is same default 72  ..

**Comment by ashutoshmjain** [comment]
> Ok I tried another fix, please test again.

Magic  .. works like a charm 

much thanks :+1:

**Comment by ashutoshmjain** [comment]
Thanks for the quick response  ..  #gossip is probably the best thing happening to #nostr  .. keep up the great work 

cheers
