### ISSUE TITLE
Less secure DM technology ?? 

### ISSUE THREAD

**Issue by ashutoshmjain** [mikedilger/gossip#805]
Not a concern  .. just FYI .. hope this is on radar !

![Screenshot_2024-07-05_11-23-20](https://github.com/mikedilger/gossip/assets/17075281/5866bb41-b2c0-4597-805c-1e0f293ec2f7)

**Comment by mikedilger** [comment]
To use the new DMs, users have to choose and publish their new DM relays.  You, for example (if you haven't already) need to go into your relays and switch some of them (I recommend 2 or 3, not heaps, not just one either) to accept DMs for you, and then Advertise.  Creatr needs to do that too (or the equivalent thing on other clients).  Only once both of you have advertised DM relays can you use the new NIP-17 secure DMs.
