### ISSUE TITLE
lots of like icons push notes out wider

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#808]
![width-bug](https://github.com/user-attachments/assets/3d799098-b675-4908-8491-80cb1c446fc4)

**Comment by bu5hm4nn** [comment]
Yes, I can tackle this next. We'll sum the up next to the heart symbol as before but show the additional icons in a tooltip.

**Comment by bu5hm4nn** [comment]
Done, pushed to unstable

**Comment by mikedilger** [comment]
Cool.  Oh I also see this was a dup.
