### ISSUE TITLE
Very slow disk performance on btrfs

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#813]
Not sure if it is btrfs related, but crazy slow LMDB performance.  I tried MDB_NOMETASYNC but it is just as slow.

**Comment by bu5hm4nn** [comment]
Is there a command we can run to test performance on different platforms?

**Comment by mikedilger** [comment]
Ok I have created a "rapid" mode.  You have to start gossip with the rapid command, e.g. "gossip rapid".

This risks data corruption on a crash or sudden loss of power, if you use a filesystem that does not preserve write ordering. But it is **much** faster, and people can take backups or start over from scratch if their data gets corrupted.  The decision is now theirs.
