### ISSUE TITLE
Optimize reaction/emoji popovers

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#829]
We have 7 hearts in the reaction popover, and they are virtually indistinguishable since we don't render the colors.
The standard "like" reaction (+), used as default by many clients, is also buried between the emoji.

<img width="309" alt="image" src="https://github.com/user-attachments/assets/177a6e0d-6dc3-4501-b8cb-6c4b1a7a9944">
<br/><br/>

I would update the popover like this:

- Leave only one heart (the purple one?)
- Remove "+" from the popovers
- In the reaction context add before the emoji two links: "Like it" - "Dislike it" that produce "+" and "-" reactions.

**Comment by mikedilger** [comment]
Nobody does downvotes in nostr.  I think I found maybe 1 downvote ever.  So having a like/dislike might not even render in other clients.  I think nostr has just gone towards emoji reactions like github comments do.... but also the '+' is used very commonly too as a generic like.

So we have to have a "Like" button, but I think dislike isn't necessary.

We can also prune the hearts, but it's not clear which.  I'll leave that up to you.

**Comment by dtonon** [comment]
Your are right, the dislike is practically useless since is rarely used, I mentioned it only because its in the specs and I thought I saw it in the popover.

I don't have any strong opinion about the hearts, I don't use them, it just seems too me that the purple one is the most used.

**Comment by dtonon** [comment]
noStrudel has (of course) the dislike, rendered as 👎

https://njump.me/nevent1qqs2hk7k6ahrvdhsk06ac4eqjp52dca5ycmgn0tsctnknjljcfgp52gpz4mhxue69uhkummnw3ezummcw3ezuer9wchsygrmmmmmugka3evlgcqwq3922wsul966nhrayl04svauwldhsjjcq5psgqqqqqqsx0xjy2

**Comment by mikedilger** [comment]
implemented
