### ISSUE TITLE
Warning on build about dead code

### ISSUE THREAD

**Issue by SilberWitch** [mikedilger/gossip#849]
warning: associated functions `soft_dark` and `soft_light` are never used
  --> gossip-bin/src/ui/theme/default.rs:23:8
   |
22 | pub trait ShadowBuilder {
   |           ------------- associated functions in this trait
23 |     fn soft_dark() -> Self;
   |        ^^^^^^^^^
24 |     fn soft_light() -> Self;
   |        ^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `gossip` (bin "gossip") generated 1 warning

**Comment by mikedilger** [comment]
Yeah I'm leaving that in there.  It reminds @bu5hm4nn of something he was gonna use but didn't finish.

**Comment by mikedilger** [comment]
or maybe it was @dtonon  I dunno. One of them will eventually resolve it.

**Comment by mikedilger** [comment]
This is gone on unstable.
