### ISSUE TITLE
It's not possible to exit the Add relay modal

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#850]
The X icon on the top-right doesn't work, so the user is stuck on this modal and can only add something to exit.

<img width="690" alt="image" src="https://github.com/user-attachments/assets/895e910c-d615-4363-ba9c-7e8e1a0d00ad">

**Comment by jadijadi** [comment]
For me (Debian Linux/Gnome) it works BUT I have to exactly click on the X *lines* (and not the imaginary square where X is printed on).

**Comment by dtonon** [comment]
Thanks for the feedback @jadijadi, I confirm that on macOS it is not possibile to click it in any way.

**Comment by mikedilger** [comment]
Is this still a problem guys?  It works fine for me.  I haven't fixed anything, but please check unstable.  I don't want to release if this is still a problem.

**Comment by bu5hm4nn** [comment]
Was fixed in 95c053ad920e331487c761fe9596217b6237ec2b
