### ISSUE TITLE
Relay panel "test relay" with results

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#889]
There are now far too many "rulesets" for relays out there. It is very difficult for a user to choose their relays for (inbox, outbox, DM, discovery, spamsafe)

I propose we have a relay tester.  It probes the relay, tries to put an event on it, tries to read the event back, reads the NIP-11, and makes its best judgement as to whether the relay is appropriate for (inbox, outbox, DM, discovery, spamsafe).  Then people can just press the 'test' button and wait for the result, and if inbox gets a tick, they can maybe choose it as an inbox.

**Comment by mikedilger** [comment]
@bu5hm4nn we will want to change the relay_entry to make space where the NIP-11 data is for three outcomes, each with an icon next to it, maybe like this (@dtonon can decide):

✅ Inbox
❌ Outbox
 ?  DM

I haven't decided where it will pull data from yet, just mock something up and I'll plumb it when it is ready.

**Comment by bu5hm4nn** [comment]
But we already have the usage bits. How is this different? Do you want to show what the picker is using it for? Or a different way for the user to choose?

**Comment by mikedilger** [comment]
I already did it.  Try unstable, press test on a relay, see what I mean.

**Comment by mikedilger** [comment]
These things explain what the relay could be used for based on the test.
