### ISSUE TITLE
Update broke keys

### ISSUE THREAD

**Issue by RH89** [mikedilger/gossip#899]
So, appearently after updating to a newer version of gossip (which btw deleted the old files as well, which really shouldnt happen but here we are) it no longer accepts my old files, claims my passphrase is incorrect (which it defnitiely isnt) after previously heavily discouraging ever backing up any keys because that would degrade the key security to "low" without an explonation of what effect it would have for gossip/nostr for it to be considered "low".

**Comment by mikedilger** [comment]
Gossip does not delete your data files.

If you are upgrading from a version 0.8 or earlier, you need to take manual steps to upgrade.
See https://github.com/mikedilger/gossip/blob/master/docs/TROUBLESHOOTING.md

I have always encouraged backing up your key in encrypted form, and gossip exports that:  https://github.com/nostr-protocol/nips/blob/master/49.md   It is usable in some other clients too including fiatjaf's stuff.

Your gossip directory (if you have not overridden it with an env variable) is in here and named 'gossip': https://docs.rs/dirs/latest/dirs/fn.data_dir.html  Make a copy of the LMDB directory in case it becomes corrupted to make sure you don't lose your key.  I copy it like this:
`tar cvf - lmdb/ | zstd -c > lmdb.TODAY.tar.zstd`

**Comment by mikedilger** [comment]
You can also run "gossip export_encrypted_key" and it will export the encrypted key to the terminal instead of opening a UI window.  Then you can save that somewhere, or decrypt it with https://github.com/fiatjaf/nak

**Comment by RH89** [comment]
Yes, i noticed that you heavily discourage other ways of backing it up. Oh well, i only set up the account the other day (after first having installed it a long long time ago)... so have already set up a new account, not like there was anything of note on the existing one, was less than a day between setting it up and deciding i might want to update after its been installed so long (and there were some issues), this time backed it up as i usually back up my keys, in a textfile encrypted in a way that doesnt rely on a specific program on a drive i also keep disconnected from anything.
