### ISSUE TITLE
Switch to async or connection pool for sqlite

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#9]
possibly r2d2-sqlite or tokio-sqlite

Or somehow figure out if we can have many readers at once (I know it's only 1 writer, but can you have that writer going while readers are also going?)

**Comment by ok300** [comment]
Yes its possible.

I'm using sqlx with connection pools: https://docs.rs/sqlx/latest/sqlx/sqlite/type.SqlitePool.html

From what I've noticed, only one writer can access the DB at a time. While the writer is writing, all other DB IO is waiting. When writing is done, either next writer or next readers (in parallel) can access the DB.

Surely other frameworks expose similar APIs.

**Comment by mikedilger** [comment]
According to scsibug, sqlx is far too slow for this.  Blocking with tokio::spawn_blocking() seems to work very well.  I think I'm just going to stick with this as is for the time being.

**Comment by mikedilger** [comment]
I don't think this is going to make any difference so I'm closing.

**Comment by mikedilger** [comment]
I noticed you @ok300 are trying a branch ok300-sql-conn-pool.  I'd be interested to know if that turned out to be faster.  Spawning a task onto the blocking thread pool isn't free, so I suspect it could well be, and Stephen Fackler's stuff was always my first go-to choice for database stuff.

**Comment by ok300** [comment]
It's somewhat experimental, still not sure if it's worth a PR.

I have seen small improvements when switching views (going to a thread, then to a user profile, then load all his posts, etc). The UI feels more fluid.

But I didn't check whether it's subjective or it's really measurable. Will have to add tracing with timestamps around the SQL queries.

If there is any notable difference, I'll prepare a PR.

**Comment by mikedilger** [comment]
There are other benefits besides performance. In order to pass data into a newly spawned task you cannot use references you must copy. Sometimes this is a bear. The programming would be a lot simpler if we didn't have all this spawn_blocking() crap.

I'm going to reopen this because maybe this is something we should do.

**Comment by mikedilger** [comment]
I rebased your work on master, made a few tweaks and merged it.  I think it's better.

**Comment by ok300** [comment]
Thank you sir.
