### ISSUE TITLE
Avoid compacting the database if there's not enough space for the backup

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#908]
As per title.

**Comment by mikedilger** [comment]
I don't know how to determine if there is enough space.  Rust std doesn't offer any such function and I can't seem to find a rust crate that does it either.

But if it fails, it erases the partial copy and then keeps running gossip.

And it only tries once per week.

If you find a better way, I'll do it.

**Comment by dtonon** [comment]
I confirm that now it's working fine!
I probably didn't pull the last commits, sorry.
