### ISSUE TITLE
Fail to show video URL

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#909]
https://njump.me/nevent1qqsy7xjyu9wsp979askq7fana7yxg8v0cv30dehf9ew7v82ezg5tx4spramhxue69uhkymmnw3ezumrfva58gmnfdenhxur0wfjjucm0d5hsyuuvcf

The video URL is missing on Gossip.
My build is compiled without the ffmpeg support.
I cannot test the support since currently I'm getting a compilation error.

<img width="708" alt="image" src="https://github.com/user-attachments/assets/15bc516d-4f53-44c4-a691-b873061990bf">

**Comment by mikedilger** [comment]
I just updated rust-ffmpeg and egui-video to support ffmpeg 7.1 (which also was giving me the compilation error).  So you can now build with ffmpeg support again.

But the issue you bring up is surely something I broke.  I updated media loading quite a lot to verify SHA signatures and to render blurhashes while waiting.  In that process I believe the [ Video ] link was removed in some cases (e.g. when the video itself was available (it has a link on the right-hand side)).  Maybe it got removed in a case that still matters and needs it.
